CONTRIBUTING.md, OWNERS, code-of-conduct.md
=> Initial commit with OWNERS, CONTRIBUTING.md and code-of-conduct.md.

.github/issue-template.md, .github/pull_request_template.md, CONTRIBUTING.md, DEVELOPMENT.md
Added a few missing docs based on list at
https://github.com/tektoncd/community/blob/master/process.md#project-requirements
=> Add any missing basic docs 📝

buildpacks/README.md
cnb.yaml doesn't exist, buildpacks-v3.yaml does exist.
review them:
=> Fix typo in buildpacks/README.md

DEVELOPMENT.md
The goal of this commit is to add a set of "requirements" and guidelines
to serve as a starting point for maintainers reviewing new submissions.
I expect this will evolve over time as we get more experience maintaining
the catalog.
review them:
=> Add more documentation on development/contributing new submissions.

kaniko/README.md, makisu/README.md, makisu/makisu.yaml, makisu/registry.yaml
This adds a Task that builds an image from source in a Git repo using makisu. It's migrated from https://github.com/knative/build-templates/tree/master/makisu
cc @johscheuer 
review them:
=> Add makisu Task

jib-maven/README.md, jib-maven/jib-maven.yaml
Adds a Task for jib-maven
review them:
=> Adding a Task for jib-maven

kaniko/kaniko.yaml
Discussed in https://github.com/tektoncd/pipeline/pull/706
Fix https://github.com/tektoncd/pipeline/issues/848
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
review them:
=> kaniko: set DOCKER_CONFIG

buildkit/0-buildkitd.yaml, buildkit/1-task.yaml, buildkit/README.md
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
Add BuildKit Task
review them:
---
cc @tonistiigi @tiborvass
Push is currently untested due to https://github.com/tektoncd/pipeline/issues/848
=> Add BuildKit Task

makisu/README.md, makisu/registry.yaml, test/e2e-tests.sh, test/presubmit-tests.sh
This e2e test just verifies each task is valid by setting up a test cluster and
creating each task. This uses boskos to provision and clean a project.
review them:
=> Add a basic Task CRD validation test for all Tasks in the catalog.

buildah/README.md
Fix the typo in buildah 
review them:
- [X ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Fix the typo in buildah example

s2i/Dockerfile, s2i/README.md, s2i/examples/nodejs-s2i.yaml, s2i/s2i.yaml
Adds task that builds an image described by a using s2i.
Also provides dockerfile for generating s2i image needed for building.
Taskrun in ./examples is also 
review them:
=> Add s2i task 

Gopkg.lock, vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh, vendor/github.com/tektoncd/plumbing/scripts/library.sh, vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
Mainly to keep it up-to-date and get fixes for the CI.
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Bump tektoncd/plumbing with latest fixes

buildah/README.md, buildah/buildah.yaml, s2i/s2i.yaml
Change buildah image to official repository by buildah team
review them:
=> Change buildah image to official repository

buildah/buildah.yaml
Fixed a typo: `workingdir` -> `workingDir`
review them:
=> fix workingDir typo in buildah.yaml

golang/README.md
Add yaml type to the codeblock for syntax highlighting.
review them:
=> [docs] Add code type to codeblocks

openshift-client/Dockerfile, s2i/Dockerfile
* openshift-client/Dockerfile Make sure we cleanup after ourselves
* s2i/Dockerfile run yum update in docker image
=> s2i and openshift-client Dockerfiles improvements

kn/kn-create.yaml
Fixes #70
- changes the default value for `force` flag to `"false"`
review them:
=> Fix(kn-create): Updates the default value for force flag

OWNERS
:angel: 
/cc @bobcatfish 
review them:
=> Add bobcatfish to owners 👼

argocd/argocd.yaml, buildah/buildah.yaml, buildkit/1-task.yaml, buildpacks/buildpacks-v3.yaml, conftest/conftest.yaml, golang/build.yaml, golang/lint.yaml, golang/tests.yaml, jib-maven/jib-maven.yaml, kaniko/kaniko.yaml, knctl/knctl-deploy.yaml, kubeval/kubeval.yaml, makisu/makisu.yaml, openshift-client/openshift-client-kubecfg-task.yaml, openshift-client/openshift-client-task.yaml, openwhisk/openwhisk.yaml, s2i/s2i.yaml
Starting from 0.7.0, the later is not supported anymore.
review them:
=> Update templating to use `$(…)` instead of `${…}`

test/e2e-tests.sh
and make sure we are running in the task-ns namespace
/cc @vdemeester
=> Allow ignoring test if we like

buildah/buildah.yaml, buildkit/1-task.yaml, openwhisk/openwhisk.yaml
Seems like some yaml files were not updated correctly.
Resolves #91
Changed forgotten templates from brackets to parentheses
review them:
=> Updated forgotten brackets with parentheses

kaniko/kaniko.yaml
Bump to the most recent kaniko version.
/cc @ImJasonH 
review them:
=> Update kaniko executor image to 0.13.0

kaniko/kaniko.yaml
When for example we want to add --skip-tls-verify or other flags
=> Allow passing extra flags to kaniko

Gopkg.lock, vendor/github.com/tektoncd/plumbing/scripts/library.sh, vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
As the title suggest :angel: 
review them:
=> Bump tektoncd/plumbing dependency ⛽️

conftest/README.md, conftest/helm-conftest.yaml
This accompanies the Helm Plugin for Conftest. It uses Helm to render
the template before running the result through Conftest.
review them:
=> A new task related to Conftest which makes testing Helm charts easier

conftest/README.md
Follow up on https://github.com/tektoncd/catalog/pull/108 with the issues from the comments added post-merge.
review them:
=> Follow up commit to resolve README issues for conftest tasks

CONTRIBUTING.md, README.md, buildah/OWNERS, conftest/OWNERS, golang/OWNERS, kn/OWNERS, kubeval/OWNERS, openshift-client/OWNERS, s2i/OWNERS
This adds information on OWNERS of the whole project and Tasks.
And also adds some initial OWNERS file :angel: 
/cc @ImJasonH @dlorenc 
/cc @navidshaikh @garethr @chmouel @piyush-garg @khrm (as I added you in some task `OWNERS`)
Closes #4 
review them:
=> Update README and CONTRIBUTING with some submission guidelines 📖

kn/README.md, kn/kn.yaml
- kn v0.9.0 released image path gcr.io/knative-releases/knative.dev/client/cmd/kn:v0.9.0
review them:
=> Updates kn released image path and pins to v0.9.0

README.md
The purpose of this is to provide additional information on _how_ to join Slack and what some of the channels are as described in the contact info section.
review them:
=> Set slack link to contact info section for slack

buildpacks/OWNERS
Add OWNERS file to buildpacks task
review them:
=> Add OWNERS file to buildpacks task

ansible-tower-cli/README.md, ansible-tower-cli/ansible-tower-cli-task.yaml
Creation of a new TASK to run Ansible Tower CLI commands.
review them:
=> Add a task for tower-cli command execution Closes #106

kn/README.md, kn/kn.yaml
- Updates kn image tag to `v0.10.0`
- Updates README.md
review them:
=> References latest kn release v0.10.0 in task

OWNERS
This PR adds me as an owner on the catalog repo. I'd like to be able to approve new catalog entries :angel:.  Like this one: https://github.com/tektoncd/catalog/pull/126
I promise to be very careful with this power.
=> Add @sbwsg as approver in catalog

.yamllint, ansible-tower-cli/ansible-tower-cli-task.yaml, argocd/argocd.yaml, buildah/buildah.yaml, buildkit-daemonless/buildkit-daemonless.yaml, buildkit/deployment+service.privileged.yaml, buildkit/deployment+service.rootless.yaml, buildkit/task.yaml, buildpacks/buildpacks-v3.yaml, conftest/conftest.yaml, conftest/helm-conftest.yaml, golang/lint.yaml, kaniko/kaniko.yaml, knctl/knctl-deploy.yaml, kubeval/kubeval.yaml, openwhisk/openwhisk.yaml, openwhisk/service-account.yaml, s2i/s2i.yaml
Next update of plumbing will enable `yamllint` check, so this make
sure we have linted yaml before 👼.
Related to #101 (not closing it yet as the CI is not hooked up, needs tektoncd/plumbing#111 and a prow config update :stuck_out_tongue: 
/cc @chmouel 
review them:
=> Linting yamls with yamllint 🏷

test/e2e-common.sh, test/e2e-tests.sh
This will add create install pipeline CRD
function which can accept release yaml or
install latest
review them:
=> Refactor e2e test

test/e2e-common.sh, test/e2e-tests.sh
- Move test functiosn to e2e-common
- Remove old serviceaccount things
- Allow override functions (or add) like the way we do with plumbing functions (for downstream CIs)
review them:
=> Refactor the test functions

.github/pull_request_template.md
=> Add info about yaml validation in github/pull_req_template

s2i/s2i.yaml, s2i/tests/resources.yaml, s2i/tests/run.yaml, test/e2e-tests.sh
Run the python s2i example from the official sclorgs image instead of the nodejs
one with my personal directory.
review them:
=> Fix S2I E2E Test

buildah/tests/pre-apply-task-hook.sh, jib-maven/tests/pre-apply-task-hook.sh, kaniko/tests/pre-apply-task-hook.sh, s2i/tests/pre-apply-task-hook.sh, test/e2e-common.sh
This add a central function in e2e common for when we want to add a registry as
sidecar in tasks for the e2e tests
Fixes #145
=> [E2E] Add common function when we are adding a registry to tasks

terraform-cli/Dockerfile, terraform-cli/OWNERS, terraform-cli/README.md, terraform-cli/terraform-cli-task.yaml
Creation of a task  to run terraform-cli commands
This is fairly complex task to setup, if someone can test this with azure or AWS would be great, I tested with OpenStack.
review them:
=> Add a task for terraform-cli command execution Closes #124

test/e2e-common.sh
We are currently looping forever without any safe counter, let's just do that,
Refactoring a bit so we reuse a common function for that,
Closes #156
=> Catalog tests should not be looping in case of failures

ansible-tower-cli/Dockerfile, ansible-tower-cli/OWNERS
Adding the OWNERS and the Dockerfile used to built the custom Image for the ansible-tower-cli task
review them:
=> Adding the OWNERS and the Dockerfile of ansible-tower-cli's custom image

maven/README.md, maven/maven.yaml, maven/tests/resources.yaml, maven/tests/run.yaml
Add `maven` Task manifest
Add PipelineResource and TaskRun for testing
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
review them:
=> Add MAVEN Task to catalog

golang/README.md, golang/build.yaml, golang/tests.yaml
This will track with new Go releases, while still letting users pin to a specific version if they want to.
review them:
=> Default go versions to latest

azure-cli/OWNERS
Adding an `OWNERS` file with myself as an approver/reviewer to follow up on [this comment](https://github.com/tektoncd/catalog/pull/150#issuecomment-568266253) in #150.
review them:
=> Adding OWNERS File for azure-cli

buildah/README.md, buildah/buildah.yaml
Add CONTEXT param to buildah task.  Addresses issue #170.
review them:
- [ x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x ] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
=> Add CONTEXT param to buildah task.

github/README.md, github/close_issue.yaml
Following other GitHub task adding close issue task.
review them:
=> Add Github close issue/pr task

kn/knative-dockerfile-deploy/README.md
- Update README and align the numbered list
review them:
=> Update README and align the numbered list

buildpacks/README.md, buildpacks/buildpacks-v3.yaml
- Also update buildpacks README to have more easily consumable example
Signed-off-by: Natalie Arellano <narellano@vmware.com>
* Update CNB task to conform to Platform API 0.2
* The latest lifecycle (v0.6.0) implements the new platform API
* Also update buildpacks README to have more easily consumable example
* This is to address the concern raised in https://github.com/tektoncd/catalog/issues/151
review them:
=> Update CNB task to conform to Platform API 0.2

slackmessage/OWNERS, slackmessage/README.md, slackmessage/send-to-channel-slack.yaml, slackmessage/send-to-webhook-slack.yaml
Adding new simple tasks that post a message to the slack channel
There are 2 tasks that both post a message to the slack channel.  One uses the Incoming Webhook of the slack and the other uses chat.postMessage slack api.
review them:
-  [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Send slack message tasks

mail/OWNERS, mail/README.md, mail/sendmail.yaml
Add a task that sends an email via SMTP server
review them:
=> Send email via SMTP server task

slackmessage/send-to-webhook-slack.yaml
Fix syntax error of the CURL command in send-to-webhook task.
review them:
- [x ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
=> fix syntax error in the webhook task

git/README.md
Re-reading the docs for the `git-clone` Task I didn't feel like it was particularly clear what the user is required to provide.
I've added a short explanation paragraph and an ordered list at the top of the `Task`'s description of the required inputs.
I also did a few other sneaky edits to try and help the overall flow of reading.
review them:
=> Clarify requirements of git-clone Task

golang/build.yaml, golang/lint.yaml, golang/tests.yaml
It simplifies the task spec.
/cc @chmouel @sbwsg 
review them:
=> Use script for golang tasks 🦍

conftest/conftest.yaml, conftest/helm-conftest.yaml, golang/build.yaml, golang/lint.yaml, golang/tests.yaml, kaniko/kaniko.yaml, kubeval/kubeval.yaml, makisu/makisu.yaml, maven/README.md, maven/maven.yaml, s2i/s2i.yaml
Just use the correct camelcase field.
Closes #148
/cc @chmouel @nikhil-thomas 
review them:
=> Use workingDir instead of workingdir 🐺

ansible-tower-cli/README.md, argocd/README.md, azure-cli/README.md, buildah/README.md, buildkit-daemonless/README.md, buildkit/README.md, buildpacks/README.md, conftest/README.md, gcloud/README.md, git/README.md, github/README.md, gke-deploy/README.md, golang/README.md, jib-gradle/README.md, jib-maven/README.md, kaniko/README.md, kn/README.md, knctl/README.md, kubeval/README.md, mail/README.md, makisu/README.md, maven/README.md, openshift-client/README.md, s2i/README.md, slackmessage/README.md, terraform-cli/README.md, tkn/README.md
- Port `gcloud` (for some reason I missed it…)
- Update READMEs to reflect the fact that `Params` are not under `Inputs` anymore
/cc @afrittoli @chmouel @sbwsg 
review them:
=> Bump gcloud and update READMEs

pullrequest/OWNERS, pullrequest/README.md, pullrequest/pr-example/README.md, pullrequest/pr-example/base.json, pullrequest/pr-example/comments/505233618.json, pullrequest/pr-example/comments/505476017.json, pullrequest/pr-example/comments/505482755.json, pullrequest/pr-example/comments/505529049.json, pullrequest/pr-example/comments/505616303.json, pullrequest/pr-example/comments/505676294.json, pullrequest/pr-example/comments/505798994.json, pullrequest/pr-example/comments/505890656.json, pullrequest/pr-example/comments/505923534.json, pullrequest/pr-example/comments/506032472.json, pullrequest/pr-example/comments/506082430.json, pullrequest/pr-example/comments/506082465.json, pullrequest/pr-example/comments/507732301.json, pullrequest/pr-example/comments/507763725.json, pullrequest/pr-example/comments/508007084.json, pullrequest/pr-example/head.json, pullrequest/pr-example/pr.json, pullrequest/pr-example/status/cla%2Fgoogle.json, pullrequest/pr-example/status/pull-tekton-pipeline-build-tests.json, pullrequest/pr-example/status/pull-tekton-pipeline-go-coverage.json, pullrequest/pr-example/status/pull-tekton-pipeline-integration-tests.json, pullrequest/pr-example/status/pull-tekton-pipeline-unit-tests.json, pullrequest/pr-example/status/tide.json, pullrequest/pr.yaml, pullrequest/sample/add-comment.yaml, pullrequest/sample/static.yaml
_Merging into v1beta1-wip branch @vdemeester !_
With the addition of workspaces and results, we are exploring a world
without PipelineResources! (see
https://github.com/tektoncd/pipeline/issues/1673)
To that end, this commit adds a Task that does the same things as the
PullRequest PipelineResource. It still uses the same underlying image,
pullrequest-init, which is currently built and published as part of the
Tekton Pipelines release, but which one day may be in another repo and
published separately.
This also includes a "sample" which uses the Task to post a comment on
an existing known PR - the only requirement to run it is a secret that
contains a github token.
Part of #95 
review them:
_See [the …
=> Add Task equivalent of PullRequest PipelineResource ⚗️

buildah/README.md, buildah/buildah.yaml
Add --format option to buildah task, closes #221 
review them:
=> Add --format option to buildah task

git/git-clone.yaml
=> the removed line fails if a checkout hasn't yet happened

maven/README.md, maven/maven.yaml
It simplifies the task spec. Also added proxies in settings.xml
#158 
review them:
=> Add Proxies and use Script for maven tasks

kaniko/kaniko.yaml
The version can be pinned by using the `BUILDER_IMAGE` parameter.
Closes #226 
/cc @mattmoor @bobcatfish
review them:
=> Use latest for kaniko task 😅

golang/README.md, golang/build.yaml, golang/lint.yaml, golang/test/pre-apply-task-hook.sh, golang/test/resources.yaml, golang/test/run.yaml, golang/tests.yaml
1. Update README.md file
2. Add pipeline and pipeline run 
review them:
=> Add pipeline and pipelinerun for golang

kn/knative-dockerfile-deploy/README.md, kn/knative-dockerfile-deploy/build_deploy/README.md, kn/knative-dockerfile-deploy/build_deploy/pipeline_run.yaml, kn/knative-dockerfile-deploy/build_deploy/resources.yaml
1. Added git-clone task creation instruction to README.md
2. Added PVC for workspace mount
3. Modified PipelineRun
review them:
=> Update kn task for workspace to deploy successfully

README.md
Pointing to `v1beta1` branch as the "default" one and the "current" one.
/cc @sbwsg 
review them:
=> Update README on master 😌

README.md
Preparing `v1beta1` to be the default branch
review them:
=> Update README.md to point to master/v1alpha1 📖

maven/README.md
fix markdown list
review them:
=> fix markdown list

README.md, roadmap.md
Adding the roadmap from https://github.com/tektoncd/catalog/pull/236/ into the default v1beta1 branch as well.
review them:
=> Add 2020 roadmap 🛣️

maven/README.md, maven/maven.yaml, maven/tests/run.yaml
Updated the README.md and added proxies as a part of custom params. Also fixed the mounting of settings.xml via ConfigMap.
Ref: #158
review them:
=> Improve Maven Task in v1beta1

gcs/README.md, gcs/gcs-download.yaml
"path" is a more descriptive name for this param since it is the path to
the data - also this is what upload was already using :D
review them:
=> Use "path" instead of "name" 👣

pullrequest/pr.yaml
I think I added this workspace while I was making the Task work, not
sure how this finally got committed! Wasn't the version I was testing
against obviously :sweat-smile: - looking forward to actually using the
samples/tests!
review them:
=> Remove unnecessary auth workspace 💼

test/presubmit-tests.sh
yamllint fails often on the current CI image. While we are working on
fixing it, let's disable yamllint temporarly.
/cc @sbwsg 
review them:
=> Temporarly disable yamllint 😓

buildah/README.md, buildah/buildah.yaml, git/README.md, git/git-clone.yaml, github/README.md, github/add_comment.yaml, github/close_issue.yaml, github/set_status.yaml, jib-gradle/jib-gradle.yaml, openshift-client/openshift-client-task.yaml, test/presubmit-tests.sh
Some pullrequest were merged in master while we were working on `v1beta1`. This cherry-pick those that could :angel: 
/cc @sbwsg @chmouel 
It'll need a manual `cla` check :stuck_out_tongue_closed_eyes: 
review them:
=> Cherry-pick some fixes from master

knctl/README.md, knctl/knctl-deploy.yaml
=> Correct knctl sample

git/tests/run.yaml, test/e2e-common.sh
This is following discussion on https://github.com/tektoncd/catalog/pull/277#issuecomment-614053647, adding tests for git-clone task
Since we have multiple taskrun tests and that wasn't supported before I am adding the support for it in test-runner.
review them:
=> Add git clone task tests

slackmessage/README.md, slackmessage/send-to-channel-slack.yaml, slackmessage/send-to-webhook-slack.yaml
Fix some small typo's.
review them:
=> Fix some typos in slack message

kaniko/kaniko.yaml
Because well, it's better to not use a `rc` image :stuck_out_tongue: 
/cc @sbwsg @chmouel 
review them:
=> Bump imagedigestexporter to v0.11.1

skopeo/README.md, skopeo/example/docker-secret.yaml, skopeo/example/quay-secret.yaml, skopeo/example/run.yaml, skopeo/example/serviceaccount.yaml, skopeo/skopeo.yaml, skopeo/test/pre-apply-task-hook.sh, skopeo/test/run.yaml
This is a part of documenting and providing `Skopeo` task, which can mirror a given set of images from a specified container image registry to another container image registry.
authors: @divyansh42 , @vinamra28 
review them:
=> Add Skopeo task

recommendations.md
Related https://github.com/tektoncd/catalog/issues/281 (though not addressed in this PR)
/assign @sbwsg 
/assign @vdemeester 
review them:
=> Begin to collect Task authoring recommendations

kythe/README.md, kythe/kythe-go.yaml, kythe/tests/run.yaml
This task allows you to generate Kythe annotation metadata for a given
Go project. This follows the workspace model as presented by the `git`
Task. The expectation is that any results place in the workspace will be
exported by another Task in the pipeline for remote storage (e.g. GCS).
review them:
=> Add Kythe golang extractor task.

telegrammessage/README.md, telegrammessage/send-to-telegram.yaml
A task for sending messages towards telegram as an alternative to slack.
review them:
- [?] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
=> Add telegram example

buildah/buildah.yaml
=> Update buildah to 1.14.8

git/README.md, git/git-clone.yaml
Adding httpsProxy, httpProxy, and noProxy in git-clone task.
review them:
=> adding proxy settings to git-clone

kaniko/kaniko.yaml
I copied this Task (can't wait for OCI registry referencing! :D)
into Pipelines for an example in https://github.com/tektoncd/pipeline/pull/2482
and @ImJasonH asked me to add a comment, so I used
https://github.com/tektoncd/catalog/commit/0a8b65343b0c8f7409366141c741ec6296764cd9
to figure out why this was added and now I'm adding the comment
here as well!
review them:
=> Add comment about security context 🔒

github/create-github-release/README.md, github/create-github-release/create-github-release.yaml, github/create-github-release/example/run.yaml, github/create-github-release/example/secret.yaml
This task can be used to make a release in the Github.
Multiple `assets` including `binaries` of the released version and the `release notes`, can also be uploaded with the release.
review them:
=> Add Github Release task

gitlab/README.md, gitlab/issue-add-labels.yaml
This `task` can be used to add labels to the Gitlab issue.
review them:
=> Add task to add labels in Gitlab issue

README.md
=> README: update the notice on v1alpha1 👼

maven/maven.yaml
The Maven mirror url param has an incorrect reference which is fixed now. 
review them:
=> Fixed Maven mirror url param description

ansible-tower-cli/README.md, argocd/README.md, azure-cli/README.md, buildah/README.md, buildkit-daemonless/README.md, buildpacks/README.md, conftest/README.md, gcloud/README.md, github/README.md, gke-deploy/README.md, golang/README.md, jib-gradle/README.md, jib-maven/README.md, kaniko/README.md, kn/README.md, knctl/README.md, kubeval/README.md, mail/README.md, makisu/README.md, openshift-client/README.md, openshift-provision/README.md, s2i/README.md, slackmessage/README.md, telegrammessage/README.md, terraform-cli/README.md, tkn/README.md
PR to improve the Readme.md migrating the install task URL from
master to v1beta1
Signed-off-by: ishani2412 <ishani.1613039@kiet.edu>
review them:
=> Improve Readme.md

ibmcloud-cli/OWNERS, ibmcloud-cli/README.md, ibmcloud-cli/ibmcloud-cli.yaml
- Initial Release inspired by `az` for the IBM Cloud CLI in the catalog
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
review them:
=> IBM Cloud CLI Task for tekton

sonarqube/README.md, sonarqube/examples/pvc.yaml, sonarqube/examples/run.yaml, sonarqube/examples/sonar-project.properties, sonarqube/sonarqube.yaml
The following task can be used to do static analysis of the source code by taking SonarQube server URL as the input.
review them:
=> Add SonarQube Task to catalog

aws-cli/README.md, aws-cli/aws-cli.yaml, aws-cli/example/run.yaml, aws-cli/example/secret.yaml
This task performs operations on Amazon Web Services resources using `aws`.
Authors: @vinamra28 @divyansh42
review them:
=> Add aws-cli task

github/add-labels/README.md, github/add-labels/add-labels.yaml, github/add-labels/example/run.yaml, github/add-labels/example/secret.yaml
This task can be used to add labels to a Github `pull request` or an `issue`.
review them:
=> Add task to label Github pull request or an issue

gitlab/create-gitlab-release/README.md, gitlab/create-gitlab-release/create-gitlab-release.yaml, gitlab/create-gitlab-release/example/run.yaml, gitlab/create-gitlab-release/example/secret.yaml
This task can be used to make a `release` on the `Gitlab`.
`Assets` or `binaries` of the released version can also be uploaded with the release.
review them:
=> Add Gitlab Release task

buildpacks/README.md, buildpacks/buildpacks-v3.yaml, buildpacks/tests/run.yaml
(re-opening to hopefully satisfy the CLA)
Add support in buildpacks task for platform envs
This change makes it possible for users to provide
environment variables to buildpacks via a volume with
appropriately configured directories.
Also updates to platform API 0.3 (previously, only the master branch was updated).
See https://buildpacks.io/docs/reference/buildpack-api/
for more info on how PLATFORM_DIR is used.
Resolves #160
review them:
=> Support v1beta1 platform envs

ibmcloud-cli/OWNERS
Added me as a reviewer and approver to the task resource i created.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
review them:
=> I'm an owner now!

curl/README.md, curl/curl.yaml, curl/tests/run.yaml
=> create curl task to request response from internet

maven/tests/run.yaml
Since the "master" branch has been renamed to "main", let's make sure we pin to
a revision and fix if there is other rename going on.
review them:
=> Pin maven repo test to a revision

prettier/README.md, prettier/prettier.yaml, prettier/tests/pre-apply-task-hook.sh, prettier/tests/resources.yaml, prettier/tests/run.yaml
Create a new Prettier task to check codes from a git repo (need to use the git-clone task to fetch codes).
review them:
=> Create a new Prettier task version 1

test/e2e-tests.sh
Eventually we want to be able to have Tasks declare what versions they
are compatible with and test against those
(https://github.com/tektoncd/catalog/issues/373) but in the meantime, it
seems reasonable to bump the version every time we do a release (and
even once we have #373, we would want to be running tests against new
versions as well - and this could have the benefit of giving us
information about issues in a release early, before users notice them!)
review them:
- [n/x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules. …
=> Update automation to test against 0.13.2

buildid/OWNERS, buildid/README.md, buildid/examples/build-service-api.yaml, buildid/examples/pipeline.yaml, buildid/examples/taskrun.yaml, buildid/task.yaml, buildid/tests/run.yaml
Task for generating unique build id
Closes #368 
review them:
=> Task for generating unique build id

git/git-batch-merge.yaml, git/git-clone.yaml
The PR include changes to bump git-init image to 0.13.2 which is latest
review them:
=> Bump git-init image to 0.13.2

git/README.md, git/examples/git-rebase/run.yaml, git/examples/git-rebase/secret.yaml, git/examples/git-rebase/service-account.yaml, git/git-rebase.yaml
This task will `Rebase` the  git branch based on the user input. `Squashing` of commits before rebase can also be done, if required. 
review them:
=> Add Git Rebase task

.github/ISSUE_TEMPLATE/config.yml, aws-cli/aws-cli.yaml, aws-cli/example/secret.yaml, buildid/examples/build-service-api.yaml, buildid/examples/pipeline.yaml, curl/curl.yaml, curl/tests/run.yaml, gcs/gcs-generic.yaml, git/examples/git-clone-checking-out-a-branch.yaml, git/examples/git-clone-checking-out-a-commit.yaml, git/examples/using-git-clone-result.yaml, github/add-labels/add-labels.yaml, github/add-labels/example/run.yaml, github/create-github-release/example/run.yaml, gitlab/add-labels.yaml, gitlab/create-gitlab-release/create-gitlab-release.yaml, kubectl/clusterrole.yaml, kubectl/kubectl-deploy.yaml, kubectl/taskrun.yaml, maven/maven.yaml, openshift-provision/openshift-cluster-create.yaml, prettier/tests/run.yaml, replace-tokens/tests/run.yaml, skopeo/skopeo.yaml, telegrammessage/send-to-telegram.yaml, test/presubmit-tests.sh, wget/tests/run.yaml, wget/wget.yaml
=> Fix yaml lint errors and warnings

cloudevent/README.md, cloudevent/config/task.yaml, cloudevent/tests/event-display.yaml, cloudevent/tests/run.yaml
This is a small task that uses the knative eventing [`sendevent`](https://github.com/knative/eventing/tree/master/cmd/sendevent) cmd to send an event to a sink.
review them:
=> Add Cloudevent Task

git/README.md, git/examples/git-cli/pipeline.yaml, git/examples/git-cli/pvc.yaml, git/examples/git-cli/secret.yaml, git/examples/git-cli/service-account.yaml, git/git-cli.yaml, git/tests/run.yaml
Added `Git CLI` task, this task can be used to run `git commands`.
Git command need to be passed as a `script` to the task
review them:
=> Add Git CLI task

.github/pull_request_template.md
Add checks to PR template to  validate that the PRs comply with the TEP: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
review them:
- [🙅 ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [🙅 ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Add manual validation checks to comply with Catalog Org TEP

task/aws-cli/0.1/README.md, task/build-push-gke-deploy/0.1/README.md, task/create-github-release/0.1/README.md, task/create-gitlab-release/0.1/README.md, task/generate-build-id/0.1/README.md, task/git-cli/0.1/README.md, task/git-clone/0.1/README.md, task/git-rebase/0.1/README.md, task/github-add-labels/0.1/README.md, task/gke-deploy/0.1/README.md, task/kubeconfig-creator/0.1/README.md, task/pull-request/0.1/README.md, task/skopeo-copy/0.1/README.md, task/sonarqube-scanner/0.1/README.md
review them:
```
spec:
```
---
=> Modifies the path in readme for samples directory

task/git-batch-merge/0.1/git-batch-merge.yaml, task/git-clone/0.1/git-clone.yaml, task/kaniko/0.1/kaniko.yaml, task/kubeconfig-creator/0.1/kubeconfig-creator.yaml, task/pull-request/0.1/pull-request.yaml, test/e2e-tests.sh
- Update the pipeline to install for e2e tests
- Update images to refer to 0.14.0 version of pipeline
review them:
=> Bump pipeline release to 0.14.0

test/e2e-common.sh
This will refactor sidecar script to read it in
a better way to avoid unicode error
review them:
```
spec:
```
---
=> Refactor sidecar script

task/aws-ecr-login/0.1/README.md, task/aws-ecr-login/0.1/aws-ecr-login.yaml, task/aws-ecr-login/0.1/samples/run.yaml, task/aws-ecr-login/0.1/samples/secret.yaml, task/aws-ecr-login/0.1/samples/test-task.yaml
This task will be used to authenticate to `Amazon ECR registry`. 
Task will give the `authentication token` in form of `results` 
of the task and this token can be used for authentication. 
Tests cannot be provided for this Task, as AWS credentials 
are required to generate login token in order to login into Amazon ECR.
review them:
=> Add AWS ECR Login task

task/kubectl-deploy-pod/0.1/kubectl-deploy-pod.yaml
review them:
```
spec:
```
---
=> Spell Error kubectl-deploy-pod.yaml

task/skopeo-copy/0.1/README.md
After https://github.com/tektoncd/catalog/pull/425 we have changed the image,
so we are not using the Dockerfile present [here](https://github.com/tektoncd/plumbing/tree/master/tekton/images/skopeo) anymore.
review them:
```
spec:
```
---
[validation]: …
=> Fix README.md of skopeo task

task/gke-cluster-create/0.1/README.md
I removed this from the Task name but forgot to update the README!
review them:
- [n/a] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
---
=> Remove "end to end" from cluster creation Task

task/pylint/0.1/pylint.yaml
* Only intall the requirements when the file is here
(sometime we write pure python script that doesn't need external libs)
* fix installing pylint when needed
review them:
```
spec:
```
=> Fixes for pylint tasks

task/ansible-runner/0.1/README.md, task/ansible-runner/0.1/ansible-runner.yaml, task/ansible-runner/0.1/support/ansible-deployer.yaml, task/ansible-runner/0.1/support/playbooks-pvc.yaml, task/ansible-runner/0.1/tests/pre-apply-task-hook.sh, task/ansible-runner/0.1/tests/resources.yaml, task/ansible-runner/0.1/tests/run.yaml
Signed-off-by: Kamesh Sampath <ksampath@redhat.com>
A new Task to run Ansible Playbook, that can help performing Kubernetes cluster interaction.  Resolves #463 
review them:
- [* ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ *] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [*] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
- [* ] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [*] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
- [*] Has mandatory …
=> Add Ansible Runner Task

task/git-batch-merge/0.2/git-batch-merge.yaml, task/git-clone/0.1/git-clone.yaml, task/kaniko/0.1/kaniko.yaml, task/kubeconfig-creator/0.1/kubeconfig-creator.yaml, task/pull-request/0.1/pull-request.yaml, test/e2e-tests.sh
review them:
```
spec:
```
---
=> Bump images to 0.15.2

test/e2e-common.sh
CI was not able to monitor some pipelineruns for tasks in catalog example maven task and was getting "Could not find a created taskrun or pipelinerun in maven-0-1+ breakit=True" which is not the expected behaviour so with this patch we will iterate over it 5 times and check for it's status and reason
Logs of the current CI for the maven task. There are various other tasks as well for which CI is not running the tests
```
+ for runtest in ${@}
+ local runtestdir=maven/0.1/tests
+ local testname=maven
++++ dirname task/maven/0.1/tests
+++ basename task/maven/0.1
++ basename 0.1
+ local version=0.1
+ [[ 0.1 =~ ^[0-9]+\.[0-9]+$ ]]
++ echo 0.1
++ tr . -
+ version=0-1
+ local tns=maven-0-1
+ local skipit=
+ local maxloop=60
+ local taskdir=task/maven/0.1
+ ls task/maven/0.1/maven.yaml
+ [[ -n …
```
=> Fix CI issues

task/send-to-webex-room/0.1/README.md, task/send-to-webex-room/0.1/send-to-webex-room.yaml
This adds a task to send text message to Webex room
Adds Task to send text messages to a Webex room.
```
spec:
```
=> feat: send to Webex

task/buildpacks-phases/0.1/README.md, task/buildpacks/0.1/README.md
[#173928543]
Update paketo builders location to dockerhub
review them:
- [x ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x ] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
- [x ] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [x ] File path follows  `<kind>/<name>/<version>/name.yaml`
- [x ] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [x ] Has mandatory …
=> Update paketo builders location to dockerhub

test/e2e-common.sh
previous link https://storage.googleapis.com/tekton-releases/latest/release.yaml would install 0.10.0
cc @popcor255 @danielhelfand
=> Use the proper path for the last release.yaml

.github/pull_request_template.md
Just fixing a typo! originally in https://github.com/tektoncd/catalog/pull/472
review them:
- [n/a] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
---
=> Fix a typo

README.md
review them:
```
spec:
```
---
=> Adds Hub preview link in the readme

task/git-clone/0.2/README.md, task/git-clone/0.2/git-clone.yaml
This matches the behavior in PipelineResources after https://github.com/tektoncd/pipeline/pull/2975
review them:
```
spec:
```
---
=> Add a URL result to the Git clone task.

task/git-batch-merge/0.2/git-batch-merge.yaml, task/git-clone/0.2/git-clone.yaml, task/kaniko/0.1/kaniko.yaml, task/kubeconfig-creator/0.1/kubeconfig-creator.yaml, task/pull-request/0.1/pull-request.yaml, test/e2e-tests.sh
review them:
```
spec:
```
---
=> Bump images to 0.16.2

task/aws-ecr-login/0.1/samples/test-task.yaml, task/buildah/0.1/README.md, task/buildah/0.1/buildah.yaml, task/s2i/0.1/s2i.yaml
Buildah image in few tasks was not pointing to latest
image release tag, so updated the image to point to
latest release.
review them:
```
spec:
```
---
=> Bump buildah image

task/git-cli/0.1/README.md
review them:
```
spec:
```
---
=> Fixed typo

task/github-set-status/0.1/README.md
Fixed invalid URL to the Tekton Dashboard
review them:
```
spec:
```
---
=> Fix invalid URL to Tekton Dashboard

task/github-set-status/0.1/README.md, task/github-set-status/0.1/github-set-status.yaml
Improve the documentation for the GitHub status task, fix
spelling issues and add link to the GitHub API implemented.
review them:
```
spec:
```
---
=> Fix documentation for the GitHub status task

task/github-app-token/0.1/Dockerfile, task/github-app-token/0.1/README.md, task/github-app-token/0.1/github-app-token.yaml, task/github-app-token/0.1/samples/run.yaml, task/github-app-token/0.1/samples/secret.yaml
This add the github app token, this would help to get a user token from a github
app which can be perused to do github operations.
Flow for github apps to work on tekton can usually going like this :
* github events
-> triggers event listenner 
-> start a pipeline
->  -> get user token from app (with this task)
->  -> do operation (like ci checks or others) on github with perusing
the token from the previous task
review them:
- [ X Has `README.md` at `<kind>/<name>/<version>/README.md`
```
spec:
```
---
[TEP]: …
=> Add Github APP token task

task/black/0.1/README.md, task/black/0.1/black.yaml, task/black/0.1/tests/pre-apply-task-hook.sh, task/black/0.1/tests/resources.yaml, task/black/0.1/tests/run.yaml
This task will be used to format python code after doing a lint check and will not complain for the errors.
review them:
```
spec:
```
---
=> Add task to include Black(Python Prettier)

task/goreleaser/0.1/README.md, task/goreleaser/0.1/goreleaser.yaml, task/goreleaser/0.1/samples/run.yaml
This task can be used to builds Go binaries for several platforms,
creates a GitHub release and then pushes a Homebrew formula to a tap
repository using [goreleaser](https://github.com/goreleaser/goreleaser).
closes https://github.com/tektoncd/cli/issues/1170
review them:
```
spec:
```
--- …
=> Add GoReleaser task to Catalog

task/mypy-lint/0.1/README.md, task/mypy-lint/0.1/mypy-lint.yaml, task/mypy-lint/0.1/tests/pre-apply-task-hook.sh, task/mypy-lint/0.1/tests/resources.yaml, task/mypy-lint/0.1/tests/run.yaml
The following task contains `mypy` linter which is a popular static code analyser for python that checks code as described http://mypy-lang.org/
closes #527 
review them:
```
spec:
```
---
=> Add Mypy Linter for Python

task/kubeconfig-creator/0.1/tests/run.yaml
Add a test for the kubeconfig-creator task
=> Add a test for the kubeconfig-creator task

task/git-batch-merge/0.2/git-batch-merge.yaml, task/git-clone/0.2/git-clone.yaml, test/e2e-tests.sh
Signed-off-by: divyansh42 <diagrawa@redhat.com>
review them:
```
spec:
```
---
=> Bump images to 0.17.1

.github/pull_request_template.md
To manually validate whether the PR includes tests for the task which is modified or added
review them:
```
spec:
```
---
=> Add manual validation check for including tests

task/tkn/0.2/tests/resources.yaml, task/tkn/0.2/tests/run.yaml
Add test for `tkn` task which will use the current cluster's `kubeconfig` and `list/describe` the task in current namespace.
With ref to https://github.com/tektoncd/catalog/pull/499#issuecomment-714323245. I have added tests for the tkn task
/cc @chmouel @sbwsg @vdemeester 
review them:
```
spec:
```
---
[example]: …
=> Add tests for tkn Task

task/buildah/0.2/README.md
=> Fix buildah sample optional workspace link

task/blue-green-deploy/0.1/samples/v1-deploy/blue-deployment.yaml, task/blue-green-deploy/0.1/samples/v1-deploy/service.yaml, task/blue-green-deploy/0.1/samples/v2-deploy/green-deployment.yaml, task/blue-green-deploy/0.1/tests/pre-apply-task-hook.sh, task/blue-green-deploy/0.1/tests/resources.yaml, task/blue-green-deploy/0.1/tests/run.yaml
Adding tests for blue green deployment task. The test will first
deploy version v1 of an application and service pointing to version
that deployment using `pre-apply-task-hook.sh` script and using taskrun will
deploy version v2 of that application and patch the service to point to v2 version
of the application
Also modified the images in deployment manifests present in samples as the previous image
is not accessible now
review them:
```
spec:
```
---
[TEP]: …
=> Add tests for Blue Green Deployment Task

task/buildpacks/0.2/README.md, task/buildpacks/0.2/buildpacks.yaml, task/buildpacks/0.2/tests/pre-apply-task-hook.sh, task/buildpacks/0.2/tests/resources.yaml, task/buildpacks/0.2/tests/run.yaml
This is an update of https://github.com/tektoncd/catalog/pull/276
cc @ekcasey 
review them:
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [y] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [y] File path follows  `<kind>/<name>/<version>/name.yaml`
- [y] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [y] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the …
=> Update buildpack task to drop privilege

task/codecov/0.1/README.md, task/codecov/0.1/codecov.yaml, task/codecov/0.1/samples/codecov.sample.yaml, task/codecov/0.1/tests/pre-apply-task-hook.sh, task/codecov/0.1/tests/run.yaml
This task allows uploading a code coverage report to  [codecov.io](https://codecov.io)
Closes #533
review them:
```
spec:
```
---
=> Add codecov task

task/github-add-comment/0.2/README.md, task/github-add-comment/0.2/github-add-comment.yaml, task/github-add-comment/0.2/tests/fixtures/github-post-comment.yaml, task/github-add-comment/0.2/tests/pre-apply-task-hook.sh, task/github-add-comment/0.2/tests/run.yaml, task/github-close-issue/0.2/README.md, task/github-close-issue/0.2/github-close-issue.yaml
Rather than forcing task users to create a secret with a fixed
name, allow setting the secret name and key as parameter.
The new parameters are optional, in the sense that they default
to the previous hardcoded values.
Fixes : https://github.com/tektoncd/catalog/issues/555
review them:
```
spec:
```
---
[validation]: …
=> Modify GitHub tasks to add ability to specify secret name and key

CONTRIBUTING.md, task/docker-build/0.1/README.md
Closes #550 
Closes #549
Signed-off-by: ishani2412 <ishani.1613039@kiet.edu>
review them:
```
spec:
```
---
=> Fix broken link

task/helm-upgrade-from-source/0.2/README.md, task/helm-upgrade-from-source/0.2/helm-upgrade-from-source.yaml, task/helm-upgrade-from-source/0.2/samples/helm-upgrade-from-source-task-run.yaml.tmpl, task/helm-upgrade-from-source/0.2/tests/pre-apply-task-hook.sh, task/helm-upgrade-from-source/0.2/tests/resources.yaml, task/helm-upgrade-from-source/0.2/tests/run.yaml
Making it easier to overwrite multiple values,
Instead of defining them all in overwrite_values.
review them:
```
spec:
```
---
=> Add values_file to helm-upgrade-from-source

task/s2i/0.1/README.md
Fix broken link of builder image of python
Signed-off-by: divyansh42 <diagrawa@redhat.com>
review them:
```
spec:
```
---
=> Fix broken image link

test/e2e-common.sh, test/e2e-tests.sh
We were running previously the tests sequentially,
Since the catalogs tests are growing exponentially, let's add parallelisation to
speed things up (default: 5 tests)
Moreover we add another related patch to be able to redefine KUBECONFIG for downstream CIs.
/area testing
=> Add parallelisation of tests

task/scorecard/0.1/README.md, task/scorecard/0.1/scorecard.yaml, task/scorecard/OWNERS
This task is very simple right now, but will be extended to support
other flags and output formats int he future.
review them:
```
spec:
```
---
=> Add a catalog task to run the OpenSSF Security Scorecard project.

task/git-batch-merge/0.2/git-batch-merge.yaml, task/git-clone/0.2/git-clone.yaml, test/e2e-tests.sh
This update the pipeline version to latest => 0.18.1
All good 👍🏼
/kind cleanup
=> Bump tekton pipeline version to 0.18.1

test/e2e-tests.sh
Updated the Tekton Pipelines version to 0.19.0
review them:
```
spec:
```
---
=> Bump Tekton Pipeline version to 0.19.0

task/golang-build/0.1/tests/pre-apply-task-hook.sh, task/golang-test/0.1/tests/pre-apply-task-hook.sh
review them:
```
spec:
```
---
=> Remove unnecessary sidecar in golang test

task/blue-green-deploy/0.1/blue-green-deploy.yaml, task/istio-canary-release/0.1/istio-canary-release.yaml, task/kubeconfig-creator/0.1/README.md, task/kubeconfig-creator/0.1/samples/test-task.yaml, task/openshift-client-kubecfg/0.1/openshift-client-kubecfg.yaml, task/openshift-client-python/0.1/Dockerfile, task/openshift-client/0.1/openshift-client.yaml, task/openshift-install/0.1/README.md, task/openshift-install/0.1/openshift-install.yaml, task/openshift-uninstall/0.1/README.md, task/openshift-uninstall/0.1/openshift-uninstall.yaml
* Update all images to use the latest stable 4.6
* Modify the task using :latest to pin it to 4.6
review them:
```
spec:
```
---
=> Update all images using openshift to latest stable 4.6

CONTRIBUTING.md, test/e2e-common.sh
Add dependency checks to e2e test script.
This is a trivial change to hopefully make it easier for other get started with executing the e2e tests. It simply checks for commands and packages before getting too far in execution in hopes that it provides a more focused error.
review them:
```
spec:
```
---
[validation]: …
=> Add dependency checks to e2e test script

task/powershell/0.1/README.md, task/powershell/0.1/powershell.yaml, task/powershell/0.1/tests/run.yaml
review them:
```
spec:
```
---
=> Powershell task added

task/eks-cluster-create/0.1/README.md, task/eks-cluster-create/0.1/eks-cluster-create.yaml, task/eks-cluster-create/0.1/samples/create-eks-cluster.yaml, task/eks-cluster-create/0.1/samples/secret.yaml, task/eks-cluster-create/OWNERS, task/eks-cluster-teardown/0.1/README.md, task/eks-cluster-teardown/0.1/eks-cluster-teardown.yaml, task/eks-cluster-teardown/0.1/samples/secret.yaml, task/eks-cluster-teardown/0.1/samples/teardown-eks-cluster.yaml, task/eks-cluster-teardown/OWNERS
Adds `eks-cluster-create` and `eks-cluster-teardown` tasks with the `eksctl` tool using the official image of weaveworks.
review them:
```
spec:
```
---
=> Add EKS cluster create/teardown tasks

task/helm-upgrade-from-repo/0.1/tests/pre-apply-task-hook.sh, task/helm-upgrade-from-source/0.1/tests/pre-apply-task-hook.sh, task/helm-upgrade-from-source/0.2/tests/pre-apply-task-hook.sh
Upstream catalog nightly is failing with the error
`error: error parsing STDIN: error converting YAML to JSON: yaml: line
2: mapping values are not allowed in this context` which is occuring
while creating the SA in `pre-apply-task-hook.sh` as the SA YAML was
first created and then applied and during this process the error is
occuring.
The PR fixes that by directly creating the SA and not first generating
the YAML and then applying in next step.
Link to failing catalog nightly can be found [here](https://tekton-releases.appspot.com/build/tekton-prow/logs/periodic-tekton-catalog-integration-tests/1351365279543726080/)
/hold
review them:
```
spec:
one …
```
=> Fix creation of ServiceAccount in helm tasks

test/e2e-tests.sh
Bumping the Tekton Pipelines to the latest version in e2e tests.
review them:
```
spec:
```
---
=> Bump Tekton Pipelines to 0.20.0

test/e2e-common.sh
If a task is being removed from the catalog then also the CI runs the
check for validating the YAML and thus fails if the task manifest is not
found.
This PR checks for the task directory whether it exists or not and in the case
where task directory is not present then the function doesn't checks the
validation of the YAML. Example if we remove the task knctl-deploy then
the CI would skip the check for that pull request.
closes #619 
review them:
```
spec:
```
---
[TEP]: …
=> Skip the validation of YAML if task is being removed from catalog

recommendations.md
I added some recommendations after some months of working with Tekton Pipelines, as recommended by @ImJasonH in the Tekton slack.
review them:
(removed N/A checkboxes)
=> Proposed recommendations for authoring tasks

task/npm/0.1/README.md, task/npm/0.1/npm.yaml, task/npm/0.1/tests/pre-apply-task-hook.sh, task/npm/0.1/tests/run.yaml
This task can be used to run npm goals on a nodejs based project.
review them:
```
spec:
```
---
=> Add npm cli task

README.md
review them:
```
spec:
```
---
=> Updates readme by redirecting Hub preview to Hub

task/aws-ecr-login/0.1/samples/test-task.yaml, task/buildah/0.1/README.md, task/buildah/0.1/buildah.yaml, task/buildah/0.2/README.md, task/buildah/0.2/buildah.yaml, task/buildah/0.2/tests/pre-apply-task-hook.sh, task/s2i/0.1/s2i.yaml, task/s2i/0.2/s2i.yaml
Update buildah to latest stable version
review them:
```
spec:
```
---
=> 🧹 Update buildah to latest version 0.17.0

task/kubeconfig-creator/0.1/kubeconfig-creator.yaml, task/pull-request/0.1/pull-request.yaml
Latest image versions have multi-arch support, it will allow to use the same catalog tasks for many hardware architectures.
review them:
```
spec:
```
---
=> Bump pullrequest-init and kubeconfigwriter version to v0.20.1

OWNERS
Vinamra has been a very active contributor on the catalog project for
a while now.
He has been actively participating in reviews for more than 3 months,
is the **most active reviewer** on the catalog for a while now, has added and contributed
to several tasks, helped for the catalog reorganization and is
actively working on enhancing the current CI.
https://github.com/tektoncd/community/blob/master/process.md#requirements
/cc @ImJasonH @chmouel @bobcatfish @sbwsg 
review them:
```
spec:
``` …
=> Add vinamra28 as OWNER 🦩

task/jib-maven/0.2/README.md, task/jib-maven/0.2/jib-maven.yaml, task/jib-maven/0.2/tests/pre-apply-task-hook.sh, task/jib-maven/0.2/tests/resources.yaml, task/jib-maven/0.2/tests/run.yaml
- Add parameter for the maven image
- Replace usage of PipelineResource to image name as param and image digest as
results
review them:
```
spec:
```
---
=> Add version 0.2 to jib-maven task

task/helm-upgrade-from-repo/0.2/README.md
Fix version of the helm-upgrade-from-repo task in README
review them:
```
spec:
```
---
=> Minor fix in README for helm-upgrade-from-repo

test/e2e-tests.sh
Bumping the Tekton Pipelines to the latest version in e2e tests, as directed in [step 15 of Tekton Pipelines release guide](https://github.com/tektoncd/pipeline/blob/master/tekton/release-cheat-sheet.md)
Bumping the Tekton Pipelines to the latest version in e2e tests, as directed in [step 15 of Tekton Pipelines release guide](https://github.com/tektoncd/pipeline/blob/master/tekton/release-cheat-sheet.md)
review them:
--- …
=> Bump Tekton Pipelines to 0.21.0

task/jib-gradle/0.2/README.md, task/jib-gradle/0.2/jib-gradle.yaml, task/jib-gradle/0.2/tests/pre-apply-task-hook.sh, task/jib-gradle/0.2/tests/resources.yaml, task/jib-gradle/0.2/tests/run.yaml
Signed-off-by: rudeigerc <rudeigerc@gmail.com>
Closes #584 
Add version 0.2 to `jib-gradle` task.
review them:
```
spec:
```
---
=> Add version 0.2 to jib-gradle task

task/orka-deploy/0.1/tests/run.yaml, task/orka-teardown/0.1/tests/run.yaml
This PR corrects a potential race condition for the orka-deploy
and orka-teardown tests which causes the nightly integration test run to
fail. A runAfter condition is added to each test pipeline to avoid a
race condition where the pods created by the orka-deploy and
orka-teardown tasks are unable to be created when the orka-init task
has not yet created the secret and config map needed for pod config.
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-o …
=> Fix failing tests for orka tasks

recommendations.md
review them:
```
spec:
```
---
=> Fix typo in recommendations.md

task/kaniko/0.2/README.md, task/kaniko/0.2/kaniko.yaml, task/kaniko/0.2/tests/pre-apply-task-hook.sh, task/kaniko/0.2/tests/resources.yaml, task/kaniko/0.2/tests/run.yaml
Since 1.0.0 a lot of multi-arch improvements have been made, as well as
performance improvements and bug fixes
See full changelog: https://github.com/GoogleContainerTools/kaniko/blob/master/CHANGELOG.md
review them:
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [y] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been …
=> Update kaniko image v1.0.0 -> v1.5.1

test/e2e-tests.sh
Updating the RELEASE_YAML to bump the Tekton Pipelines to the latest version in e2e tests.
review them:
---
=> Bump Tekton Pipelines to 0.22.0

test/e2e-common.sh
python and pyyaml are currently required to inject an optional sidecar for a registry.
This PR uses sed to inject that sidecar and removes the need for python
Benefits include reducing attack surface and the requirement for 2 extra dependencies
Also I set `require_command` to check for the kubectl command
review them:
```
spec:
```
--- …
=> use sed to add sidecar and remove python

task/boskos-release/0.1/samples/pipelinerun.yaml, task/boskos-release/0.1/samples/service-account.yaml
This resolves #545 by repointing the dangling symlinks to the appropriate location. No change in functionality.
review them:
```
spec:
```
---
=> Fix broken symlink

task/terraform-cli/0.2/README.md, task/terraform-cli/0.2/terraform-cli.yaml
- Add parameter for the Terraform image
- Add proxy parameter
- Use official Hashicorp Terraform by default
- Better Terraform Environment Variable description
=> Add version 0.2 to terraform-cli task

task/git-batch-merge/0.2/tests/run.yaml
Updated refspec defaults because recently upstream branch changed from `master` to `main` (`refs/heads/master:refs/heads/master`->`refs/heads/main:refs/heads/main`)
review them:
```
spec:
```
---
=> Add  `refspec` param  to run.yaml 

task/buildpacks/0.3/README.md, task/buildpacks/0.3/buildpacks.yaml, task/buildpacks/0.3/samples/env-vars.yaml, task/buildpacks/0.3/samples/results.yaml, task/buildpacks/0.3/tests/pre-apply-task-hook.sh, task/buildpacks/0.3/tests/resources.yaml, task/buildpacks/0.3/tests/run.yaml
- Add `APP_IMAGE_DIGEST` result
- Upgrade to Platform API 0.4
- Add support for build-time environment variables
- Replace use of PipelineResources with Params
review them:
```
spec:
```
---
=> Add task/buildpacks/0.3

task/sendmail/0.1/sendmail.yaml
Non-ascii characters would cause the task to fail to send the email because by default smtplib tries to encode the message in ascii. 
Adding the encode('utf-8') to the email body fixes the issue.
Non-ascii characters would cause the task to fail to send the email because by default smtplib tries to encode the message in ascii. 
Adding the encode('utf-8') to the email body fixes the issue.
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.m …
=> Fixed message encoding to support non-ascii chars in Sendmail task

task/kn/0.1/README.md
Fixes the broken link to kn-deployer.yaml.
review them:
```
spec:
```
---
=> Fix kn-deployer.yaml path.

test/e2e-tests.sh
Pipelines just released v0.23.0.
This commit updates the e2e test runner to use the new version
of Pipelines when testing catalog entries.
review them:
=> Update catalog e2e test runner to use Pipelines version 0.23.0

task/git-clone/0.3/samples/git-clone-checkout-out-a-pr.yaml
Add a sample to demonstrate how to checkout a PR directly with git-clone.
Closes #694
/cc @sbwsg 
review them:
=> Add pr checkout sample for git-clone task

task/jib-maven/0.3/jib-maven.yaml
Added `securityContext` in order to run jib-maven in privileged mode.
review them:
```
spec:
```
---
/cc @vinamra28 @chmouel @piyush-garg
=> Add privileged permission to jib-maven task

task/jib-maven/0.3/jib-maven.yaml
This reverts commit 1920b1e36c136371f675ee95c568b2eec78327b6.
review them:
```
spec:
```
---
=> Revert "Add privileged permission to jib-maven task"

task/tkn/0.2/tkn.yaml
review them:
```
spec:
```
---
=> Bump tkn image to 0.18

task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
When the optional dockerconfig workspace is set, set the
DOCKER_CONFIG env variable accordingly.
review them:
```
spec:
```
---
=> [tekton-catalog-publish] Bind the dockerconfig workspace

task/cloudevent/0.1/cloudevent.yaml, task/cloudevent/0.1/config/task.yaml
Removing the inputs param prefix according to the v1beta1 specs. 
Fixing the #721 issue.
review them:
```
spec:
```
---
=> Removing the inputs param prefix according to the v1beta1 specs

task/golangci-lint/0.1/golangci-lint.yaml, task/golangci-lint/0.1/tests/run.yaml
review them:
```
spec:
```
---
=> Update golangci-lint to latest

README.md
Tasks are now published nightly to bundles.
Document how to use tasks from bundles.
Docs only! N/A: 
review them:
```
spec:
```
---
=> Add details on using tasks from bundles

task/jib-gradle/OWNERS, task/jib-maven/OWNERS
=> Add new Jib member to OWNERs

go.mod, go.sum, vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh, vendor/github.com/tektoncd/plumbing/scripts/library.sh, vendor/modules.txt
review them:
```
spec:
```
---
=> Bump plumbing dependencies to fix CI

pipeline/build-push-gke-deploy/0.1/README.md, task/ansible-tower-cli/0.1/README.md, task/boskos-acquire/0.1/README.md, task/boskos-release/0.1/README.md, task/buildkit-daemonless/0.1/README.md, task/buildkit/0.1/README.md, task/buildpacks/0.1/README.md, task/buildpacks/0.2/README.md, task/codecov/0.1/README.md, task/git-cli/0.1/README.md, task/git-rebase/0.1/README.md, task/gitlab-add-label/0.1/README.md, task/sonarqube-scanner/0.1/README.md
Few task's README contains some url links which had
invalid directory path and was pointing to a invalid page
Signed-off-by: Shiv Verma <shverma@redhat.com>
review them:
```
spec:
```
---
=> Improves url links in the README

task/github-app-token/0.2/github-app-token.yaml
* Allow defining the github api url
* Handle Exception better by showing the error message.
(i.e: in case if ntp is not synchronized and the jwt token would not be issued due of time drift between github servers and where this task is run)
* I am not sure if bumping the task version is needed since this is a pretty silent change.
review them:
```
spec:
```
---
[example]: …
=> github-app-token allow github api url to be defined

task/send-to-microsoft-teams/0.1/README.md, task/send-to-microsoft-teams/0.1/send-to-microsoft-teams.yaml
A Task to send a message towards a Microsoft Teams Channel in the same spirit as the Slack and Telegram notification options.
review them:
```
spec:
```
---
=> Add Microsoft Teams Notification Task

task/yq/0.1/README.md, task/yq/0.1/tests/pre-apply-task-hook.sh, task/yq/0.1/tests/resources.yaml, task/yq/0.1/tests/run.yaml, task/yq/0.1/yq.yaml
Add a yq task for GitOps repository usage (like a helm chart inside an ArgoCD monitored GitOps repository).
=> Add YQ Task including tests

task/github-open-pr/0.1/README.md, task/github-open-pr/0.1/github-open-pr.yaml, task/github-open-pr/0.1/tests/fixtures/github-open-pr.yaml, task/github-open-pr/0.1/tests/pre-apply-task-hook.sh, task/github-open-pr/0.1/tests/run.yaml
Add a simple task to open a PR on github which uses the Github API directly.
review them:
---
=> Add Github Open PR Task

test/e2e-tests.sh
Pipelines just released v0.25.0.
This commit updates the e2e test runner to use the new version
of Pipelines when testing catalog entries.
review them:
```
spec:
```
---
=> Update catalog e2e test runner to use Pipelines v0.25.0

task/kube-linter/0.1/README.md, task/kube-linter/0.1/kube-linter.yaml, task/kube-linter/0.1/samples/config_sample1.yaml, task/kube-linter/0.1/samples/config_sample2.yaml, task/kube-linter/0.1/samples/pvc.yaml, task/kube-linter/0.1/samples/run.yaml, task/kube-linter/0.1/tests/pre-apply-task-hook.sh, task/kube-linter/0.1/tests/run.yaml
This task makes it possible to use Kube-Linter within Tekton pipelines.
=> Add task for Kube-Linter Tool

task/github-set-status/0.2/github-set-status.yaml
Adjust script title comment
review them:
```
spec:
```
---
=> docs: typo in script title comment

task/pytest/0.1/README.md, task/pytest/0.1/pytest.yaml
review them:
```
spec:
```
---
=> Fixed source directory bug when not set at the default (.)

roadmap.md
This is an inital attempt to update the roadmap for 2021.
This is open for discussion, feedback, proposals, …
/cc @tektoncd/catalog-collaborators 
/cc @tektoncd/catalog-maintainers 
review them:
```
spec:
```
---
=> Update roadmap for 2021

test/e2e-tests.sh
Tekton pipeline just released 0.26, updating catalog to use the latest pipeline release.
https://github.com/tektoncd/pipeline/releases/tag/v0.26.0
review them:
```
spec:
```
---
=> updating tekton pipeline

task/golang-fuzz/0.1/README.md, task/golang-fuzz/0.1/golang-fuzz.yaml, task/golang-fuzz/0.1/tests/pre-apply-task-hook.sh, task/golang-fuzz/0.1/tests/resources.yaml, task/golang-fuzz/0.1/tests/run.yaml, task/golang-fuzz/OWNERS
This task is a Golang Tekton Task to fuzz Go projects
It uses the native Go Fuzzing Beta for dynamic analysis to find issues
in your code.
The release announcement https://blog.golang.org/fuzz-beta notes that:
"Fuzzing is a type of automated testing which continuously manipulates
inputs to a program to find issues such as panics or bugs. These
semi-random data mutations can discover new code coverage that existing
unit tests may miss, and uncover edge case bugs which would otherwise
go unnoticed. Since fuzzing can reach these edge cases, **fuzz testing is
particularly valuable for finding security exploits and vulnerabilities**"
review them:
```
spec: …
```
=> Add Golang Fuzz Task

task/jib-maven/0.4/README.md, task/jib-maven/0.4/jib-maven.yaml, task/maven/0.2/README.md, task/maven/0.2/maven.yaml
Following [TEP 70](https://github.com/tektoncd/community/blob/main/teps/0070-tekton-catalog-task-platform-support.md), information about platforms, on which tasks can be run, is added.
As well as document multi-arch maven image for `linux/s390x` and `linux/ppc64le` platforms.
Tested for `linux/amd64`, `linux/s390x`, `linux/ppc64le` platforms using e2e test provided with the tasks.
review them:
```
spec:
```
--- …
=> Add platforms information for maven and jib-maven tasks

task/goreleaser/0.2/README.md, task/goreleaser/0.2/goreleaser.yaml, task/goreleaser/0.2/samples/run.yaml
Allow configure the image name and default to latest,
The latest goreleaser version probably break the old version so bumping
the task version here and allow to override if the user wants it with
params.
review them:
```
spec:
```
---
[validation]: …
=> Add goreleaser task 0.2

task/helm-upgrade-from-repo/0.2/README.md, task/helm-upgrade-from-repo/0.2/helm-upgrade-from-repo.yaml, task/helm-upgrade-from-source/0.2/README.md, task/helm-upgrade-from-source/0.2/helm-upgrade-from-source.yaml
Following [TEP 70](https://github.com/tektoncd/community/blob/main/teps/0070-tekton-catalog-task-platform-support.md), information about platforms, on which tasks can be run, is added.
Tested for `linux/amd64`, `linux/s390x`, `linux/ppc64le` platforms using e2e test provided with tasks.
Also helm image is updated to use multi-arch version of it.
review them:
```
spec:
```
---
[example]: …
=> Add platforms information for helm-upgrade-from-repo and helm-upgrade-from-source tasks

task/git-cli/0.1/README.md, task/git-cli/0.1/git-cli.yaml, task/git-cli/0.2/README.md, task/git-cli/0.2/git-cli.yaml, task/kubeconfig-creator/0.1/README.md, task/kubeconfig-creator/0.1/kubeconfig-creator.yaml, task/pull-request/0.1/README.md, task/pull-request/0.1/pull-request.yaml, task/tkn/0.1/README.md, task/tkn/0.1/tkn.yaml, task/tkn/0.2/README.md, task/tkn/0.2/tkn.yaml
Annotation about `linux/amd64`,`linux/s390x`,`linux/ppc64le` platforms was added to the latest versions of the  `tkn`, `git-cli`, `pull-request` and `kubeconfig-creator` tasks.
Tested for all mentioned platforms using e2e test provided with the tasks.
review them:
```
spec:
```
---
[validation]: …
=> Add platforms annotation to several task

task/ansible-runner/0.1/README.md
review them:
```
spec:
```
---
=> Minor fix in ansible-runner readme

task/git-version/0.1/README.md, task/git-version/0.1/git-version.yaml, task/git-version/0.1/tests/pre-apply-task-hook.sh, task/git-version/0.1/tests/resources.yaml, task/git-version/0.1/tests/run.yaml
Add a task to generate versions based on git history.
review them:
=> Add git-version task

README.md
review them:
```
spec:
```
---
=> Adds reference to add new Categories to existing generalized list

task/helm-upgrade-from-source/0.3/README.md, task/helm-upgrade-from-source/0.3/helm-upgrade-from-source.yaml, task/helm-upgrade-from-source/0.3/samples/helm-upgrade-from-source-task-run.yaml.tmpl, task/helm-upgrade-from-source/0.3/tests/pre-apply-task-hook.sh, task/helm-upgrade-from-source/0.3/tests/resources.yaml, task/helm-upgrade-from-source/0.3/tests/run.yaml
Add an option to pass extra parameters to helm.
review them:
```
spec:
```
---
=> Add extra params

test/e2e-common.sh
When adding `fixtures` volume, we need to consider whether the task
already has a volumes section. If the volumes is already defined, then
we should add `fixtures` rather than replacing the whole volumes.
The bug causes integration test failure for #776 
test/e2e: handle fixtures configmap volume correctly
review them:
=> test/e2e: handle fixtures configmap volume correctly

task/yq/0.2/README.md, task/yq/0.2/tests/pre-apply-task-hook.sh, task/yq/0.2/tests/resources.yaml, task/yq/0.2/tests/run.yaml, task/yq/0.2/yq.yaml
Added a version 0.2 with support for multiple files at once in a single task.
review them:
- [ 
- X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Add version 0.2 with support for multiple files at once

task/rsync/0.1/Dockerfile, task/rsync/0.1/README.md, task/rsync/0.1/rsync.yaml, task/rsync/0.1/samples/rsync-local-to-remote.yaml, task/rsync/0.1/samples/rsync-remote-to-local.yaml, task/rsync/0.1/samples/secret-ssh.yaml, task/rsync/OWNERS
Signed-off-by: shaowenchen <mail@chenshaowen.com>
add sync task
review them:
```
spec:
```
---
=> feature: add rsync task

roadmap.md
delete extra characters '-' in roadmap.md
review them:
```
spec:
```
---
=> delete extra characters in roadmap.md file

task/sonarqube-scanner/0.1/sonarqube-scanner.yaml
makes sonar-project.properties editable when mounted from secret
review them:
```
spec:
```
---
=> fix: https://github.com/tektoncd/catalog/issues/768

task/pylint/0.1/README.md, task/pylint/0.1/pylint.yaml
Annotation about `linux/amd64`, `linux/s390x`, `linux/arm64` and `linux/ppc64le` platforms is added to the `0.1` version of the `pylint` task.
The task was tested for `linux/amd64`, `linux/s390x`, `linux/ppc64le` platforms. `linux/arm64` platform was added to the list, because task image has `linux/arm64` support.
review them:
```
spec:
```
---
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/ …
=> Add platforms annotation to pylint 0.1 task

task/kn-apply/0.1/kn-apply.yaml
This will add home env with value /tekton/home to the kn-apply task
as it throws warning sometime like
2021/11/03 12:18:36 warning: unsuccessful cred copy: .docker from
/tekton/creds to /: unable to create destination directory:
mkdir /.docker: permission denied
This env does not break the task so adding it in same version
review them:
```
spec:
```
---
[example]: …
=> Add home env to kn-apply task

CONTRIBUTING.md
Update contributiong guide with guidance on  how to bump a task and pipeline
make it easy for reviewers and have a clean git log.
review them:
```
spec:
```
---
=> Update contribution guide on how to bump a task/pipeline

task/send-to-webhook-discord/0.1/README.md, task/send-to-webhook-discord/0.1/send-to-webhook-discord.yaml
Update task/send-to-webhook-discord/0.1/README.md
Co-authored-by: Vinamra Jain <vinjain@redhat.com>
Update task/send-to-webhook-discord/0.1/README.md
Co-authored-by: Vinamra Jain <vinjain@redhat.com>
fix: trailing spaces
fix: add default message and avatar
Update task/send-to-webhook-discord/0.1/send-to-webhook-discord.yaml
Update task/send-to-webhook-discord/0.1/README.md
review them:
```
spec:
```
---
[example]: …
=> feat: discord messaging

task/kubernetes-actions/0.2/samples/update-deployment-image-taskrun.yaml
Correct the quoting in the patch. Now the variables are included
in the patch.
Fixes #887
review them:
```
spec:
```
---
=> Correct quoting in sample file

task/gcs-download/0.1/README.md
Fixes https://github.com/tektoncd/catalog/issues/890
Prior to this commit an example in the readme for gcs-download
referenced a Task that didn't exist.
This commit updates the broken taskRef to point to the correctly
named Task.
review them:
```
spec:
```
---
=> Fix small issue with gcs-download README

task/hadolint/0.1/README.md, task/hadolint/0.1/hadolint.yaml, task/hadolint/0.1/tests/pre-apply-task-hook.sh, task/hadolint/0.1/tests/pvc.yaml, task/hadolint/0.1/tests/run.yaml
This PR introduces tasks for Hadolint.
review them:
```
spec:
```
---
=> Add Hadolint Dockerfile Scan

task/yq/0.3/README.md, task/yq/0.3/tests/pre-apply-task-hook.sh, task/yq/0.3/tests/resources.yaml, task/yq/0.3/tests/run.yaml, task/yq/0.3/yq.yaml
* Added an `image` param so that you have more control over which version of yq you want to use
* Updated the default value to the newest image
* Added the `set -e` flag so that the script does not report success when one of the commands failed
review them:
```
spec:
```
---
=> Yq add optional image param

task/asciidoctor/0.1/README.md, task/asciidoctor/0.1/asciidoctor.yaml, task/asciidoctor/0.1/tests/pre-apply-task-hook.sh, task/asciidoctor/0.1/tests/pvc.yaml, task/asciidoctor/0.1/tests/run.yaml
Asciidoctor text processor task
https://asciidoctor.org
This PR introduces tasks for Asciidoctor.
review them:
```
spec:
```
---
=> Add asciidoctor Task

task/pluto/0.1/README.md, task/pluto/0.1/pluto.yaml, task/pluto/0.1/tests/pre-apply-task-hook.sh, task/pluto/0.1/tests/run.yaml
Added a new task to run `pluto`
- https://pluto.docs.fairwinds.com/
review them:
```
spec:
```
---
=> added 0.1 of pluto task

task/stackrox-image-check/0.1/README.md, task/stackrox-image-check/0.1/samples/rox-pipeline.yaml, task/stackrox-image-check/0.1/samples/rox-secrets.yaml, task/stackrox-image-check/0.1/stackrox-image-check.yaml, task/stackrox-image-check/OWNERS, task/stackrox-image-scan/0.1/README.md, task/stackrox-image-scan/0.1/samples/rox-pipeline.yaml, task/stackrox-image-scan/0.1/samples/rox-secrets.yaml, task/stackrox-image-scan/0.1/stackrox-image-scan.yaml, task/stackrox-image-scan/OWNERS
This PR introduces tasks for stackrox-image-scan and stackrox-image-check, integrating with StackRox and Red Hat Advanced Cluster Security.
Replaces - https://github.com/tektoncd/catalog/pull/783
review them:
```
spec:
```
---
=> Add StackRox Image Scan & Image Check Tasks - Replace #783

task/powershell/0.1/README.md
Fix random Usage Sample for PWSH
Fix random Usage Sample for PWSH
review them:
```
spec:
```
---
=> Fix random Usage Sample for PWSH

test/e2e-tests.sh
Update the e2e tests to use the latest release of Tekton pipelines
v0.33.0.
review them:
```
spec:
```
---
=> Update the RELEASE_YAML to pipeline v0.33.0

test/e2e-tests.sh
Update the e2e tests to use the latest release of Tekton pipelines
v0.33.1.
review them:
```
spec:
```
---
=> Update the RELEASE_YAML to pipeline v0.33.1

task/kaniko/0.6/README.md, task/kaniko/0.6/kaniko.yaml, task/kaniko/0.6/tests/pre-apply-task-hook.sh, task/kaniko/0.6/tests/resources.yaml, task/kaniko/0.6/tests/run.yaml
Added chains compliant Kaniko task. Addresses issue #908 
review them:
```
spec:
```
---
=> Added chains compliant kaniko task

task/buildah/0.3/README.md
review them:
```
spec:
```
---
=> use the version of the current task for the installation command

task/gcloud/0.2/README.md, task/gcloud/0.2/gcloud.yaml
Update cloud-sdk version from `312.0.0`->`374.0.0`
Correct readme documentation of the default (pinned!) image `google/cloud-sdk:slim` -> `gcr.io/google.com/cloudsdktool/cloud-sdk:374.0.0-slim`
review them:
```
spec:
```
---
=> Update gcloud task

task/kubernetes-actions/0.2/README.md
In the documentation the wrong task name is used. 
According to the definition it must be `kubernetes-actions` and not `kubectl-actions`
review them:
```
spec:
```
---
=> use the correct task name

task/orka-deploy/0.1/README.md, task/orka-deploy/0.1/orka-deploy.yaml, task/orka-full/0.1/README.md, task/orka-full/0.1/orka-full.yaml, task/orka-init/0.1/README.md, task/orka-init/0.1/orka-init.yaml, task/orka-teardown/0.1/README.md, task/orka-teardown/0.1/orka-teardown.yaml
**What:**
Parameterizing orka task images so it can be overriden
**Why:**
docker.io not accessible from internal networks. one needs to either access it via a proxy OR copy the image into an internal docker registry. Doing this requires modifying the `image` var.  
**How:**
Creating params var for task image which defaults to orka docker.io image.
review them:
```
spec:
```
---
[example]: …
=> Parameterizing orka-image name

task/jib-gradle/0.4/README.md, task/jib-gradle/0.4/jib-gradle.yaml, task/jib-gradle/0.4/tests/pre-apply-task-hook.sh, task/jib-gradle/0.4/tests/resources.yaml, task/jib-gradle/0.4/tests/run.yaml
Updated `jib-gradle` task to be chains compliant. Fixes #946
review them:
```
spec:
```
=> Update jib-gradle task to be chains compliant

task/buildpacks/0.4/README.md, task/buildpacks/0.4/buildpacks.yaml, task/buildpacks/0.4/samples/dockerconfig.yaml, task/buildpacks/0.4/samples/env-vars.yaml, task/buildpacks/0.4/samples/results.yaml, task/buildpacks/0.4/tests/pre-apply-task-hook.sh, task/buildpacks/0.4/tests/resources.yaml, task/buildpacks/0.4/tests/run.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
- removing `securityContext.privileged : true` as it is not needed anymore 
- adding `dockerconfig` workspace, which is an optional workspace that allows providing a `.docker/config.json` file for Buildpacks lifecycle binary to access the container registry. The file should be placed at the root of the Workspace with name `config.json`.
Bumping Task version to 0.4 as this is breaking change.
review them:
```
spec:
```
---
[TEP]: …
=> Buildpacks: remove `securityContext.privileged` and add `dockerconfig` workspace

task/datree/0.1/README.md, task/datree/0.1/datree.yaml, task/datree/0.1/samples/pvc.yaml, task/datree/0.1/samples/run.yaml, task/datree/0.1/samples/secret.yaml
Add [Datree](https://datree.io/) task to the Tekton catalog.
review them:
```
spec:
```
---
=> Add datree task

task/gcs-upload/0.3/README.md, task/gcs-upload/0.3/gcs-upload.yaml, task/gcs-upload/0.3/samples/gcs-sample.yaml
Improve gcs-upload performace with busy targets
gcs-upload uses `rsync` to upload folders. When the target contains
many thousands of files, it can take a very long time.
Change the default implementation to use `cp -r` which only copies
new files. Recursive copy supports not replacing existing files,
so adding an option to the task for that.
The option to delete extra remote files is still there, and still
false by default. Delete extra remote files is not compatible with
"not replace remote files" so adding a note about that.
review them:
```
spec:
```
_See [the …
=> Gcs upload copy

task/git-clone/0.6/README.md, task/git-clone/0.6/git-clone.yaml, task/git-clone/0.6/samples/git-clone-checking-out-a-branch.yaml, task/git-clone/0.6/samples/git-clone-checking-out-a-commit.yaml, task/git-clone/0.6/samples/git-clone-sparse-checkout.yaml, task/git-clone/0.6/samples/using-git-clone-result.yaml, task/git-clone/0.6/tests/run.yaml
The Kyverno `verify-image` policy fails to verify the signature on `v0.21.0`:
```
task fetch-from-git has failed: failed to create task run pod "cache-image-pipelinerun-z6j99-fetch-from-git-vnmbv": admission webhook "mutate.kyverno.svc-fail" denied the request: 
resource Pod/default/cache-image-pipelinerun-z6j99-fetch-from-git-vnmbv-pod-dl755 was blocked due to the following policies
verify-image:
verify-image: 'image signature verification failed for gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.21.0:
signature mismatch'
. Maybe missing or invalid Task default/git-clone
```
Essentially a copy of the 0.4 version with the pipeline version minimum changed to v0.29.0.
review them:
```
spec: …
```
=> Update minimum pipeline version to v0.29.0 for task git-clone

task/ansible-runner/0.1/README.md, task/ansible-runner/0.1/ansible-runner.yaml, task/ansible-runner/0.2/README.md, task/ansible-runner/0.2/ansible-runner.yaml, task/ansible-runner/0.2/support/ansible-deployer.yaml, task/ansible-runner/0.2/support/playbooks-pvc.yaml, task/ansible-runner/0.2/tests/pre-apply-task-hook.sh, task/ansible-runner/0.2/tests/resources.yaml, task/ansible-runner/0.2/tests/run.yaml
The image being used here was removed by the authors from dockerhub and
instead moved to quay.io. Also the tag used in this version was very old
and no longer present in quay.io.
----
This bumps the version of ansible-runner which uses the latest
ansible-runner image and this requires community.general to be installed
from ansible collections.
closes #970 
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalo …
=> Deprecate v0.1 of ansible-runner and add 0.2 version for same

test/e2e-tests.sh
Updating the catalog repo test infrastructure to use the latest release - v0.35.0
review them:
- [] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
```
spec:
```
---
=> updating pipeline release

task/datree/0.1/README.md
Remove unused parameter from datree docs
review them:
```
spec:
```
---
=> Remove unused parameter from datree docs

task/github-set-status/0.4/github-set-status.yaml, task/github-set-status/0.4/tests/fixtures/github-set-status-response.json, task/github-set-status/0.4/tests/fixtures/github-set-status.yaml, task/github-set-status/0.4/tests/pre-apply-task-hook.sh, task/github-set-status/0.4/tests/run.yaml
Rather than using params in the script, set environment variables
and use them in the python script with os.getenv
review them:
```
spec:
```
---
=> Use environment variables in github-set-status

task/ansible-builder/0.1/README.md, task/ansible-builder/0.1/ansible-builder.yaml, task/ansible-builder/0.1/samples/0-internal-registry.yaml, task/ansible-builder/0.1/samples/1-pipeline.yaml, task/ansible-builder/0.1/tests/pre-apply-task-hook.sh, task/ansible-builder/0.1/tests/run.yaml, task/ansible-builder/OWNERS
Adds an [ansible-builder task ](https://ansible-builder.readthedocs.io/en/stable/)to create the context from an execution environment.
review them:
- [ x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [x ] File path follows  `<kind>/<name>/<version>/name.yaml`
- [x ] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [x ] Has mandatory `metadata.labels` - …
=> Ansible builder task 0.1

task/datree/0.1/datree.yaml
Update the datree task description
review them:
```
spec:
```
---
=> Update datree task description

task/argocd-task-connect-repo/0.1/README.md, task/argocd-task-connect-repo/0.1/argocd-task-connect-repo.yaml
Add task to connect a repository to an ArgoCD server. Formatted like the other existing argocd-task
review them:
```
spec:
```
---
=> Add task to connect a repository to an ArgoCD server

task/git-clone/0.7/samples/git-clone-for-ssl-ca.yaml
Addressed comment from https://github.com/tektoncd/catalog/pull/1001#pullrequestreview-1020010941
review them:
```
spec:
```
---
=> Add samples for ssl-ca-directory

task/github-set-status/0.4/github-set-status.yaml
The task is using python:3.10.1-alpine3.15 x86 image only. 
This PR fixes https://github.com/tektoncd/catalog/issues/987 on [task/github-set-status/0.4/github-set-status.yaml](https://github.com/tektoncd/catalog/compare/main...kabhiibm:main#diff-144b5e4752c056cfbf116f4b6b06bd77c947f8488739de064333abe518d238ce)
Removing sha256 value to execute test on correct test image for respective platforms (x86, pp64le, s390x).
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-te …
=> Use Multi-arch python image for ppc64le, s390x

task/buildpacks/0.5/README.md, task/buildpacks/0.5/buildpacks.yaml, task/buildpacks/0.5/samples/dockerconfig.yaml, task/buildpacks/0.5/samples/env-vars.yaml, task/buildpacks/0.5/samples/results.yaml, task/buildpacks/0.5/tests/pre-apply-task-hook.sh, task/buildpacks/0.5/tests/resources.yaml, task/buildpacks/0.5/tests/run.yaml
Updated `buildpacks` task to be chains compliant.
review them:
```
spec:
```
=> Update buildpacks task to be chains compliant

task/git-cli/0.4/README.md, task/git-cli/0.4/git-cli.yaml, task/git-cli/0.4/tests/run.yaml
Fix nonroot user support: setting HOME env
review them:
```
spec:
```
---
=> Git cli home env

task/git-batch-merge/0.1/tests/run.yaml, task/git-batch-merge/0.2/tests/run.yaml, task/git-clone/0.1/tests/run.yaml, task/kn/0.1/knative-dockerfile-deploy/service_traffic/README.md, test/e2e-tests.sh
This commit updates the catalog e2e tests to use the latest Pipelines release.
review them:
- n/a Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- n/a Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- n/a Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- n/a Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
=> Use latest release for e2e tests

task/gradle/0.2/README.md, task/gradle/0.2/gradle.yaml, task/gradle/0.2/tests/pre-apply-task-hook.sh, task/gradle/0.2/tests/resources.yaml, task/gradle/0.2/tests/run.yaml
Update how Gradle is invoked to support multiple parameters in the TASKS parameter
review them:
task changed or new task added)
practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
validation][validation]
```
spec:
```
---
=> Support multiple params in tasks

task/orka-init/0.2/README.md, task/orka-init/0.2/orka-init.yaml, task/orka-init/0.2/tests/fixtures/orka.yaml, task/orka-init/0.2/tests/resources.yaml, task/orka-init/0.2/tests/run.yaml
Added version `0.2` for `orka-init` task
* Compatibility changes to make the pipelines also work properly when using Tekton v0.34.1
* Added additional task parameters for feature parity with Orka v2.1.0:
* `tag`: When specified, the VM is preferred to be deployed to a node marked with this tag.
* `tag-required`: VM is required to be deployed to a node marked with tag specified above.
* `scheduler`: When set to 'most-allocated', the deployed VM will be scheduled to nodes having most of their resources allocated.
* Changes in scripts to dynamically add additional parameters to VM config/deploy request when they are passed in pipelines
review them:
```
spec: …
```
=> v0.2 for orka-init task

task/nexus-lifecycle-scan/0.1/README.md, task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yml, task/nexus-lifecycle-scan/0.1/samples/sample-pipeline-nexus-lifecycle-scan.yml
Add Sonatype Nexus Lifecycle scan task to catalog
review them:
---
=> Add Sonatype Nexus Lifecycle scan task to catalog

task/gcloud/0.1/README.md, task/gcloud/0.2/README.md
Fixed typo: `kubect` --> `kubectl`.
review them:
```
spec:
```
---
=> Fixed typo: kubect --> kubectl.

task/gcloud/0.3/README.md, task/gcloud/0.3/gcloud.yaml, task/gcloud/0.3/tests/config.yaml, task/gcloud/0.3/tests/default-version.yaml, task/gcloud/0.3/tests/gsutil-version.yaml, task/gcloud/0.3/tests/version-test.yaml
`gcloud` task version 0.3 always uses the latest `gcloud` CLI.
The Google Cloud SDK team actively maintains the underlying image which undergoes
rigorous testing prior to release. Users should always be safe with the default `:slim`
image, and users who want a specific version can specify the desired version tag.
For details on the underlying image, see https://github.com/GoogleCloudPlatform/cloud-sdk-docker
Changes from version 0.2:
- defaults to latest `:slim` image
- version and image are configurable via params
- added `SCRIPT` param to enable call of `gsutil` and other commands
review them:
```
spec:
```
---
[TEP]: …
=> Add gcloud task version 0.3.

task/buildah/0.5/README.md, task/buildah/0.5/buildah.yaml, task/buildah/0.5/samples/dockerconfig.yaml, task/buildah/0.5/samples/openshift-internal-registry.yaml, task/buildah/0.5/tests/internal-registry/internal-registry.yaml, task/buildah/0.5/tests/pre-apply-task-hook.sh, task/buildah/0.5/tests/run.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
review them:
```
spec:
```
---
=> [task][buildah] - v0.5: option to provide container registry credentials in a workspace

task/s2i/0.3/Dockerfile, task/s2i/0.3/README.md, task/s2i/0.3/s2i.yaml, task/s2i/0.3/samples/dockerconfig.yaml, task/s2i/0.3/samples/openshift-internal-registry.yaml, task/s2i/0.3/tests/internal-registry/internal-registry.yaml, task/s2i/0.3/tests/pre-apply-task-hook.sh, task/s2i/0.3/tests/run.yaml
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
review them:
```
spec:
```
---
=> [task][s2i] - v0.3: option to provide container registry credentials in a workspace

CONTRIBUTING.md
- Most changes are grammar nits or fixes to typos.
- I cleaned up whitespace while I was here.
- Fixed some broken links (presumably their targets had moved)
- There are no expected meaningful changes in this PR.
review them:
---
=> Cleanup CONTRIBUTING.md

task/gcloud/0.1/gcloud.yaml, task/gcloud/0.2/gcloud.yaml, task/gcloud/0.3/gcloud.yaml
Update `gcloud` task to list in all relevant categories.
```
spec:
```
---
=> List gcloud task in all relevant categories.

.github/pull_request_template.md
- Move all link definitions down to the bottom for readability.
- Added request for `kind` label
- Added link to end-to-end testing documentation
review them:
---
=> Cleanup and enhance pull_request_template.

task/git-clone/0.8/README.md, task/git-clone/0.8/samples/git-clone-checking-out-a-branch.yaml, task/git-clone/0.8/samples/git-clone-checking-out-a-commit.yaml, task/git-clone/0.8/samples/git-clone-for-ssl-ca.yaml, task/git-clone/0.8/samples/git-clone-sparse-checkout.yaml, task/git-clone/0.8/samples/using-git-clone-result.yaml, task/git-clone/0.8/tests/run.yaml
This commit updates the docs, samples and tests required to run this
task as a non-root user.
Fix #1044
review them:
=> [git-clone] Update docs, samples and tests for nonroot user

task/blue-green-deploy/0.1/README.md, task/istio-canary-release/0.1/README.md, task/kn-apply/0.1/README.md, task/kn-apply/0.2/README.md, task/kn/0.1/README.md, task/kn/0.2/README.md
Signed-off-by: Puneet Punamiya ppunamiy@redhat.com
review them:
```
spec:
```
--- …
=> Fixes installations instructions in readme

OWNERS, task/generate-build-id/OWNERS
@sbws has deleted his account
/kind cleanup 
review them:
---
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs] …
=> Remove @sbwsg -- account deleted.

task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yaml
Signed-off-by: Puneet Punamiya ppunamiy@redhat.com
review them:
```
spec:
```
--- …
=> Fix name in nexus-lifecycle-scan manifest to match the directory name

task/gcloud/0.3/tests/gsutil-version-args.yaml
Add `gcloud` test example passing args to gsutil.
/kind misc
review them:
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md …
=> Add `gcloud` test example passing args to gsutil.

task/buildah/0.5/samples/dockerconfig.yaml
This PR is intended to do a workspace name fix for a PipelineRun in  [dockerconfig.yaml](https://github.com/tektoncd/catalog/blob/main/task/buildah/0.5/samples/dockerconfig.yaml).
/kind bug
Fixes #1053 
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organizati …
=> fix workspace name

task/grype/0.1/grype.yaml, task/syft/0.1/syft.yaml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
quick fix
/cc @vdemeester @vinamra28 
review them:
- [] Follows the [authoring recommendations][authoring]
```
spec:
```
[example]: …
=> fix: add type to argument to both grype and syft tasks

pipeline/artifacthub-repo.yml, task/artifacthub-repo.yml
This follows the artifacthub documention :
https://artifacthub.io/docs/topics/repositories/#ownership-claim.
I did create an organization there. @tektoncd/catalog-maintainers please send me (on slack, or comment here), your username on artifacthub so that I can add you to the organization there (and also in this file as owner).
review them:
```
spec:
``` …
=> Add artifacthub metadata to tektoncd/catalog

pipeline/artifacthub-repo.yml, task/artifacthub-repo.yml
See
https://artifacthub.io/docs/topics/repositories/#verified-publisher.
Those IDs are coming from the repositories claimed in ArtifactHub.
/cc @vinamra28 @jerop @chmouel @abayer 
review them:
```
spec:
```
[TEP]: …
=> The repositoryID needs to be set for being seen as verified

pipeline/artifacthub-repo.yml, task/artifacthub-repo.yml
Add @QuanZhang-William as repo owner to the Artifact Hub metadata file
review them:
```
spec:
```
[validation]: …
=> Add zhangquan to Artifact Hub Tekton repo owner

OWNERS
Following the Contributor ladder[1], I am moving some OWNERS to alumni as they are/were inactive for a longer period.
[1]: https://github.com/tektoncd/community/blob/main/process.md#inactivity
review them:
```
spec:
```
[TEP]: …
=> Remove some OWNERs due to inactivity

task/orka-init/0.2/README.md, task/orka-init/0.2/orka-init.yaml
orka-init 0.2 - change param name from `docker-image` to `orka-tekton-runner-image` to keep it consistent with the other tasks.  For more details - [PR comment](https://github.com/tektoncd/catalog/pull/1030#discussion_r939546941)
review them:
```
spec:
```
=> orka-init 0.2 docker-image param name change

task/orka-full/0.2/README.md, task/orka-full/0.2/orka-full.yaml
orka-full 0.2 - change param name from `docker-image` to `orka-tekton-runner-image` to keep it consistent with the other tasks.  For more details - [PR comment](https://github.com/tektoncd/catalog/pull/1030#discussion_r939546941)
review them:
```
spec:
```
=> orka-full 0.2 docker-image param name change

test/e2e-tests.sh
Latest pipeline release.
review them:
```
spec:
```
[authoring]: …
=> e2e-tests.sh: bump to 0.40.0 pipeline release

task/rhacs-deployment-check/3.71/README.md, task/rhacs-deployment-check/3.71/rhacs-deployment-check.yaml, task/rhacs-deployment-check/3.71/samples/pipeline.yaml, task/rhacs-deployment-check/3.71/samples/pipelinerun.yaml, task/rhacs-deployment-check/3.71/samples/secrets.yaml, task/rhacs-deployment-check/OWNERS, task/rhacs-image-check/3.71/README.md, task/rhacs-image-check/3.71/rhacs-image-check.yaml, task/rhacs-image-check/3.71/samples/pipeline.yaml, task/rhacs-image-check/3.71/samples/pipelinerun.yaml, task/rhacs-image-check/3.71/samples/rox-secrets.yaml, task/rhacs-image-check/3.71/samples/secrets.yaml, task/rhacs-image-check/OWNERS, task/rhacs-image-scan/3.71/README.md, task/rhacs-image-scan/3.71/rhacs-image-scan.yaml, task/rhacs-image-scan/3.71/samples/pipeline.yaml, task/rhacs-image-scan/3.71/samples/pipelinerun.yaml, task/rhacs-image-scan/3.71/samples/secrets.yaml, task/rhacs-image-scan/OWNERS
Adds tasks `rhacs-deployment-check`, `rhacs-image-check`, and `rhacs-image-scan` using `roxctl` from Red Hat Advanced Cluster Security.
Developed with input from tasks stackrox-image-check and stackrox-image-scan with these differences
* `roxctl` image rather than curling for binary
* command args rather than script
* tasks are versioned to match roxctl image
* updated examples help illustrate forced image scan
review them:
- **No**. _Requires external service integration._
```
spec:
one line summary of …
```
=> add RHACS deployment, image check and scan tasks

task/sonarqube-scanner/0.4/README.md, task/sonarqube-scanner/0.4/samples/sonar-project.properties, task/sonarqube-scanner/0.4/sonarqube-scanner.yaml, task/sonarqube-scanner/0.4/tests/pre-apply-task-hook.sh, task/sonarqube-scanner/0.4/tests/resources.yaml, task/sonarqube-scanner/0.4/tests/run.yaml
Add a possibility to optionally mount a workspace with sonarqube credentials.
See https://github.com/tektoncd/catalog/pull/930 (retry/rebase of these changes on new sonarqube task version)
review them:
- [ 
```
spec:
``` …
=> Add sonarqube-scanner with optioanl credentials workspace

task/stackrox-image-scan/0.1/stackrox-image-scan.yaml
Updating stackrox image scan task changing the deprecated --format flag to the --output flag.
Changed the --format deprecated flag to the --output flag.
review them:
```
spec:
```
[example]: …
=> Updating Stackrox Image-Scan fixes #1064

task/artifacthub-repo.yml
review them:
```
spec:
```
[authoring]: …
=> Add vinamra28 as Artifacthub Tekton repo owner

task/orka-teardown/0.2/README.md, task/orka-teardown/0.2/orka-teardown.yaml, task/orka-teardown/0.2/tests/mocks/orka.yaml, task/orka-teardown/0.2/tests/mods/mod_task.py, task/orka-teardown/0.2/tests/pre-apply-task-hook.sh, task/orka-teardown/0.2/tests/resources.yaml, task/orka-teardown/0.2/tests/run.yaml
Added version `0.2` for `orka-teardown` task
* Compatibility changes to make the pipelines also work properly when using Tekton v0.34.1
* Updated `orka-tekton-runner` docker image and updated versioning.
* Requires `task/orka-init/0.2/orka-init.yaml` in `pre-apply-task-hook.sh` in order for tests to work.
review them:
```
spec:
```
--- …
=> v0.2 for orka-teardown task

task/goreleaser/0.2/goreleaser.yaml
this updates goreleaser image to latest.
faced issue with cli release, and the image was last updated almost 10 months back.
Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>
review them:
```
spec:
```
[example]: …
=> update goreleaser image to latest

task/buildpacks/0.6/README.md, task/buildpacks/0.6/buildpacks.yaml, task/buildpacks/0.6/samples/dockerconfig.yaml, task/buildpacks/0.6/samples/env-vars.yaml, task/buildpacks/0.6/samples/results.yaml, task/buildpacks/0.6/tests/pre-apply-task-hook.sh, task/buildpacks/0.6/tests/resources.yaml, task/buildpacks/0.6/tests/run.yaml
Bump CNB_PLATFORM_API version to 0.9 for buildpack task
review them:
```
spec:
``` …
=> Bump CNB_PLATFORM_API version to 0.9 for buildpack task

task/42crunch-api-security-audit/0.1/42crunch-api-security-audit.yaml, task/42crunch-api-security-audit/0.1/README.md, task/42crunch-api-security-audit/0.1/samples/README.md, task/42crunch-api-security-audit/0.1/samples/git-secret.yaml, task/42crunch-api-security-audit/0.1/samples/pipeline-run.yaml, task/42crunch-api-security-audit/0.1/samples/pipeline.yaml, task/42crunch-api-security-audit/0.1/samples/secret.yaml, task/42crunch-api-security-audit/OWNERS
review them:
```
spec:
```
[authoring]: …
=> Add '42Crunch REST API Static Security Testing' task to the catalog

task/kind/0.1/tests/run.yaml
Earlier Billy's repo was being used in which the latest pipelines version was getting installed. Changing to Vinamra's fork as the version is pinned.
review them:
```
spec:
``` …
=> Fix kind e2e tests

task/ansible-runner/0.2/ansible-runner.yaml
Setting ansible runner image as parameter to task. 
review them:
```
spec:
``` …
=> Ansinle runner image as task parameter

OWNERS
I haven't done much reviews or contributions on catalog and rather not set a false expectation for contributors I will be when they submit a PR.
review them:
```
spec:
```
[example]: …
=> Remove chmouel from OWNERS file

task/gogit/0.1/gogit.yaml, task/gogit/README.md
review them:
```
spec:
```
[authoring]: …
=> Adding the gogit task into catalog

task/git-clone/0.9/README.md, task/git-clone/0.9/git-clone.yaml
Add comitter-date Result to git-clone Task. This could be used by later tasks to populate the `SOURCE_DATE_EPOCH` environment variable (or `--timestamp` argument to buildah) to enable [reproducible builds](https://reproducible-builds.org/docs/source-date-epoch/)
review them:
```
spec:
```
[TEP]: …
=> Add committer-date Result to git-clone Task

OWNERS
Since @chmouel stepped down from maintaining catalog repository, he was missing from Alumni, hence adding him there 🙂
/kind misc
review them:
```
spec:
```
[example]: …
=> Add Chmouel in Alumni

task/pylint/0.3/README.md, task/pylint/0.3/pylint.yaml, task/pylint/0.3/tests/pre-apply-task-hook.sh, task/pylint/0.3/tests/resources.yaml, task/pylint/0.3/tests/run.yaml
Possibility to add an optional workspace to the pylint task in order to use pip.conf settings from a workspace.
review them:
```
spec:
``` …
=> Add pip.conf workspace for pylint

task/pytest/0.2/README.md, task/pytest/0.2/pytest.yaml, task/pytest/0.2/tests/pre-apply-task-hook.sh, task/pytest/0.2/tests/resources.yaml, task/pytest/0.2/tests/run.yaml
Possibility to add an optional workspace to the pytest task in order to use pip.conf settings from a workspace.
review them:
```
spec:
``` …
=> Add PyTest version 0.2 with optional pip.conf workspace

test/e2e-tests.sh
Update the catalog e2e tests to use the latest Pipeline release, v0.45.0.
/kind misc
review them:
```
spec:
```
[validation]: …
=> Update e2e-tests to use Pipeline v0.45.0

task/trivy-scanner/0.2/README.md, task/trivy-scanner/0.2/tests/pvc.yaml, task/trivy-scanner/0.2/tests/run.yaml, task/trivy-scanner/0.2/trivy-scanner.yaml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I just tried to air-gapped support of Trivy for supporting air-gapped installations by enabling a flag named `AIR_GAPPED_ENABLED.`
> _https://aquasecurity.github.io/trivy/v0.36/docs/advanced/air-gap/_
/kind feature
review them:
- [] File path follows  `<kind>/<name>/<version>/name.yaml`
- [] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
- [] …
=> add air-gapped mode to trivy

task/42crunch-api-security-audit/0.2/42crunch-api-security-audit.yaml, task/42crunch-api-security-audit/0.2/README.md, task/42crunch-api-security-audit/0.2/samples/README.md, task/42crunch-api-security-audit/0.2/samples/git-secret.yaml, task/42crunch-api-security-audit/0.2/samples/pipeline-run.yaml, task/42crunch-api-security-audit/0.2/samples/pipeline.yaml, task/42crunch-api-security-audit/0.2/samples/secret.yaml
Updates 42Crunch task to use newer docker image.
review them:
```
spec:
```
[authoring]: …
=> Update 42crunch-api-security-audit task to 0.2 and deprecate 0.1 one

task/jib-maven/0.5/README.md, task/jib-maven/0.5/jib-maven.yaml, task/jib-maven/0.5/tests/internal-registry/internal-registry.yaml, task/jib-maven/0.5/tests/pre-apply-task-hook.sh, task/jib-maven/0.5/tests/resources.yaml, task/jib-maven/0.5/tests/run.yaml
This will bump jib-maven to 0.5
to handle the case where permission to
add certs to javacacerts is no there
we just create a new store with default certs and
add provided certs to that and use that cert
in mvn command
later delete the store on exit
review them:
```
spec:
```
[TEP]: …
=> Bump jib-maven to 0.5

task/grype/0.1/grype.yaml, task/syft/0.1/syft.yaml, task/trivy-scanner/0.2/trivy-scanner.yaml
Updated value for tekton.dev/platforms annotations and mutli arch docker images for trivy, syft and grype
review them:
```
spec:
```
[validation]: …
=> Updated multi arch docker image value for trivy, syft, grype task

task/redhat-codeready-dependency-analysis/0.1/README.md, task/redhat-codeready-dependency-analysis/0.1/redhat-codeready-dependency-analysis.yaml
We have completed an extensive refactoring initiative and re-branded the project as "Red Hat Dependency Analytics" instead of its previous name, "Red Hat Codeready Dependency Analysis". As a result, "Red Hat Codeready Dependency Analysis" is now considered obsolete, with "Red Hat Dependency Analytics" taking its place.
PR to "Red Hat Dependency Analytics" new tekton task: https://github.com/tektoncd/catalog/pull/1194 
review them:
```
spec:
Paragraph(s) to describe the …
```
=> chore(deprecation): deprecate redhat-codeready-dependency-analysis task

task/buildah/0.6/README.md, task/buildah/0.6/buildah.yaml, task/buildah/0.6/samples/dockerconfig.yaml, task/buildah/0.6/samples/openshift-internal-registry.yaml, task/buildah/0.6/tests/internal-registry/internal-registry.yaml, task/buildah/0.6/tests/pre-apply-task-hook.sh, task/buildah/0.6/tests/run.yaml
New buildah 0.6 task: Upgrade to buildah v1.31.0, pin by digest and add results to docs
review them:
```
spec:
```
[validation]: …
=> Upgrade to buildah v1.31.0, pin by digest and add results to docs

task/buildkit-daemonless/0.1/buildkit-daemonless.yaml, task/buildkit/0.1/buildkit.yaml, task/buildpacks-phases/0.1/buildpacks-phases.yaml, task/buildpacks-phases/0.2/tests/run.yaml, task/buildpacks/0.2/buildpacks.yaml, task/buildpacks/0.3/tests/run.yaml, task/buildpacks/0.4/tests/run.yaml, task/buildpacks/0.5/tests/run.yaml, task/buildpacks/0.6/tests/run.yaml, task/jib-gradle/0.1/jib-gradle.yaml, task/jib-maven/0.1/jib-maven.yaml, task/makisu/0.1/makisu.yaml, task/nexus-lifecycle-scan/0.1/nexus-lifecycle-scan.yaml, task/openshift-client-kubecfg/0.1/openshift-client-kubecfg.yaml, task/openshift-client/0.1/openshift-client.yaml, task/s2i/0.1/s2i.yaml, test/e2e-common.sh, test/e2e-tests.sh
E2E tests were running an older version of pipelines ie v0.45.0. Bumping it to use the latest version v0.51.0 so that current tasks in catalog can be tested against latest version
/kind misc
review them:
```
spec:
``` …
=> Bump pipelines to v0.51.0

task/kamel-run/0.1/kamel-run.yaml, task/kamel-run/0.1/tests/pre-apply-task-hook.sh, task/kamel-run/0.1/tests/run.yaml
Fix the issue when parameters are provided to the kamel-run task.
Example of error with `container-image` param:
```
Error: cannot read sources: failed to resolve sources: missing file or unsupported scheme in examples/yaml/data/routes.yaml -t container.image=10.111.155.196/default/exampleyaml@sha256:06398e857e71463bf235623529d35b908ff1b835e51775e3ad119feb674c918d
```
Define the command parameters as an array instead of a string in the run command arguments because the it interprets the string as a single parameter.
review them:
feature, flake, misc, …
=> Fix Kamel-run issue with parameters

task/git-clone/0.9/README.md
yaml says minVersion: "0.38.0"
README says v29 is minimum, YAML says 0.38 (https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.9/git-clone.yaml#L8). Making this match YAML
review them:
```
spec:
```
[example]: …
=> Update README.md - minVersion

task/gradle/0.4/README.md, task/gradle/0.4/gradle.yaml, task/gradle/0.4/tests/pre-apply-task-hook.sh, task/gradle/0.4/tests/resources.yaml, task/gradle/0.4/tests/run.yaml
This PR adds gradle wrapper support. When a gradle wrapper file is present in the project root, this wrapper will be invoked instead of the gradle binary provided by the image. 
review them:
```
spec:
```
[example]: …
=> Gradle wrapper support

task/valint/0.1/README.md, task/valint/0.1/samples/secret.yaml, task/valint/0.1/samples/task-run.yaml, task/valint/0.1/tests/resource.yaml, task/valint/0.1/tests/run.yaml, task/valint/0.1/valint.yaml
review them:
```
spec:
```
[authoring]: …
=> Valint tekton task

task/skopeo-copy/0.3/README.md
review them:
```
spec:
```
[authoring]: …
=> corrected typo

task/nexus-lifecycle-scan/0.1/README.md
review them:
```
spec:
```
[authoring]: …
=> Update README.md changing CLI name

task/buildah/0.7/README.md, task/buildah/0.7/buildah.yaml, task/buildah/0.7/samples/dockerconfig.yaml, task/buildah/0.7/samples/openshift-internal-registry.yaml, task/buildah/0.7/tests/internal-registry/internal-registry.yaml, task/buildah/0.7/tests/pre-apply-task-hook.sh, task/buildah/0.7/tests/run.yaml
Remove `--no-cache` as no longer necessary and prevents use of `--cache-from`/`--cache-to`
See #1229 
@vdemeester @holly-cummins 
review them:
```
spec:
```
[example]: …
=> Remove --no-cache from buildah as no longer necessary

task/dockerslim-build/0.1/dockerslim-build.yaml, task/golang-fuzz/0.1/golang-fuzz.yaml, task/kythe-go/0.2/kythe-go.yaml, task/orka-deploy/0.1/orka-deploy.yaml, task/orka-deploy/0.2/orka-deploy.yaml, task/orka-full/0.1/orka-full.yaml, task/orka-full/0.2/orka-full.yaml, task/orka-init/0.1/orka-init.yaml, task/orka-init/0.2/orka-init.yaml, task/orka-teardown/0.1/orka-teardown.yaml, task/orka-teardown/0.2/orka-teardown.yaml, task/redhat-dependency-analytics/0.1/redhat-dependency-analytics.yaml, task/sonarqube-scanner/0.3/sonarqube-scanner.yaml, task/sonarqube-scanner/0.4/sonarqube-scanner.yaml
This PR deprecates the old and broken Tasks because they are now throwing errors. They are old and not actively maintained which is why we decided to deprecate them.
review them:
```
spec:
```
[example]: …
=> Deprecate old and broken Tasks

stepaction/tekton-catalog-publish/0.1/README.md, stepaction/tekton-catalog-publish/0.1/samples/run-with-workspace-secret.yaml, stepaction/tekton-catalog-publish/0.1/samples/run-without-workspace-secret.yaml, stepaction/tekton-catalog-publish/0.1/samples/secrets.yaml, stepaction/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml, stepaction/tekton-catalog-publish/0.1/tests/pre-apply-task-hook.sh, stepaction/tekton-catalog-publish/0.1/tests/run.yaml, test/e2e-common.sh
Added a StepAction `tekton-catalog-publish` to assist in publishing the StepAction catalog as a bundle.
review them:
```
spec:
```
[validation]: …
=> Created StepAction tekton-catalog-publish

task/42crunch-api-security-audit/0.2/42crunch-api-security-audit.yaml
Updates docker image for the task. This is bugfix release of the image, which introduces no new parameters etc for the task, therefore keeping the version at 0.2.
review them:
```
spec:
```
[example]: …
=> Update docker image for 42Crunch task to 3.4

CONTRIBUTING.md
In this pr, fixed the command to run e2e tests locally
review them:
```
spec:
``` …
=> fix: fix command for local execution of e2e tests

task/hugo/0.1/README.md, task/hugo/0.1/hugo.yaml, task/hugo/0.1/tests/pre-apply-task-hook.sh, task/hugo/0.1/tests/resources.yaml, task/hugo/0.1/tests/run.yaml, task/hugo/OWNERS
Adds `hugo` task for static site generation. It is based on the [hugo project](https://github.com/gohugoio/hugo) and includes a sample `pipelineRun`. It is tested successfully with `./test/run-test.sh hugo 0.1`.
review them:
```
spec:
```
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organ …
=> adding tekton task for hugo static site generator

task/redhat-dependency-analytics/0.2/README.md, task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml, task/redhat-dependency-analytics/0.2/samples/pipeline-run.yaml, task/redhat-dependency-analytics/0.2/samples/pipeline.yaml, task/redhat-dependency-analytics/0.2/samples/task-run.yaml, task/redhat-dependency-analytics/0.2/samples/workspace.yaml, task/redhat-dependency-analytics/0.2/tests/pre-apply-task-hook.sh, task/redhat-dependency-analytics/0.2/tests/resources.yaml, task/redhat-dependency-analytics/0.2/tests/run.yaml
Enhanced Tekton task to also support for Python and Go ecosystems by enabling RHDA analysis for requirements.txt and go.mod manifest files. 
review them:
```
spec:
```
[example]: …
=> feat: added support for golang and python ecosystems

task/anchore-cli/0.1/README.md, task/anchore-cli/0.1/anchore-cli.yaml, task/anchore-cli/0.1/samples/secret.yaml
review them:
```
spec:
```
[authoring]: …
=> adding anchore cli task

task/rhacs-deployment-check/OWNERS, task/rhacs-image-check/OWNERS, task/rhacs-image-scan/OWNERS
Add Daniel Haus to RHACS Tasks Owners
=> Add Daniel Haus to RHACS task owners

task/s2i/0.2/tests/run.yaml, task/s2i/0.3/tests/run.yaml
review them:
```
spec:
```
[authoring]: …
=> Fix s2i 0.3

task/helm-render-manifests-from-repo/0.1/README.md, task/helm-render-manifests-from-repo/0.1/helm-render-manifests-from-repo.yaml, task/helm-render-manifests-from-repo/0.1/samples/helm-render-manifests-from-repo-task-run.yaml.tmpl, task/helm-render-manifests-from-repo/0.1/tests/pre-apply-task-hook.sh, task/helm-render-manifests-from-repo/0.1/tests/run.yaml
This task is designed to be used as part of an implementation of the GitOps [Rendered Manifests Pattern](https://akuity.io/blog/the-rendered-manifests-pattern/).
It is intended to be unopinionated and as such will simply template a Helm chart and output a file to a workspace volume with an optionally specified name and location.
It largely follows the same structure as the existing `helm-upgrade-from-repo` task for the sake of consistency. The `OWNERS` file is empty at the moment, I wasn't sure who would be the best person yet.
I am also assuming that no corresponding issue is needed, but I'm happy to create one if there needs to be some discussion around the implementation.
review them:
- See the [end-to-end …
=> Add new task helm-render-manifests-from-repo

task/jq/0.1/README.md, task/jq/0.1/jq.yaml, task/jq/0.1/tests/pipeline.yaml, task/jq/0.1/tests/pipelinerun.yaml
review them:
```
spec:
```
[authoring]: …
=> Tekton Task JQ v0.1

task/shp/0.1/shp.yaml
review them:
```
spec:
```
[authoring]: …
=> Fix version in `shp` task

task/rhacs-deployment-check/4.0/samples/with-m2m-token/pipeline.yaml, task/rhacs-image-check/4.0/samples/with-m2m-token/pipeline.yaml, task/rhacs-image-scan/4.0/samples/with-m2m-token/pipeline.yaml, task/rhacs-m2m-authenticate/0.1/rhacs-m2m-authenticate.yaml, task/rhacs-m2m-authenticate/0.1/samples/pipeline.yaml
Update the task name to be compliant with [Tekton naming guidelines](https://github.com/tektoncd/community/blob/main/teps/0003-tekton-catalog-organization.md).
review them:
```
spec:
```
[example]: …
=> Update RHACS m2m task name

task/rhacs-m2m-authenticate/0.1/rhacs-m2m-authenticate.yaml
Fixed a typo in the version label which avoided the task being rendered within the hub.
review them:
```
spec:
```
[validation]: …
=> task: Fix typo in rhacs-m2m-authenticate

task/git-clone/0.9/README.md
Fix for [1219](https://github.com/tektoncd/catalog/issues/1219)
review them:
```
spec:
```
[validation]: …
=> Fix for Issue 1219: The "git-clone" task document about the default value of the "userHome" parameter is not right

task/git-cli/0.4/git-cli.yaml
Fix for #1289 
review them:
```
spec:
```
[authoring]: …
=> ISSUE-1289: Superfluous 'output' workspace defined in git-cli env

task/goreleaser/0.2/goreleaser.yaml
This will goreleaser task that is failing with error related to git
review them:
```
spec:
```
[validation]: …
=> Fix goreleaser task

CONTRIBUTING.md
fix typo in CONTRIBUTING.md
review them:
```
spec:
```
[authoring]: …
=> Update CONTRIBUTING.md (typo correction)

task/maven/0.4/README.md, task/maven/0.4/maven.yaml, task/maven/0.4/tests/pre-apply-task-hook.sh, task/maven/0.4/tests/resources.yaml, task/maven/0.4/tests/run.yaml
see #1309 
review them:
```
spec:
```
[authoring]: …
=> Add maven task results

task/oci-cli/0.1/README.md, task/oci-cli/0.1/oci-cli.yaml, task/oci-cli/0.1/samples/oci-cli-taskrun.yaml, task/oci-cli/0.1/samples/secret.yaml
review them:
```
spec:
```
[authoring]: …
=> adding oracle cli task for tekton

task/python-sdk-azure/0.1/README.md, task/python-sdk-azure/0.1/python-sdk-azure.yaml, task/python-sdk-azure/0.1/samples/config-map.yaml, task/python-sdk-azure/0.1/samples/run.yaml, task/python-sdk-azure/0.1/samples/secret.yaml
review them:
```
spec:
```
[authoring]: …
=> adding python sdk azure task

task/buildpacks-phases/0.3/README.md, task/buildpacks-phases/0.3/buildpacks-phases.yaml, task/buildpacks-phases/0.3/containers/skopeo-jq/Dockerfile, task/buildpacks-phases/0.3/containers/skopeo-jq/buildme, task/buildpacks-phases/0.3/samples/bp-env-vars.yaml, task/buildpacks-phases/0.3/samples/cache.yaml, task/buildpacks-phases/0.3/samples/results.yaml, task/buildpacks-phases/0.3/tests/pre-apply-task-hook.sh, task/buildpacks-phases/0.3/tests/resources.yaml, task/buildpacks-phases/0.3/tests/run.yaml, test/e2e-common.sh, test/e2e-tests.sh
This PR introduces a major update the task `Buildpack-phases` which has not been updated since a while. It supports the latest platform api spec: 0.13, lifecycle 0.20.9 and the new extension mechanism allowing to execute `Dockerfile(s)` during the build process of the application.
review them:
```
spec:
```
[TEP]: …
=> Add a new version of the Task: Buildpacks phases supporting extension mechanism

test/e2e-tests.sh
Update pipeline version used for testing to 1.1.0
review them:
```
spec:
``` …
=> Update pipeline to 1.1.0

task/yq/0.5/README.md, task/yq/0.5/tests/pre-apply-task-hook.sh, task/yq/0.5/tests/resources.yaml, task/yq/0.5/tests/run.yaml, task/yq/0.5/yq.yaml
Added a new version of the yq task to the catalog, just a copy for now
but adding the update to make it easier to review.
Using the 0.4 yq version on arm64 fails for example:
```
% tkn tr describe -n pac-e2e-test-nzrs7 yq-pipeline-run-4-7qd74-fetch-repository|grep task.*yq
pipelinesascode.tekton.dev/task-1=[yq:0.4.0]
% ocla -n pac-e2e-test-nzrs7 yq-pipeline-run-4-7qd74-yq-replace-pod
2025/07/24 19:12:51 Error executing command: fork/exec /tekton/scripts/script-0-gjfvg: exec format error
2025/07/24 19:12:42 Decoded script /tekton/scripts/script-0-gjfvg
2025/07/24 19:12:37 Entrypoint initialization
```
review them:
contains `/kind …
=> chore: Add version 0.5 of the yq task
