- README.md
- bazel/README.md
- bazel/bazel.yaml
- kaniko/README.md
- kaniko/kaniko.yaml
This migrates some initial contents from https://github.com/knative/build-templates
> Add top-level README, and bazel and kaniko Tasks

- buildpacks/README.md
- buildpacks/buildpacks-v3.yaml
This migrates the build template at https://github.com/knative/build-templates/blob/master/buildpacks/cnb.yaml
Notable changes:
* Passes `-app=.` with `workingdir: /workspace/source` instead of `-app=/workspace` since Tekton puts source in the `./source` subdir
* Uses `heroku/buildpacks` image, since it seemed to give better output while I was debugging; if buildpacks folks prefer the other image let me know, or we can change it in a future PR.
I tested this running on source at https://github.com/buildpack/sample-java-app and the task was able to detect it as Java and build it.
/cc @matthewmcnew @sclevine @ekcasey
> Add Task for Cloud Native Buildpacks

- openshift-cli/Dockerfile
- openshift-cli/README.MD
- openshift-cli/taskUsingClusterResource/octaskresource.yaml
- openshift-cli/taskUsingClusterResource/octaskrunresource.yaml
- openshift-cli/taskUsingClusterResource/resource.yaml
- openshift-cli/taskUsingServiceaccount/octask.yaml
- openshift-cli/taskUsingServiceaccount/octaskrun.yaml
- openshift-cli/taskUsingServiceaccount/role.yaml
- openshift-cli/taskUsingServiceaccount/rolebinding.yaml
- openshift-cli/taskUsingServiceaccount/serviceaccount.yaml
This will add examples of using oc binary in task
It will add a dockerfile of oc binary and two
examples
1. Using oc on same cluster using serviceAccount
2. Using oc on different cluster using clusterResource
Thanks
> Add examples for using oc

- buildpacks/README.md
- buildpacks/buildpacks-v3.yaml
- kaniko/README.md
- kaniko/kaniko.yaml
Updates kaniko and buildpacks Tasks to specify output images, and use the specified output image url instead of the `IMAGE` input param.
review them:
- [ :heavy_check_mark:  ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ :heavy_check_mark: ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
> Use image-type outputs instead of IMAGE params

- buildpacks/buildpacks-v3.yaml
The image flag in the export step should point to the run image. 
+ Pointing at the output image produces a 'MANIFEST_UNKNOWN' unknown error fetching the unbuilt image.
> Use run image as image in export step

- Gopkg.toml
Those comments are added by default when doing a `dep init`. We don't
need them and can just refer to the documentation instead.
/cc @abayer 
review them:
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
> Remove comments from Gopkg.toml and refer to the documentation

- kaniko/README.md
- kaniko/kaniko.yaml
We need to pin to specific version rather than go with the dynamic latest commit. The version v0.9.0 seems to be a stable one.
Add the parameter context support for kaniko.
review them:
> Add a specific version and context support for kaniko  

- knctl/README.md
- knctl/knctl-deploy.yaml
Adds a `knctl-deploy` task that will deploy an image (resource) as a
Knative service.
Enhancements:
- a general `knctl` task that would take any arguments as input (tektoncd/pipeline#207 is required for that **or** a wrapper like the one in `openshift-client` task)
- provide more parameters (`knctl deploy --help` has quite some :angel:)
- dig into [`knative/client`](https://github.com/knative/client) instead (or in addition to)
review them:
> Initial `knctl` task definition 🌮

- golang/README.md
- golang/build.yaml
- golang/lint.yaml
- golang/tests.yaml
Related to https://github.com/tektoncd/pipeline/pull/954 and https://github.com/tektoncd/pipeline/pull/949, this provides initial Tasks for Golang.
This adds initial golang tasks : build (`golang-build`), tests (`golang-tests`) and linting (`golangci-lint`, using golangci-lint).
Improvements (todos):
Closes tektoncd/pipeline#532
Closes tektoncd/pipeline#558
/cc @chmouel @bobcatfish 
review them:
> Initial golang tasks

- golang/README.md
- golang/lint.yaml
- Those url were not targeting the files, I renamed the files and forgot
to update the README.
- `GOOS` and `GOARCH` didn't have a correct default value for the lint task
- The README doc for build and test `flags` parameter were wrong
:bowing_man: 
/cc @bobcatfish @abayer @dlorenc 
review them:
> golang: few fixes

- argocd/README.md
- argocd/argocd.yaml
Created a `Task` that syncs (deploys) an Argo CD application. 
review them:
> New Task: Argo CD

- argocd/argocd.yaml
* PR fixes incorrect usage of environment variables (adds missing `$` in front of variables name ) in login step of argocd task.
* Additionally allows parameterizing argocd image version.
> Fix argocd incorrect usage of ARGOCD_USERNAME/ARGOCD_USERNAME in login

- buildpacks/README.md
- buildpacks/buildpacks-v3.yaml
Signed-off-by: Andrew Meyer <ameyer@pivotal.io>
review them:
> Update buildpacks-v3 template for latest lifecycle

- kn/README.md
- kn/kn-create.yaml
- kn/kn-deployer.yaml
Also define a sample ServiceAccount, ClusterRole and ClusterRoleBinding
that can be used to authorize Knative Service deployments.
Adds a new Task that uses [`kn`](https://github.com/knative/client) to create Knative services.
review them:
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
/assign @vdemeester 
-----
I think we'd probably like to rely on `kn` over `knctl` going forward since I …
> Add a new Task that uses `kn` to create services

- kubeval/README.md
- kubeval/kubeval.yaml
Kubeval is a tool used to validate Kubernetes configuration against
the upstream object schemas. This commit adds a `Task` spec for using
Kubeval from Tekton, along with documentation of the parameters and usage.
review them:
> Added task for Kubeval

- golang/README.md
- golang/build.yaml
- golang/lint.yaml
- golang/tests.yaml
Signed-off-by: jtcheng <jtcheng@alauda.io>
- Support to set GO11MODULE in `golangci-lint`, `golang-build`, `golang-test`
The default value of GO11MODULE is auto in golang.
We should allow to change the value, in order to force module support on or off regardless of directory location
review them:
> Support to set go11module in golang task

- conftest/README.md
- conftest/conftest.yaml
Conftest is a tool used to validate configuration files using Open
Policy Agent. This commit adds a `Task` spec for using Conftest from
Tekton, along with documentation of the parameters and usage.
review them:
> Added task for Conftest

- kn/kn-create.yaml
Fixes #73
`kn` apparently doesn't like flags passed with spaces, and prefers `--foo=bar` style (with `=`). The error message when you pass flags with a space is...confusing.
I've confirmed this change makes the kn-create Task successfully attempt to create the Service.
review them:
- [ n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ y ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
_See [the contribution guide(https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
> Fix kn-create Task to pass args in accepted manner

- openshift-client/Dockerfile
- openshift-client/README.md
- openshift-client/openshift-client-kubecfg-task.yaml
- openshift-client/openshift-client-task.yaml
- openshift-client/script.sh
This is breaking the backward compatibility, better release
a branch for 0.5 and then update the tasks
This change will fix the issue of client
task giving error on tekton 0.5.0
Also, tag the image with the pipeline version
in spite of always latest
Fix #78
review them:
> Revert 'remove script' and fix the Dockerfile

- argocd/argocd.yaml
We are currently using the latest release to run tests on
catalog. This means this fails with 0.7.0 and above.
`containerTemplate` is now `stepTemplate`.
/cc @abayer @ImJasonH @bobcatfish 
This is *why* I would like to tag catalog alongside the pipeline releases :angel: 
review them:
> Use stepTemplate instead of containerTemplate as it is now gone

- openshift-client/Dockerfile
We still need to keep the hack in there for origin until we sort it out
compatibility between ${} and $()
/cc @vdemeester 
/cc @piyush-garg
> Use quay.io/openshift/origin-cli instead of doing our own

- gcloud/README.md
- gcloud/gcloud.yaml
This Task simply wraps invocations of the `gcloud` CLI, which can be used to deploy code, spin up and tear down GKE clusters and VM instance pools, and looooots of other stuff.
Longer term, there should probably be specific Tasks just for common CI/CD workflows, like deploying to GKE/GCF/GAE/GCE, which can have a much better UX than just "what to tell `gcloud` to run". Those higher-level Tasks can also just wrap `gcloud`, or could call the underlying APIs. But this is an easy stopgap to at least enable `gcloud` invocations from Tekton.
review them:
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best …
> Add gcloud Task

- kn/README.md
Otherwise it produces an error:
```
unknown flag: --env TARGET
```
> There needs to be an equals after the --env

- buildah/README.md
- buildah/buildah.yaml
Closes #118 
Tagging default image used as `v1.11.0` to prevent breaking changes that may be introduced by `latest` tag.
review them:
> Tag Default Buildah Image as v1.11.0

- conftest/conftest.yaml
Although this appears to be the default I just started seeing errors:
```
invalid input params: param types don't match the user-specified type: [files]
```
with the following params:
```
params:
- name: files
value: Pipfile
```
Explicitly setting the type resolves this issue so doing that for now. I'm going to investigate further.
review them:
> Be explicit about files being a string

- DEVELOPMENT.md
- buildah/tests/pre-apply-task-hook.sh
- buildah/tests/resources.yaml
- buildah/tests/run.yaml
- jib-maven/jib-maven.yaml
- jib-maven/tests/pre-apply-task-hook.sh
- jib-maven/tests/resources.yaml
- jib-maven/tests/run.yaml
- kaniko/kaniko.yaml
- kaniko/tests/pre-apply-task-hook.sh
- kaniko/tests/resources.yaml
- kaniko/tests/run.yaml
- s2i/tests/pre-apply-task-hook.sh
- s2i/tests/resources.yaml
- s2i/tests/run.yaml
- test/e2e-tests.sh
We are adding a directory with in each tasks with its run, resources and
hooks. 
There is a hook system which allows to do some manipulation on task for the
tests (as we don't want to modify the main task). Or if we want to do some extra
pre-setup before setting the taskrun
For example on buildah/kaniko/jib would add a registry as a sidecontainers on
the tasks so we can do our testings without having to upload it somewhere.
S2I is disabled too due of not working on other cluster than openshift.
Closes: #103
> Add Taskrun e2e testing

- OWNERS
Chmouel has done tons of contributions to the catalog (see
[here](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=tektoncd%2Fcatalog&var-country_name=All))
and started working on the e2e tests.
/cc @ImJasonH @sbwsg @dlorenc 
review them:
> Add @chmouel as an OWNER

- kaniko/kaniko.yaml
As of today, kaniko assumes it is running as root, which means, this
example fails on platform that default to run containers as random
uid (like OpenShift). Adding this securityContext make it explicit that
it needs to run as root.
review them:
> Add securityContext to run as root for kaniko task 🤖

- s2i/Dockerfile
When building the dockerfile we were creating directory as root
unreadable by normal user, let's make sure it's readable/executable by
everyone.
/cc @sthaha
review them:
> Fix running s2i binary as user

- kaniko/kaniko.yaml
Hi all,
Right now, the kaniko builder image is hard code in the steps.
As other build tasks (As buildpacks an example: https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml#L8), it is better to extract the build image as a common parameter `BUILDER_IMAGE` so that users can set it by themselves.
Please review. Thanks!
review them:
> Extract the builder image as a common parameter

- tkn/README.md
- tkn/tkn.yaml
Adds a Task to the catalog for the [Tekton CLI](https://github.com/tektoncd/cli).
Fixes #154
review them:
> Add tkn to catalog.

- azure-cli/README.md
- azure-cli/azure_cli.yaml
Closes #147 
This pull request adds a task to execute azure cli (`az`) commands. It uses the [official Microsoft Azure CLI image](https://hub.docker.com/_/microsoft-azure-cli). The default image used is `mcr.microsoft.com/azure-cli:2.0.77`, which is the most recent release of `az`.
Future work on this task will be centered around documenting best authentication approaches using `az` from a task.
> Azure CLI Task

- kn/README.md
- kn/knative-dockerfile-deploy/README.md
- kn/knative-dockerfile-deploy/build_deploy/README.md
- kn/knative-dockerfile-deploy/build_deploy/build_deploy_pipeline.yaml
- kn/knative-dockerfile-deploy/build_deploy/pipeline_run.yaml
- kn/knative-dockerfile-deploy/build_deploy/resources.yaml
- kn/knative-dockerfile-deploy/kn_deployer.yaml
- kn/knative-dockerfile-deploy/service_traffic/README.md
- kn/knative-dockerfile-deploy/service_traffic/kn_service_traffic_splitting_pipeline.yaml
- kn/knative-dockerfile-deploy/service_traffic/pipeline_run.yaml
- kn/knative-dockerfile-deploy/service_update/README.md
- kn/knative-dockerfile-deploy/service_update/kn_service_update_pipeline.yaml
- kn/knative-dockerfile-deploy/service_update/pipeline_run.yaml
- kn/knative-dockerfile-deploy/service_update/resources.yaml
- Uses `buildah` task for Dockerfile-source at git to build and push
- Uses `kn` task to deploy as Knative Service
- Documents creating `docker-registry` type secrets, for push/pull
- Documents configuring `ServiceAccount` for deploying ksvc and linking the secrets to it
- Adds Pipelines for updating a ksvc as well as performing some traffic operations
- Links the example Pipelines from kn task README
review them:
> Add Dockerfile-source to Knative Service Pipelines

- azure-cli/README.md
- azure-cli/azure_cli.yaml
- tkn/README.md
This pull request introduces the following changes:
* Updates the default image for the azure-cli task to the latest version of `az`, which is 2.0.78
* Removes the default for `ARGS` parameter, making it a required parameter
* Updates the `tkn` task README to reflect that `ARGS` does not have a default and is required
review them:
> Remove Default for ARGS and Update Image Tag to 2.0.78 for Azure CLI

- openwhisk/openwhisk.yaml
When using the latest Tekton pipeline version. It reports an error when executing this task:
`bash: line 15: OW_ACTION_CODE: command not found`
It because this line: `              ENV __OW_ACTION_CODE "$(OW_ACTION_CODE)"`
When running this code, bash thinks it is a command not a variable.
So change it to `ENV __OW_ACTION_CODE "${OW_ACTION_CODE}"`
Then the task can be run correctly
Pls review
review them:
> Change to ${OW_ACTION_CODE} for new Tekton version

- kaniko/kaniko.yaml
Follow the change in `pipeline`, change docker credential path to `/tekton/home/.docker`
review them:
> Correct credential path of docker

- gcloud/README.md
- kn/README.md
- openwhisk/runtimes/javascript/README.md
- openwhisk/runtimes/javascript/examples/01-helloworld/taskrun-helloworld.yaml.tmpl
- openwhisk/runtimes/javascript/examples/02-json-in-json-out/taskrun-helloworld-with-params.yaml.tmpl
- openwhisk/runtimes/javascript/examples/03-github/taskrun-raw-github.yaml.tmpl
- openwhisk/runtimes/javascript/examples/04-zip/taskrun-zip.yaml.tmpl
- s2i/README.md
- test/presubmit-tests.sh
`serviceAccount` is deprecated and now invalid (starting from 0.9.0),
so removing it from the examples.
/cc @afrittoli @chmouel @bobcatfish @ImJasonH 
review them:
> Use serviceAccountName instead of serviceAccount 💺

- github/README.md
- github/add_comment.yaml
- github/set_status.yaml
Add a github directory with for now only two tasks (more to follow)  allowing to do
different github actions with the API.
I have made those tasks in _pure_ python to be able to use a minimal image and
not have to build one with `hub` or other tools.
The `github-set-status` task allows external services to mark GtiHUB commits
with an `error`, `failure`, `pending`, or `success` state, which is then
reflected in pull requests involving those commits.
The `github-set-status` task allows external services to mark GtiHUB commits
with an `error`, `failure`, `pending`, or `success` state, which is then
reflected in pull requests involving those commits.
The `github-add-comment` task let you add a comment to a pull request or an
xissue.
These are the criteria that every PR should meet, please …
> Add Github set-status and add-comment tasks

- openshift-client/README.md
- openshift-client/openshift-client-kubecfg-task.yaml
- openshift-client/openshift-client-task.yaml
This will update openshift-client to be used in script mode
This will help to pass multiple commands or parametrized
commands in a single taskrun
review them:
> Update openshift client task to use script mode

- git/README.md
- git/fetch-git.yaml
This is part of documenting and providing Tasks in the catalog that
would help user not using PipelineResource.
Related to [tektoncd/pipeline#1369](https://github.com/tektoncd/pipeline/issues/1369).
Part of #95 
review them:
> Add a git task to clone a repository without PipelineResource

- git/git-clone.yaml
I accidentally missed passing these two params to the flags of git-init.
This PR passes the params as expected.
review them:
> git-clone: Pass depth and sslVerify params to args

- kn/kn.yaml
- Use `latest` tag for kn image at https://gcr.io/knative-releases/knative.dev/client/cmd/kn
which points to the latest released version of kn.
- User can still parameterize the kn image to use, for example nightly build of kn image
at https://gcr.io/knative-nightly/knative.dev/client/cmd/kn:latest
review them:
> Default kn image to the latest released version

- DEVELOPMENT.md
- jib-gradle/README.md
- jib-gradle/jib-gradle.yaml
- jib-gradle/tests/pre-apply-task-hook.sh
- jib-gradle/tests/resources.yaml
- jib-gradle/tests/run.yaml
- jib-maven/jib-maven.yaml
Add Jib Gradle catalog / fix Docker config issue for Jib Maven
- Add Jib Gradle catalog: counterpart of Jib Maven.
- Change the user home inside JVM from `/builder/home` to `/tekton/home` in Jib Maven
- See: https://github.com/tektoncd/pipeline/issues/2013#issuecomment-585908031
- Run Jib Maven in batch mode (`mvn -B ...`)
(@GoogleContainerTools/java-tools-build FYI)
review them:
> Add Jib Gradle catalog / fix Docker config issue for Jib Maven

- jib-gradle/jib-gradle.yaml
This wil fix the issue jib gradle task
gettng failed on security constrained
environments like OpenShift
Fix #198
review them:
> Fix jib-gradle task

- buildpacks/buildpacks-v3.yaml
This will change to run the prepare step of buildpack
as priviledged because it is failing on security constraint
platform like OpenShift
Fix #197 
review them:
> Run prepare of buildpack as privileged

- jib-gradle/OWNERS
- jib-maven/OWNERS
Add OWNERS to jib catalog entries (https://github.com/GoogleContainerTools/jib)
With guidance from @bobcatfish
> Create OWNERS from jib team

- jib-gradle/jib-gradle.yaml
@piyush-garg @hrishin 
Reverting the Gradle home change introduced in #199.
As explained in #199, the change is in conflict with `-Dgradle.user.home=/tekton/home/.gradle`, and this actually breaks caching. I am certain that changing the Gradle home is not the right solution for #198.
@piyush-garg @hrishin I do not know what exactly the "security constraint" issue, but we should implement a proper fix after understanding the issue. Please reopen #198.
review them:
> Don't change Gradle home in jib-gradle

- git/README.md
- git/git-clone.yaml
An implementation detail of the git-clone task in the catalog: it fails
if the directory it's cloning into is already a git repo. This behaviour
has been carried over from the GitResource. Prior to this commit the
advice for users was to manually delete the directory themselves before
running this Task.
This PR introduces a param that, when set to "true", will empty the
directory of any files and folders before performing the clone.
review them:
> Add a delete param to the git-clone task for reusing PVCs

- README.md
We don't have a `bazel` task in the catalog. Switch to use
`golang-build` with `tektoncd/pipeline` as source.
/cc @sbwsg @chmouel @bobcatfish 
review them:
> Use golang instead of bazel in catalog README 📎

- jib-gradle/jib-gradle.yaml
This will fix the issue of task not
working on OpenShift as it needs root access and
by default on OpenShift pod run as nonroot
Fix #198 
review them:
> Run jib-gradle as root

- pullrequest/pr.yaml
The pull request image was updated in v0.11.0-rc2, update it here
too for consistency.
review them:
> Update the pullrequest image

- github/README.md
- github/add_comment.yaml
- github/close_issue.yaml
- github/set_status.yaml
Three changes.
1. Add API_PATH_PREFIX parameter to each task. The Github Enterprise has `/api/v3` prefix between the host URL and the API path.
1. Correct github secret name in the README
1. Add `type: string` to all parameter definition.  This is not always necessary but useful sometimes.
review them:
> Github Enterprise support for github tasks

- git/README.md
The version of the `git-clone` task on the master branch of the catalog is only compatible with 0.11-rc1 and above because I modified it to start using Task Results.  We've got stuff in the works related to versioning of the catalog but at the very least this version info should be documented.
This PR adds version information to the README so that at least we have this documented somewhere.
review them:
> Add Pipelines version info to the git-clone README

- test/e2e-tests.sh
Otherwise, 0.10.2 is picked up, and `v1beta1` is not present…
/cc @chmouel @afrittoli 
review them:
> Force using v0.11.0-rc2 yaml for the v1beta1 branch

- openshift-client/openshift-client-task.yaml
Fixes #239
Signed-off-by: Kamesh Sampath <ksampath@redhat.com>
Added optional input resource could be used when need to apply manifest from sources
review them:
- [x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
> Add optional input resource of type git

- buildah/README.md
- buildah/buildah.yaml
- buildah/tests/resources.yaml
- buildah/tests/run.yaml
- kaniko/README.md
- kaniko/kaniko.yaml
- kaniko/tests/resources.yaml
- kaniko/tests/run.yaml
This starts the work on using `params` for specifying the image reference, and result (when supported) to store the digest.
The `kaniko` is an example with the `results`.
Depends on tektoncd/pipeline#2212
review them:
> Port ImageResource to params and results

- maven/README.md
- maven/maven.yaml
- maven/tests/run.yaml
Earlier settings.xml used to get created but wasn't consumed by maven during the runtime.
Now after the fix, if we provide wrong configuration in the parameters, the maven goals
fail. Also improved the script in maven-settings Task Step.
Ref: #158 
review them:
> Fix script in Maven Task and settings.xml mounting

- maven/README.md
The word 'run' exists twice in line 21 of maven/README.md
This commit removes one of them
review them:
> Remove duplicate word from maven/README

- README.md
- roadmap.md
In https://github.com/tektoncd/community/pull/77 we started on a roadmap
for 2020 for all of Tekton but folks pointed out it makes more sense to
let each project's own roadmap live in the repo with them.
review them:
> Add 2020 roadmap 🛣️

- gcs/README.md
- gcs/gcs-create-bucket.yaml
- gcs/gcs-delete-bucket.yaml
- gcs/gcs-download.yaml
- gcs/gcs-upload.yaml
We are providing tasks that mimic the behaviour of our existing
PipelineResources as part of the beta.
This Commit introduces two tasks to replace the GCS PipelineResource:
1. gcs-download fetches files and directories from GCS
2. gcs-upload uploads file and directories to GCS
Each of these tasks accepts a workspace for credentials that should
contain the service account json key and a workspace to download
onto or to upload from.
Additionally, two other Tasks are added here to help support testing
of the two above:
1. gcs-create-bucket creates a new GCS bucket
2. gcs-delete-bucket deletes a GCS bucket
As above credentials are provided via a credentials workspace.
review them: …
> Add GCS Tasks to replace the GCS PipelineResources

- CONTRIBUTING.md
- test/e2e-common.sh
Allow test Taskruns 
We were only running the PipelineRuns type of test but let allow the Taskruns too
review them:
- [?] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
> Handle TaskRun as well as PipelineRun tests

- buildpacks/README.md
- buildpacks/buildpacks-v3.yaml
- buildpacks/tests/run.yaml
This change makes it so that the tekton task is compatible with
the latest changes from the Cloud Native Buildpacks.
Notably,
- Support for cred helpers has been removed. ([#259](https://github.com/buildpacks/lifecycle/pull/259))
- Default process type is configurable. ([#243](https://github.com/buildpacks/lifecycle/pull/260))
Resolves #194
review them:
> Update buildpacks task platform API to 0.3

- kubectl/README.md
- kubectl/clusterrolebinding.yaml
- kubectl/kubectl-deploy.yaml
- kubectl/taskrun.yaml
Use a image with `kubectl` installed, we can setup `step` of `task` in tekton to create arbitrary rsource of kubernates.
review them:
> Add Kubectl example

- git/git-clone.yaml
fixes #275
Use flag=val for bool and int flags passed to git-init
review them:
> git-clone: fix git-init flags

- kubectl/README.md
- kubectl/clusterrolebinding.yaml
- kubectl/kubectl-deploy.yaml
- kubectl/taskrun.yaml
Fix issue: #233 , Porting from `v1alpha1`
Use a image with `kubectl` installed, we can setup `step` of `task` in tekton to create arbitrary rsource of kubernates.
review them:
> Add Kubectl sample, porting from version "v1alpha1"

- gcs/sample/gcs-sample.yaml
Tasks in the catalog don't currently have a uniform approach to testing. It would be good if the catalog provided some kind of blessed path and supporting infrastructure so that Tasks can be exercised as part of PRs.
This commit includes a test for the GCS tasks that utilizes triggers to kick off a pipelinerun. There are still some decisions to be made around how service account generation might work, how the needed infra gets spun up, and how the triggers get _triggered_ in the first place, but this demonstrates the general idea.
author: @bobcatfish 
coauthor: @sbwsg
review them:
> Test GCS Tasks

- git/git-clone.yaml
One of the disadvantages of using a binary built from tekton's repo as the image
of a catalog task is that changes to the binary may introduce or remove behaviour
that don't then get added or removed in the catalog task.
The git-init binary is getting a new flag, `-refspec`, that won't be available until
we cut the next pipelines release. If we use the ":latest" image tag then this flag
will silently get added to git-clone tasks but there won't be params or docs
associated with it in the catalog.
I think it would be much better if we could add this change
immediately in the `git-clone` task, independently of `git-init` in pipelines. For the time being let's pin the version of the `git-init` image used and then add the feature explicitly to the git-clone task when the new version of …
> Pin git-clone to the 0.11.0 version of git-init

- git/git-clone.yaml
(cherry picked from commit d5bf0f75112f524c3cf2125c4544b5631979723f)
This PR cherry-picks a bug fix from the master branch to the v1beta1 branch.  The `ls -lah` that used to appear in the git-clone Task could cause errors.
review them:
> the removed line fails if a checkout hasn't yet happened

- replace-tokens/README.md
- replace-tokens/replace-tokens.yaml
- replace-tokens/tests/configmap.yaml
- replace-tokens/tests/pre-apply-task-hook.sh
- replace-tokens/tests/resource.yaml
- replace-tokens/tests/run.yaml
The Replace Tokens task can be used to replace the tokens in a `JSON` or `YAML` file. Provided there is a config.json or a yaml file in a git repository which contains some secret tokens can be replaced during a TaskRun by providing a tokens.json or tokens.yaml file as a part of ConfigMap. 
Link to the source code of the replace tokens :- https://github.com/vinamra28/replace-tokens-plugin
Authors: @Divyansh42 @vinamra28 
review them:
> Add Replace Tokens Task

- git/README.md
- git/git-clone.yaml
I tried to use this Task to replace use of a git PipelineResource and
was really stumped for a while because I didn't realize that my code was
checked out by default into a directory called "src" in the workspace. I
think it makes sense to let folks specify a subdir if they want it but
I'm not sure that "src" is an intuitive default so this commit removes
it.
review them:
> Remove default git Task subdir 📁

- kaniko/README.md
- kaniko/kaniko.yaml
- kaniko/tests/run.yaml
Fixes #285 
* Fixes kaniko.yaml as described in the issue.
* Updates the e2e test to test that the digest result is working.
review them:
> Fix image digest result in kaniko task

- kubeconfig-creator/README.md
- kubeconfig-creator/example/pers-vol.yaml
- kubeconfig-creator/example/pipeline.yaml
- kubeconfig-creator/example/pipelinerun.yaml
- kubeconfig-creator/example/test-task.yaml
- kubeconfig-creator/kubeconfig-creator.yaml
This is a part of documenting and providing task in the catalog that would help user not using PipelineResource for accesing the target cluster.
This task will be help in creating the `kubeconfig` file by providing the required cluster `credentials` to the task as a `param`.
Ref:#95
review them:
> Add a kubeconfig-creator Task to access cluster

- openshift-client-python/Dockerfile
- openshift-client-python/README.md
- openshift-client-python/openshift-client-python.yaml
The following task can be used to interact with the openshift cluster via `oc` commands in a python script.
The set of possible scripts can be found in the docs [here](https://github.com/openshift/openshift-client-python/blob/master/README.md#usage). 
The `Dockerfile` is there as a part of PR which consists of the `openshift-cli` binary and `python` binary
review them:
> Add OpenShift Client Python task

- test/e2e-common.sh
TLDR; See #301 for a PR where the test runner quits straight away on a test
because it takes a little bit of time for the test TaskRun to appear in the `kubectl
get` output. This PR reattempts the `kubectl get` repeatedly for up to ten
minutes.
Long version:
Immediately after our test runner submits test TaskRuns / PipelineRuns
it checks that those Runs appear in `kubectl get` output. In a recent
PR to add a kythe-go Task (#301) the test runner would fail at this
point. Checking locally I was able to reproduce the issue. It looks
like it can take a small amount of time for submitted resources to
show up in `kubectl get` output.
For other types of test failures the test runner gives a grace period of
up to ten minutes. I did the same for the `kubectl get` check, allowing
the test run loop …
> Give test Runs time to appear in `kubectl get` lists

- git/README.md
- git/git-batch-merge.yaml
- git/tests/run.yaml
Add refspec support to git task corresponding to https://github.com/tektoncd/pipeline/pull/2320
Add a new batch merge task (https://github.com/tektoncd/pipeline/issues/508) that re-uses
the git-init container and subsequently performs the requested batch merge mode on top of
the checked out revision
review them:
- [?] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
> Add batch merge and refspec support to git task

- kaniko/README.md
- kaniko/kaniko.yaml
I tried to use the kaniko task to update the build + deploy pipelinerun
example in the pipelines repo and run into some trouble which I have
fixed here:
- The jq parsing of the digest from the imagedigestexporter output
wasn't quite right, the name of the field was incorrect and it was
surrounded by quotes (removed with -r) and followed by a newline
(removed with -j)
- If the kaniko Task was used more than once with the same workspace,
even if it was building from different directories, the digests would
conflict b/c it was always writing to the same files. Now the files it
writes to are relative to the context the image is alreayd using to
build
I've also extended the test so that it both verifies that a digest is
parsed.
These are the criteria that every PR should meet, please check …
> Fix kaniko digest results 🔧

- buildah/buildah.yaml
See discussion in https://github.com/tektoncd/catalog/issues/265. Although using
layer caching in the buildah build would be nice, there are two prerequisites:
* A PVC to store the cache between pipeline runs
* A fix for https://github.com/containers/buildah/issues/2215
The buildah issue is that buildah uses file timestamps to invalidate the cache. Locally, this works well, but in a CI/CD the files will always be freshly downloaded from source control, so they will be newer than the cache. This means the cache would never be used, even if it was available in a PVC. 
review them:
- [ n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x ] Commit …
> Do not use layers in buildah task, since layer caching depends on timestamps (unreliable in a CI/CD

- buildah/buildah.yaml
The Buildah task does not have a task result. Tasks executing after this task is interested in the resulting image-digest. This commit adds the pushed image-digest as a task result, very similar to the task result in the Kaniko task.
review them:
> Add image-digest as Result in Buildah task

- test/e2e-tests.sh
We've been using Pipelines 0.11.0-rc2 for e2e tests but that's now several months old and there are features in 0.12+ that we can expect to appear in Catalog Tasks and their Tests.  Here's an example of a PR that relies on 0.12 features (volumeClaimTemplate) as part of the tests it runs: https://github.com/tektoncd/catalog/pull/321
This commit attempts to update the version of Tekton used for e2e tests.
review them:
> Update to Pipelines 0.12.1 for e2e tests

- git/README.md
By default git-clone now checks out a repo directly into the root
of the provided workspace. The README still states in one spot that
it checks out to the "src" subdirectory by default but this is no longer true.
This commit updates the content of the README to correctly reflect
the fact that git-clone checks out directly into the workspace's root.
(We updated the default subdirectory here: https://github.com/tektoncd/catalog/pull/290)
review them:
> Correct subdirectory error in git-clone's README

- git/README.md
- git/git-clone.yaml
Adding httpsProxy, httpProxy, and noProxy in git-clone task.
Originally added here: https://github.com/tektoncd/catalog/pull/231 and now being cherry-picked into the v1beta1 branch.
(cherry picked from commit 13037cbd0d8131dd05fe2eae92e8a5156807ff5c)
review them:
> (master -> v1beta1) adding proxy settings to git-clone

- git/git-batch-merge.yaml
- git/git-clone.yaml
This will bump git-init image to 0.12.1 which is
latest
This will probably fix #312 and #297
review them:
> Bump git-init image to 0.12.1

- buildah/buildah.yaml
In some case we want to use different storage driver than overlay, let's allow
this.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [-] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [-] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
> Allow define storage driver for buildah

- kubectl/README.md
- kubectl/clusterrole.yaml
- kubectl/clusterrolebinding.yaml
To binding `cluster-admin` to SA default/default without warning user will introduce some potential security issue, so:
1. Make it clearer to users that this is only intended for insecure/non-critical use cases, and should be modified after installation to match the user's use case and needs, and/or
2. Provide a more scoped-down role binding initially, which users can add to as they need.
review them:
> Add "ClusterRole" to aviod binding "cluster-admin"

- kn/kn.yaml
- kn/knative-dockerfile-deploy/README.md
- kn/knative-dockerfile-deploy/build_deploy/README.md
- kn/knative-dockerfile-deploy/build_deploy/build_deploy_pipeline.yaml
- kn/knative-dockerfile-deploy/build_deploy/pipeline_run.yaml
- kn/knative-dockerfile-deploy/build_deploy/resources.yaml
- kn/knative-dockerfile-deploy/service_traffic/README.md
- kn/knative-dockerfile-deploy/service_traffic/kn_service_traffic_splitting_pipeline.yaml
- kn/knative-dockerfile-deploy/service_traffic/pipeline_run.yaml
- kn/knative-dockerfile-deploy/service_update/README.md
- kn/knative-dockerfile-deploy/service_update/kn_service_update_pipeline.yaml
- kn/knative-dockerfile-deploy/service_update/pipeline_run.yaml
- kn/knative-dockerfile-deploy/service_update/resources.yaml
According to https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md#replacing-pipelineresources-with-tasks the PipelineResources stay at alpha version. This PR moves the `kn` task to using Tasks instead of PipelineResources where sources and images are shared between tasks rather than through the PipelineResources custom resource. This is a more straightforward approach which can be seen on the number of lines added vs. removed in this PR.
This also fixes documentation for the `kn` task - fix links to us v1beta1, fix some typos, update examples to use v1beta1.
review them:
for more …
> Migrate away from PipelineResources in kn task

- git/README.md
- git/examples/git-clone-checking-out-a-branch.yaml
- git/examples/git-clone-checking-out-a-commit.yaml
- git/examples/using-git-clone-result.yaml
Fixes https://github.com/tektoncd/catalog/issues/320
The git-clone example only demonstrated the very simplest of behaviour and didn't provide much in the way of instruction on using its features.
This PR adds examples for cloning a branch, cloning a specific commit, and cloning tags. Each example includes clear description of its purpose and the features it demonstrates.
I've removed the inline git-clone example from the README because it's really long and the
README needs to serve the purpose of documenting multiple Tasks (git-clone as well as git-batch-merge, and any future Tasks we add as well). Rather than bloat the README with many examples which can go stale if we modify git-clone's behaviour I've simply linked to the new example files.
These are the criteria that every PR should …
> Improve examples for the git-clone Task

- gitlab/README.md
- gitlab/add-labels.yaml
Current task only support adding labels to Gitlab `issue` and doesn't have support for `merge requests`. Added support for merge requests in the same task.
Now we can add labels to `merge requests` as well.
review them:
> Add support for merge requests in GitLab add-labels task

- test/e2e-common.sh
Test would be failing if there is a directory but no yaml template in there,
which in reality we should not have this happening but it happens sometime.
let's make sure we skip the test if there is no yaml files then.
review them:
> Make sure we skip the test if there is no yaml file in there

- python/publish-package/README.md
- python/publish-package/example/run.yaml
- python/publish-package/tests/pre-apply-task-hook.sh
- python/publish-package/tests/run.yaml
- python/publish-package/update-pypi.yaml
The task to publish a python module to PyPI.
Python module can be published through CI/CD pipeline using this Tekton Task.
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
This Task publishes python packages to the PyPI index using [Twine](https://pypi.org/project/twine/) utility module. It provides build system independent uploads of source and binary distribution artifacts for both new and existing projects.
review them:
> Task to publish python module to PyPI

- kythe/README.md
- kythe/kythe-go.yaml
- kythe/tests/run.yaml
This is a cherry-pick of https://github.com/tektoncd/catalog/pull/284 into the v1beta1 branch. During the window where catalog's default branch was switched from `master` to `v1beta1` it's possible that some PRs were merged to master but not to v1beta1.  This appears to be one of those, so I'm pulling it across here.
Description from the original PR:
This task allows you to generate Kythe annotation metadata for a given
Go project. This follows the workspace model as presented by the `git`
Task. The expectation is that any results place in the workspace will be
exported by another Task in the pipeline for remote storage (e.g. GCS,
etc).
(cherry picked from commit 20d449cd435e12b902595d91d785da4d168939ad)
review …
> (master -> v1beta1) Add Kythe golang extractor task.

- test/e2e-common.sh
The loop in the test runner script that was waiting for all TaskRuns to
complete had a bug where it would break out of the loop as soon as any one of
the TaskRuns completed. The test runner then tries to print the logs for all
TaskRuns (which includes some Running ones) which will sometimes fail e.g. if
the TaskRun's pod is in a PodInitializing state.
/kind bug
review them:
> Wait until all TaskRuns are complete to print logs

- test/e2e-common.sh
This can grow the log pretty big with message that we probably don't care
about.
when we show the logs on failure, make sure we are not failing if we can't show
them. Sometime some container may be in "Terminated" state until k8 cleans them
up. (i.e: affinity-assistant) so no need to worry if those are failing/exiting before
showing the next container log.
review them:
> test-runner: Do not show logs on success

- buildah/README.md
- buildkit-daemonless/README.md
- buildkit/README.md
- conftest/README.md
- golang/README.md
- helm/README.md
- jib-gradle/README.md
- jib-maven/README.md
- kaniko/README.md
- kubeval/README.md
- makisu/README.md
- python/publish-package/README.md
- s2i/README.md
- terraform-cli/README.md
The tasks in this commit were updated at some point to use workspaces instead of
pipeline resources but their readmes still refer to the resources.
This commit updates the readmes to remove mention of pipeline resources and link
out to pipeline's workspaces doc.
review them:
> Update READMEs of tasks using workspaces in place of PipelineResources

- buildah/README.md
- buildah/buildah.yaml
This adds two extra optional parameters which allow passing extra args to build when it's building and pushing images.
For example:
- name: BUILD_EXTRA_ARGS
value: "--label=test=yes --label=other=label --label=this=too"
Would add  three additional labels to the pushed image
review them:
> Add support for passing extra args to the buildah commands.

- task/buildah/0.1/README.md
- task/buildkit-daemonless/0.1/README.md
- task/buildkit/0.1/README.md
- task/conftest/0.1/README.md
- task/golang-build/0.1/README.md
- task/golang-test/0.1/README.md
- task/golangci-lint/0.1/README.md
- task/helm-conftest/0.1/README.md
- task/helm-upgrade-from-source/0.1/README.md
- task/jib-gradle/0.1/README.md
- task/jib-maven/0.1/README.md
- task/kaniko/0.1/README.md
- task/kubeval/0.1/README.md
- task/makisu/0.1/README.md
- task/s2i/0.1/README.md
- task/terraform-cli/0.1/README.md
- task/upload-pypi/0.1/README.md
We don't really have a concept in Tekton of something called a "Workspace volume",
but multiple READMEs now refer to it.
This commit removes the term "Workspace volume" in favor of simply "Workspace".
review them:
> Remove word "volume" from "Workspace volume" in READMEs

- task/skopeo-copy/0.1/skopeo-copy.yaml
Since skopeo has started providing their official image and the image would be updated regularly so changing the skopeo-copy task image so that it can use the official one from now on.
review them:
```
spec:
```
---
> Bump skopeo image to point to the official one

- task/kubectl-deploy-pod/0.1/README.md
The URL for applying the `kubectl-deploy-pod` task was incorrect in the README. This PR fixes the URL.
review them:
---
> updating raw Task URL in kubectl-deploy-pod readme

- test/e2e-common.sh
This will change the scripts to use python3
review them:
```
spec:
```
---
> Use python3

- task/kubernetes-actions/0.1/README.md
- task/kubernetes-actions/0.1/kubernetes-actions.yaml
- task/kubernetes-actions/0.1/samples/kubectl-actions-run.yaml
- task/kubernetes-actions/0.1/samples/update-deployment-image-taskrun.yaml
The task `kubectl-actions` is a generic task which can be used to perform k8s-actions. We take the whole script as a `params` whereas the existing task `kubectl-deploy` only works for deploying the pod and fulfills the specific criteria https://github.com/tektoncd/catalog/issues/233
The following PR also contains a task which can be used to patch image deployment as a part of example.
review them:
```
spec:
```
---
[TEP]: …
> Add kubernetes actions task in `kubectl`

- task/jib-gradle/0.1/README.md
- task/jib-gradle/0.1/jib-gradle.yaml
- task/jib-maven/0.1/README.md
- task/jib-maven/0.1/jib-maven.yaml
@sbwsg
As Tekton prepares for `/tekton/home` deprecation (with the `disable-home-env-overwrite` and `disable-working-directory-overwrite` switches), these changes make `jib-gradle` and `jib-maven` tasks compatible with the current Tekton release and future releases that will flip the switches.
- Set `$HOME` env to `/workspace` at the Task level. (Luckily, this works even if `disable-home-env-overwrite=false`.)
- Use `$HOME` for accessing the home directory wherever possible
- Gradle: mount empty dir volume at `$HOME/.gradle` to make it globally writable (context: https://github.com/tektoncd/pipeline/issues/2165#issuecomment-655578620)
- Maven: switch from `command:` to `script:` to use `$HOME` variable
I've verified these work before and after flipping the deprecation switches.
These are …
> Make jib-gradle and jib-maven future-proof regarding Tekton $HOME deprecation

- task/pylint/0.1/README.md
- task/pylint/0.1/pylint.yaml
- task/pylint/0.1/tests/pre-apply-task-hook.sh
- task/pylint/0.1/tests/resources.yaml
- task/pylint/0.1/tests/run.yaml
- task/pytest/0.1/README.md
- task/pytest/0.1/pytest.yaml
- task/pytest/0.1/tests/pre-apply-task-hook.sh
- task/pytest/0.1/tests/resources.yaml
- task/pytest/0.1/tests/run.yaml
The Tasks can be used to run linting based on the module `pylint` and to execute unit-tests based on the module `pytest`. This is described in issue #364.
The Tasks are based on the official [Python image](https://hub.docker.com/_/python) and therefore the image tags can be used. The installation of `pylint` and `pytest` is done during the task to ensure the possibility to pin the version by using a requirements file.
review them:
```
spec:
```
---
[TEP]: …
> Add pylint and pytest task

- task/kythe-go/0.1/kythe-go.yaml
- task/kythe-go/0.1/tests/run.yaml
This will fix the task to run on restricted environments
as this task do some chown operations and fails on
environments like opneshift
review them:
```
spec:
```
---
> Fix kythe-go task on restricted environment

- task/buildpacks-phases/0.1/README.md
- task/buildpacks-phases/0.1/buildpacks-phases.yaml
- Override /tekton/home for the detect and build phases of the lifecycle to hide registry credentials from buildpack code.
- Run analyze, restore, and export in the lifecycle image published by buildpacksio to hide registry credentials from untrusted builders.
Signed-off-by: Natalie Arellano <narellano@vmware.com>
review them:
```
spec:
```
---
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/ …
> Introduce better security for buildpacks-phases task

- task/gke-cluster-create/0.1/README.md
- task/gke-cluster-create/0.1/gke-cluster-create.yaml
- task/gke-cluster-create/0.1/samples/create-gke-cluster.yaml
- task/gke-cluster-create/OWNERS
As part of #373 I'm continuing to create Tasks that we can use to run
tests for items in the catalog. This Task creates a cluster within a GKE
project and is based on the way we create clusters for the existing end
to end tests we have in Tekton, which are themselves based on Knative,
when are THEMselves based on k8s. These tests all use a tool called
kubetest, which is responsible for invoking boskos (see #408) and
creating a GKE cluster
(https://github.com/kubernetes/test-infra/tree/master/kubetest).
This Task attempts to create a cluster in the same way, which based on the
output in the end to end logs seems to consist of creating the cluster
and setting up a firewall for it.
I'm not sure if this belongs in the catalog itself since it is specific
to our own end to end tests and isn't …
> Add a task for creating a GKE cluster for e2e tests 🧪

- task/remote-ssh-commands/0.1/README.md
- task/remote-ssh-commands/0.1/remote-ssh-commands.yaml
- task/remote-ssh-commands/0.1/samples/run.yaml
- task/remote-ssh-commands/0.1/samples/secrets.yaml
The following task can be used to run the shell command (single/multiple) on remote Host by SSHing into the remote machine by providing the required credentials required to login into that Host and get back the result as output.
Tests are not provided in the PR as this task requires a remote Host along with credentials. So I have tested this task on my machine and included a sample in the README.
review them:
```
spec:
```
---
[TEP]: …
> Add task which can run shell commands on remote Host

- task/boskos-acquire/0.1/README.md
- task/boskos-acquire/0.1/boskos-acquire.yaml
- task/boskos-acquire/0.1/samples/pipelinerun.yaml
- task/boskos-acquire/0.1/samples/service-account.yaml
- task/boskos-acquire/OWNERS
- task/boskos-release/0.1/README.md
- task/boskos-release/0.1/boskos-release.yaml
- task/boskos-release/0.1/samples/pipelinerun.yaml
- task/boskos-release/0.1/samples/service-account.yaml
- task/boskos-release/OWNERS
Boskos is a tool that allows one to create a pool of cloud projects
(definitely GCP, I think it supports other providers as well), and
manages acquiring, releasing, and cleaning them between leases.
We use it for Tekton test infrastructure for our end to end tests and
we'd like to use it for our catalog Tasks as well.
This commit adds boskos acquire and release Tasks.
The acquire Task also creates a pod in the running cluster to perform
heartbeating so that boskos knows that the resource is still in use.
(Lemme know if you have a better idea for making this work! I have this
slightly crazy idea that Pipeline level sidecars might make sense ....)
The intention of the release Task is that it would be run in a
Pipeline's `finally` clause, however today that would be difficult
because finally …
> Add Tasks to acquire and release boskos resources 🐑

- task/pylint/0.1/pylint.yaml
- task/pytest/0.1/pytest.yaml
This will the fix the pytest and pylint task
which fails if run as non root user
in case of non-root user, it install at
location which is not in PATH of image
so adding the required PATH fix the issue
review them:
```
spec:
```
---
> Fix pytest and pylint task

- CONTRIBUTING.md
- task/buildah/0.1/tests/pre-apply-task-hook.sh
- task/buildpacks-phases/0.1/tests/pre-apply-task-hook.sh
- task/buildpacks/0.1/tests/pre-apply-task-hook.sh
- task/golang-build/0.1/tests/pre-apply-task-hook.sh
- task/golang-test/0.1/tests/pre-apply-task-hook.sh
- task/golangci-lint/0.1/tests/pre-apply-task-hook.sh
- task/helm-upgrade-from-repo/0.1/tests/pre-apply-task-hook.sh
- task/helm-upgrade-from-source/0.1/tests/pre-apply-task-hook.sh
- task/jib-gradle/0.1/tests/pre-apply-task-hook.sh
- task/jib-maven/0.1/tests/pre-apply-task-hook.sh
- task/kaniko/0.1/tests/pre-apply-task-hook.sh
- task/maven/0.1/tests/pre-apply-task-hook.sh
- task/prettier/0.1/tests/pre-apply-task-hook.sh
- task/pylint/0.1/tests/pre-apply-task-hook.sh
- task/pytest/0.1/tests/pre-apply-task-hook.sh
- task/replace-tokens/0.1/tests/pre-apply-task-hook.sh
- task/s2i/0.1/tests/pre-apply-task-hook.sh
- test/e2e-common.sh
Centralize all the the git-clone apply commands we had around the
pre-apply-task-hook to a central common function.
This will make easier to have the same git-clone task version used everywhere.
Add some documentation about the helper functions along the way.
```
spec:
```
---
> Centralize all the git-clone apply task to a common function

- task/maven/0.1/README.md
- task/maven/0.1/maven.yaml
Added param for the image in maven task so that
user can use specific maven version
review them:
```
spec:
```
---
> Parameterize maven task image

- task/trigger-jenkins-job/0.1/README.md
- task/trigger-jenkins-job/0.1/samples/run.yaml
- task/trigger-jenkins-job/0.1/samples/secrets.yaml
- task/trigger-jenkins-job/0.1/trigger-jenkins-job.yaml
The following task can be used to trigger an existing Jenkins pipeline from Tekton using the CURL request by providing the required parameters.
review them:
```
spec:
```
---
> Add Task to Trigger Jenkins Build using Tekton

- task/blue-green-deploy/0.1/README.md
- task/blue-green-deploy/0.1/blue-green-deploy.yaml
- task/blue-green-deploy/0.1/samples/run.yaml
- task/blue-green-deploy/0.1/samples/v1-deploy/blue-deployment.yaml
- task/blue-green-deploy/0.1/samples/v1-deploy/service.yaml
- task/blue-green-deploy/0.1/samples/v2-deploy/green-deployment.yaml
- task/blue-green-deploy/0.1/support/clusterrolebinding.yaml
Blue-Green deployment is one of the deployment strategy being used to deploy the newer version of the application on kubernetes keeping the previous version in production so that if newer version fails then the router can be switched back to the previous version of the deployment without any downtime.
review them:
> Add Blue-Green Deployment using K8s

- task/python-coverage/0.1/README.md
- task/python-coverage/0.1/python-coverage.yaml
- task/python-coverage/0.1/tests/pre-apply-task-hook.sh
- task/python-coverage/0.1/tests/resources.yaml
- task/python-coverage/0.1/tests/run.yaml
The following task uses `coverage` dependency in python to measure code coverage of Python projects. This task works along with the pytest so that coverage can be calculated properly.
review them:
```
spec:
```
---
> Add task to include code coverage for Python

- task/upload-pypi/0.1/README.md
- task/upload-pypi/0.1/samples/run.yaml
- task/upload-pypi/0.1/upload-pypi.yaml
I added support for TaskRunResults for this task. This change adds four results:
- the sha256 hash of the bdist package and the sdist package.
- the package name
- the package version
I also fixed a permission issue in the sample - I could not get this to run as a non-root
user (even without my change). The git repo is cloned correctly, but the default user of the
twine image does not have write permissions in this directory.
review them:
```
spec:
```
---
[TEP]: …
> Fixes and improvements to the upload-pypi Task.

- task/prometheus-gate/0.1/README.md
- task/prometheus-gate/0.1/prometheus-gate.yaml
- task/prometheus-gate/0.1/samples/README.md
- task/prometheus-gate/0.1/samples/pipeline.yaml
- task/prometheus-gate/0.1/samples/pipelinerun.yaml
This adds a new Task `prometheus-gate`, aimed at for keeping Tasks and Pipelines gated (eg intentionally blocked) until a certain criteria is met. This Task uses Prometheus range query to obtain range data for the provided query, and asserts all values returned by prometheus are at/above/below target for N times, or fails the pipeline task. The source for the simple gate is [here](https://github.com/iancoffey/prometheus-gate).
Is this a good fit for the catalog? I intend to follow with [creating a custom task](https://github.com/tektoncd/community/issues/144#issuecomment-656234101) from this once I have learned more. More details in the linked issue.
review them:
```
spec:
one line summary of …
```
> Prometheus gate

- test/e2e-common.sh
This will refactor the namespace name to have version of task
in namespace name as current logic may create issue in case
of multiple versions running in same namespace as pid will
remain same
review them:
```
spec:
```
---
> Refactor namespace name to have version

- .github/pull_request_template.md
To make sure the checklist is useful and folks don't ignore it, I think
it's important to keep only the items we need to in there.
If we can enforce something with CI, I suggest we do not include it in
the checklist - if we want to write down guidance somewhere else I think
that totally makes sense, but not in the checklist.
From https://github.com/tektoncd/catalog/issues/387 it looks like
linting should be applied automatically to each PR so I don't think we
need to include this checklist item.
review them: …
> Remove "lint" checklist item 📝

- task/pylint/0.1/README.md
- task/pylint/0.1/pylint.yaml
- task/pylint/OWNERS
- task/pytest/0.1/README.md
- task/pytest/0.1/pytest.yaml
- task/pytest/OWNERS
- task/python-coverage/0.1/README.md
- task/python-coverage/0.1/python-coverage.yaml
- task/python-coverage/OWNERS
* Only install the requirements when the file is here and fix workspace -- following #459 
* Add OWNERS file
* Use latest tag for the python images as default
Now the default value for the python version is latest. This removes the burden to update to the newest python version.
I added myself also to the OWNERS file to drive the development of the tasks. Further, for the tests currently one of my repos is used and I wanted to be updated if there are issues. 
review them:
```
spec:
```
---
[TEP]: …
> Fixes for python coverage and pytest and added OWNERS

- task/git-batch-merge/0.2/README.md
- task/git-batch-merge/0.2/git-batch-merge.yaml
- task/git-batch-merge/0.2/samples/git-cli/pipeline.yaml
- task/git-batch-merge/0.2/samples/git-cli/pvc.yaml
- task/git-batch-merge/0.2/samples/git-cli/secret.yaml
- task/git-batch-merge/0.2/samples/git-cli/service-account.yaml
- task/git-batch-merge/0.2/samples/git-clone-checking-out-a-branch.yaml
- task/git-batch-merge/0.2/samples/git-clone-checking-out-a-commit.yaml
- task/git-batch-merge/0.2/samples/git-rebase/run.yaml
- task/git-batch-merge/0.2/samples/git-rebase/secret.yaml
- task/git-batch-merge/0.2/samples/git-rebase/service-account.yaml
- task/git-batch-merge/0.2/samples/using-git-clone-result.yaml
- task/git-batch-merge/0.2/tests/run.yaml
Set better/more consistent defaults for `depth` and `subdirectory` on the `git-batch-merge` task.
I also modified the test for `git-batch-merge` to actually use a real repo (this repo), real PRs with changes to existing files (PRs #474 and #475), and a `revision` set to the immediate ancestor of PR #474, so that it's actually testing something meaningful. If the test had been structured like this before my change to `git-batch-merge` itself, it would have failed, so...yeah.
fixes #477 
review them:
```
spec:
``` …
> fix: git-batch-merge should default to depth=0 and subdirectory=""

- CONTRIBUTING.md
- test/run-test.sh
This script will allow the developer to test a task directly withouth having to
send it to the CI and wait that all tasks runs to test it.
Usage is : 
```./test/run-test.sh git-clone 0.1```
review them:
> Add a helper script to run a task test directly on your local cluster

- task/git-batch-merge/0.2/git-batch-merge.yaml
- task/git-clone/0.1/git-clone.yaml
- task/kaniko/0.1/kaniko.yaml
- task/kubeconfig-creator/0.1/kubeconfig-creator.yaml
- task/pull-request/0.1/pull-request.yaml
- test/e2e-tests.sh
If the user want to use another image than what we release on gcr.io let give
this option by introducing the param `gitInitImage` to set this up which would
default to the gcr.io image as it was before.
Bump along the way to Pipeline 0.15.1
review them:
> Make git-init image configurable

- task/blue-green-deploy/0.1/README.md
Fixed few links in README, based on new catalog org.
review them:
```
spec:
```
---
> Fix links in README in Blue Green Deploy task

- test/e2e-tests.sh
This will docker-build test in CI as it is
flaky atm and causing other PR not able
to merge
review them:
```
spec:
```
---
> Skip docker-build in CI

- task/jib-maven/0.1/jib-maven.yaml
Added `DOCKER_CONFIG` env in order to avoid authorization error.
The credentials are looked at `/tekton/home` or `/tekton/creds` based on pipeline version so to make it generic used `$(credentials.path)`.
/cc @vdemeester @sbwsg 
review them:
```
spec:
```
---
> Add DOCKER_CONFIG env to avoid authorization issue

- task/git-clone/0.2/README.md
- task/git-clone/0.2/git-clone.yaml
- task/git-clone/0.2/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.2/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.2/samples/using-git-clone-result.yaml
- task/git-clone/0.2/tests/run.yaml
This commit adds git-clone v0.2. One default behaviour has changed
and one new param has been introduced in this version:
1) Tasks that don't start their script with #! automatically receive
a preamble that includes `set -x`. This results in verbose output
because every command is printed while the Task is running.
This commit adds a new param, "verbose", that - when set to "false" -
prevents the commands run by the task from being printed to logs.
The default value is "true": the commands run by the task will be
printed in the log.
2) The git-clone Task offers a param, deleteExisting, that cleans
any existing directory before performing a clone into it. This
has previously been set to "false" by default since it's potentially
destructive. But it sounds like there's quite often a request …
> Remove implicit "set -x" from git-clone, deleteExisting by default

- task/kaniko/0.1/kaniko.yaml
This will fix the issue of kaniko task
failing as we need to run that as root
review them:
```
spec:
```
---
> Fix kaniko task failing issue

- task/istio-canary-release/0.1/README.md
- task/istio-canary-release/0.1/istio-canary-release.yaml
- task/istio-canary-release/0.1/samples/application/app-gateway.yaml
- task/istio-canary-release/0.1/samples/application/myapp.yaml
- task/istio-canary-release/0.1/samples/run.yaml
- task/istio-canary-release/0.1/samples/taskrun.yaml
- task/istio-canary-release/0.1/support/clusterrolebinding.yaml
The following task can be used to do canary release using K8s and Istio. Canary release is a technique to reduce the risk of introducing a new software version in production by slowly rolling out the change to a small subset of users before rolling it out to the entire infrastructure and making it available to everybody. 
The detailed study of canary release can be found [here](https://martinfowler.com/bliki/CanaryRelease.html)
review them:
> Add Canary Release Task using K8s and Istio

- task/ansible-runner/0.1/README.md
- task/ansible-runner/0.1/ansible-runner.yaml
Signed-off-by: Kamesh Sampath <ksampath@redhat.com>
Made the ansible-runner task to be run via `entrypoint` to allow the  proper uid/guid setup in OpenShift environments.  Removed the `script` parameter.
review them:
- [x ] File path follows  `<kind>/<name>/<version>/name.yaml`
```
spec:
```
---
[validation]: …
> Update step command for ansible-runner task

- task/maven/0.2/README.md
- task/maven/0.2/maven.yaml
- task/maven/0.2/tests/pre-apply-task-hook.sh
- task/maven/0.2/tests/resources.yaml
- task/maven/0.2/tests/run.yaml
This PR is to improve the existing maven tasks and support context directory switch in case of multi-module maven projects. Also the settings.xml was being `cat` so removed that also. Also added a sample to showcase how to build a specific module in case of multi-module project.
Closes #447 
review them:
```
spec:
```
---
[example]: …
> Improve maven task in case of  multi-module maven projects

- task/docker-build/0.1/docker-build.yaml
- task/docker-build/0.1/tests/pre-apply-task-hook.sh
- task/docker-build/0.1/tests/resources.yaml
- task/docker-build/0.1/tests/run.yaml
- test/e2e-tests.sh
* Removed docker-build from skip task
* Removed add_sidecar_registry from tests
* Added a deployment with an image registry instead of sidecar.
The end to end test attaches a sidecar with a image registry for tasks to push into to. This task is optional and is encouraged to be used for testing. However, the function add_sidecar_registry sets the sidecar registry instead of appending it. Not using the tasks will fix the test https://github.com/tektoncd/catalog/issues/481
Script sets sidecar equal to an object instead of appending it. So, Im not going to use it in my test.
> [Fixes #481] remove add registry sidecar from docker-build tests

- test/e2e-common.sh
This line queries twice to the github api in order to apply the tekton release yaml. It would increase readability if we just use the googleapi to fetch the yaml.
review them:
```
spec:
```
---
> use default yaml release using google apis instead of querying github api

- task/tekton-operator-install/0.1/README.md
- task/tekton-operator-install/0.1/tekton-operator-install.yaml
The following task uses the released version of tekton operator to install tekton components on a new cluster. By default Tekton pipelines are installed but if we want to install other components as well then we have boolean parameters for respective components
review them:
```
spec:
```
--- …
> Add Task to install Tekton components using Released Tekton Operator

- task/gcs-download/0.1/gcs-download.yaml
- task/gcs-upload/0.1/gcs-upload.yaml
The -m flag copies from multiple threads and makes a huge
performance difference for large trees.
review them:
- [ na] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [na ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [ na] File path follows  `<kind>/<name>/<version>/name.yaml`
- [ na] Has `README.md` at `<kind>/<name>/<version>/README.md`
- [ na] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same …
> Parallelize calls to copy from/to GCS

- task/maven/0.2/README.md
- task/maven/0.2/maven.yaml
This PR is to add `servers` tag for the private repository server.
It is assumed to be used with `MAVEN_MIRROR_URL`, for example, when using a cached library on a private network.
Add `servers` tag for the private repository server.
This PR is a reworked version of #410.
review them:
```
spec:
```
---
[validation]: …
> Add Server's User to the maven task

- task/gcs-generic/0.1/gcs-generic.yaml
- task/gcs-generic/0.1/samples/ls-taskrun.yaml
When running on GCP, gsutil will try to infer identity from the GKE
metadata service instead of an explicitly defined credential file. The
easiest way to support this is to only set the credentials iff the file
is provided, otherwise just fallback to gsutils default behavior.
Also adds a simpler example that doesn't require credentials.
Provides working example for issue described in https://github.com/tektoncd/pipeline/issues/3208.
/cc @dansiviter (confirmed this works for a private GCS file w/ a Workload Identity enabled cluster)
review them:
```
spec:
``` …
> gcs-generic: Make credential file optional.

- task/github-set-status/0.2/README.md
- task/github-set-status/0.2/github-set-status.yaml
Rather than forcing task users to create a secret with a fixed
name, allow setting the secret name and key as parameter.
The new parameters are optional, in the sense that they default
to the previous hardcoded values.
review them:
```
spec:
```
---
> Add the ability to specify secret name and key

- task/docker-build/0.1/docker-build.yaml
A misplaced parameter, `build_extra_args` was placed where `push_extra_args` belonged. This prevents push of the built image if `--build-args` are used when building the image. This small change fixes that.
> docker-build - misplaced parameter prevents push

- task/trigger-jenkins-job/0.1/tests/pre-apply-task-hook.sh
- task/trigger-jenkins-job/0.1/tests/run.yaml
- task/trigger-jenkins-job/0.1/trigger-jenkins-job.yaml
Rewrite the triggers-jenkins-job, the arguments and params are about to same.
Starting from Jenkins LTS 2.176.2 we need to create a crumb and capture the
cookie jar to make the subsequent requests.
https://support.cloudbees.com/hc/en-us/articles/219257077-CSRF-Protection-Explained
Add tests :
We spins up a deployment with a jenkins lts and expose a service to it so our
task can access it.
We do some ninja execing into the pods to create a jenkins job in there and
setup the configmap secret.
We probably should drop the CRUMB setting since it will not work anymore but it
is harmless since we are regenerating it anyway.
Todo: need to test with jenkins image that is older than 2.176.2, but it
probably should work
> Rework the triggers-jenkins-job

- task/pylint/0.2/README.md
- task/pylint/0.2/pylint.yaml
- task/pylint/0.2/tests/pre-apply-task-hook.sh
- task/pylint/0.2/tests/run.yaml
Add new pylint task
- Bump a new pylint task to 0.2
- Use an image which already has pylint and not auto install it every time we
run the task.
- Do not try to install requirements.txt modules since pylint doesn't need it.
- Remove the ability to choose another python version since you probaby would
not need it for a static analyzer. If you really need it you can redefine the
image params targetting a custom container image.
> Pylint: use an image with pylint preinstall and don't install requirements.txt

- task/golang-build/0.1/golang-build.yaml
- task/golang-test/0.1/golang-test.yaml
Fixes https://github.com/tektoncd/catalog/issues/461
Also reported here: https://github.com/tektoncd/pipeline/issues/3152
The golang-test and build tasks attempts to use variable interpolation in a workspaces.mountPath field where it isn't supported. This results in the source code being mounted in a directory called literally, "$(params.package)".
This commit updates the golang-test and build tasks to make the package directory and copy the source code into it, then cd into it and run `go test`. This should result in better expected outcome - the source will be in the package directory that it expects to be.
review them:
/kind bug
> Fix golang-test and build issue where src is put in literal directory "$(params.package)"

- CONTRIBUTING.md
Taking the trigger-jenkins-build e2e tests example of spinning a jenkins server
inside the test namespace we document an alternative to the 'reflector' tests
for e2e test.
This is documented as the 'first' one since probably more robust to test that
way than the reflector testing.
> Add more documentation about external testing

- task/tkn/0.2/README.md
- task/tkn/0.2/samples/run-with-workspace.yaml
- task/tkn/0.2/samples/run-without-worksapce.yaml
- task/tkn/0.2/samples/secrets.yaml
- task/tkn/0.2/tkn.yaml
The tkn task will be able to work with a kubeconfig for a cluster so that it can operate on it. The following task can also accept a SCRIPT as input so that we can run multiple tkn commands.
Closes #405 
/cc @sbwsg @vdemeester 
review them:
```
spec:
```
---
[validation]: …
> Add support to mount kubeconfig  in `tkn` task

- task/jenkins/0.1/README.md
- task/jenkins/0.1/jenkins.yaml
- task/jenkins/0.1/samples/run.yaml
- task/jenkins/0.1/samples/secrets.yaml
- task/jenkins/0.1/tests/pre-apply-task-hook.sh
- task/jenkins/0.1/tests/run.yaml
Add a more generic jenkins task
We had previously the triggers-jenkins-job task, this task is more generic and
allows more operations, it currently support starting a jenkins job and getting
the log of a build. It allows as well to wait that the job had started or that
the job has finished.
With this more generic task it makes it easier to have other jenkins operations
in there.
Testing should be much more robust too.
review them:
```
spec:
```
---
[TEP]: …
> Add new generic jenkins task

- test/e2e-common.sh
We temporary disable the debug output while on the loop so we don't have the
gazillions debug messages while digging into the log. We have added the 'timing'
when it start and ends so we can easily spots the very slow tests (see #548 for investigation)
Aditionally we have introduced the new variable `CATALOG_TEST_SKIP_CLEANUP` if
set it will skip deleting the namespace. This is useful when running in
conjuncton with the `./test/run-test.sh` script to debug when there is a
failure.
> Improve e2e tests runner output

- task/pylint/0.2/README.md
- task/pylint/0.2/pylint.yaml
the install of the requirements.txt dependences was wrongly (by me) removed from the 0.1 task but it is actually
needed for pylint, since it would error out if it can't find the dependences.
review them:
```
spec:
```
---
> Readd requirements.txt install for pylint task

- task/buildah/0.2/README.md
- task/buildah/0.2/buildah.yaml
- task/buildah/0.2/samples/openshift-internal-registry.yaml
- task/buildah/0.2/tests/internal-registry/internal-registry.yaml
- task/buildah/0.2/tests/pre-apply-task-hook.sh
- task/buildah/0.2/tests/run.yaml
Add buildah 0.2 with optional ssl certdir workspace
We are bumping the buildah task to 0.2 since this needs at least pipeline 0.17.0.
This will add a optional workspace for the cert dir to pass to buildah --cert-dir flag.
This add as well a complete sample on how to use it with the openshift internal registry.
Reworked a bit the test to use pipelineSpec and make it to run against a registry with ssl certificate.
/cc @sbwsg 
review them:
- [✔️] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [✔️] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [✔️] …
> Add buildah 0.2 with optional ssl certdir workspace

- CONTRIBUTING.md
- test/e2e-common.sh
- test/e2e-tests.sh
We are nnow only doing integration tests on the tasks that has been modified or added. This will improve the speed of each PR iteration not testing everything while the PR modify only some part of it.
/cc @sthaha 
if you know if there is any other git trickery i can use to detect
file changes between the 'main' branch and the PR
/cc @bobcatfish 
cf #373 discussion
review them:
> Test tasks that only has been modified or added

- test/e2e-common.sh
- test/e2e-tests.sh
Do not quote "$@" too (as shellcheck was telling me) because we would not get a
proper array to get into.
Detect propelry changed files when there is multiple yaml in there
/hold
>  Detect propelry changed files when there is multiple yaml in there

- task/pylint/0.2/pylint.yaml
Args wasnt expanded properly, it showed like this when running the task:
`[pthon-lint : pylint] /tekton/scripts/script-0-s2wjl: line 8: inputs.params.args: not found`
review them:
- ✅ Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- ✅ Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- ✅ Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- ✅ Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation] …
> pylint: make sure we expands args

- test/e2e-common.sh
We were not getting properly the versions when there was files like OWNER in there
so make sure to grab only the directory
Before : 
```bash
$ task=golang-test;echo task/${task}/*
task/golang-test/0.1 task/golang-test/OWNERS
```
After : 
```bash
$ task=golang-test;echo task/${task}/*/
task/golang-test/0.1/
```
review them:
- ✅ Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- ✅ Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- ✅ Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messag …
> Fix add_task common function

- task/git-batch-merge/0.2/git-batch-merge.yaml
- task/git-clone/0.2/README.md
- task/git-clone/0.2/git-clone.yaml
- Bump git-init version to v0.17.3 which contains bug-fixes for `git-init` ([Release Note](https://github.com/tektoncd/pipeline/releases/tag/v0.17.3))
- Also, make git-init image in git-clone/clone as configurable value
review them:
```
spec:
```
> Bump git-init version to v0.17.3

- task/git-batch-merge/0.2/git-batch-merge.yaml
- task/git-clone/0.2/git-clone.yaml
- test/e2e-tests.sh
Tekton Pipeline [0.18.0](https://github.com/tektoncd/pipeline/releases/tag/v0.18.0) was just released and as part of the release [process](https://github.com/tektoncd/pipeline/pull/3258), bumping up the following images in the catalog tasks:
* (task - current images)
* git-batch-merge - v0.17.3
* git-clone - v0.17.3
review them:
```
spec:
```
---
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clon …
> bumping up pipeline version

- test/e2e-tests.sh
- While running integration tests we are getting `dirname: missing operand`.
- `git --no-pager diff --name-only 65dd35a5e8a7e63443b52df70ea5bbc0bc621dac..` Pull SHA is missing so fixed that
/cc @chmouel @vdemeester 
review them:
- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [n/a] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [n/a] File path follows …
> Fix e2e script

- task/orka-full/0.1/README.md
- task/orka-full/0.1/SCRIPTS.md
- task/orka-full/0.1/add-orka-creds.sh
- task/orka-full/0.1/add-ssh-creds.sh
- task/orka-full/0.1/install.sh
- task/orka-full/0.1/orka-full.yaml
- task/orka-full/0.1/resources/orka-creds.yaml.tmpl
- task/orka-full/0.1/resources/orka-ssh-creds.yaml.tmpl
- task/orka-full/0.1/resources/orka-tekton-config.yaml.tmpl
- task/orka-full/0.1/samples/build-audiokit-pipeline.yaml
- task/orka-full/0.1/samples/dump-disk-info.yaml
- task/orka-full/0.1/samples/use-ssh-key.yaml
- task/orka-full/0.1/tests/mocks/orka.yaml
- task/orka-full/0.1/tests/mods/mod_task.py
- task/orka-full/0.1/tests/mods/sidecars.yaml
- task/orka-full/0.1/tests/mods/volumes.yaml
- task/orka-full/0.1/tests/pre-apply-task-hook.sh
- task/orka-full/0.1/tests/resources.yaml
- task/orka-full/0.1/tests/run.yaml
- task/orka-full/OWNERS
This PR aims to add a Task in order to integrate Tekton with [Orka by MacStadium](https://www.macstadium.com/orka). Orka allows users to run macOS builds and workloads on real Apple hardware. An Orka / Tekton integration will allow the utilization of macOS build agents for CI jobs that run on Tekton pipelines.
The `orka-full` Task will allow the utilization of a single macOS build agent, allowing the user to provide a build script as a parameter, and will allow the user to store build artifacts in a Tekton workspace. 
> **NOTE**: In order to use this Task, an Orka environment is required. Orka runs in a self-contained Kubernetes cluster and a VPN connection must be established between the Orka cluster and the Kubernetes cluster in which Tekton is installed.
These are the criteria that …
> Add orka-full task for MacStadium Orka integration

- task/buildpacks-phases/0.1/tests/run.yaml
- task/buildpacks/0.1/buildpacks.yaml
- task/buildpacks/0.2/buildpacks.yaml
- task/buildpacks/0.2/tests/run.yaml
- test/e2e-common.sh
- Modified e2e script to check for deprecated labels and skip the tests for that task
- Added `securityContext` in buildpacks 0.2 task
- Added digest in `buildpacks-phases run.yaml` and `buildpacks 0.2 run.yaml` so that in future CI doesn't fails
fixes #575 
review them:
```
spec:
```
--- …
> Add security context in create step of buildpacks

- task/helm-upgrade-from-repo/0.1/samples/helm-upgrade-from-repo-task-run.yaml.tmpl
- task/helm-upgrade-from-repo/0.1/tests/run.yaml
repo "https://kubernetes-charts.storage.googleapis.com" is no longer available
so changing to "https://charts.helm.sh/stable"
review them:
```
spec:
```
---
> Fix helm-upgrade-from-repo tests

- task/skopeo-copy/0.1/skopeo-copy.yaml
In quay.io if a tag is repushed, the previous digest becomes in-accessible.
So removing the digest from skopeo-copy task as the current digest was in-accessible.
review them:
```
spec:
```
---
> Fix image in Skopeo-copy task

- test/e2e-common.sh
- test/e2e-tests.sh
Current e2e script is only able to run integration tests on those PRs which include tests.
With this fix, tests will run on those PRs also in which only task yaml is changed
review them:
```
spec:
```
---
> Fix e2e scripts to test modified tasks

- task/orka-full/0.1/orka-full.yaml
To run Orka in OpenShift successfully we need to run the build step as privileged else some operations are not permitted without privilege access
review them:
```
spec:
```
---
> Run build step in Orka as privilege

- task/kn-apply/0.1/README.md
- task/kn-apply/0.1/kn-apply.yaml
- task/kn-apply/0.1/support/kn-deployer.yaml
- task/kn-apply/OWNERS
Add a new kn-deploy task which uses `kn service apply` feature. The task takes only two mandatory params; service name and image name. 
review them:
```
spec:
```
---
> Add kn-apply task

- test/e2e-tests.sh
Currently no of parallel tasks running at a time are 5
but in case the last set of tasks doesn't count upto 5
then handling that case over here.
/hold
review them:
```
spec:
```
---
> Fix e2e: Test remaining tasks after parellelization

- test/e2e-tests.sh
Since maven task is being flaky thus skipping that in the e2e tests for now.
review them:
```
spec:
```
---
> Skipping maven tests in CI

- test/e2e-tests.sh
e2e script was unable to detect the changes in the `pre-apply-task-hook.sh` file(if any), so fixed that.
review them:
```
spec:
```
---
> Fix e2e script to detect any file change

- task/golang-test/0.1/tests/run.yaml
This will change the golang-test task tests to use cli repo for
unit test rather than pipeline repo as the test is failing there
review them:
```
spec:
```
---
> Change test repo to cli from pipeline in golang-test task

- test/e2e-tests.sh
The e2e tests detect changes in subdir but also applies that
subdir while testing which fails the tests for some new PRs such as #610 
This PR detects changes even in subdir but only passes the valid test
dir path to the script and avoid subdirs such as /mods, /mocks etc
/hold
review them:
```
spec:
```
---
[example]: …
> Fix e2e script to run only tests dir

- task/s2i/0.2/Dockerfile
- task/s2i/0.2/README.md
- task/s2i/0.2/s2i.yaml
- task/s2i/0.2/samples/openshift-internal-registry.yaml
- task/s2i/0.2/tests/internal-registry/internal-registry.yaml
- task/s2i/0.2/tests/pre-apply-task-hook.sh
- task/s2i/0.2/tests/run.yaml
Earlier version of s2i uses PipelineResources which are now deprecated.
Also the s2i task is missing the digest in results.
With this PR:-
- Removing the usage of PipelineResources and using equivalent task from
catalog in the tests.
- Storing the digest in results so that it can be used later on by
another task.
- Adds optional workspace for the cert dir to pass to buildah --cert-dir flag.
review them:
```
spec:
```
---
[TEP]: …
> Avoid the usage of PipelineResources from s2i

- task/orka-deploy/0.1/README.md
- task/orka-deploy/0.1/orka-deploy.yaml
- task/orka-deploy/0.1/samples/parallel-deploy.yaml
- task/orka-deploy/0.1/samples/use-ssh-key.yaml
- task/orka-deploy/0.1/tests/mocks/orka.yaml
- task/orka-deploy/0.1/tests/mods/mod_task.py
- task/orka-deploy/0.1/tests/mods/sidecars.yaml
- task/orka-deploy/0.1/tests/mods/volumes.yaml
- task/orka-deploy/0.1/tests/pre-apply-task-hook.sh
- task/orka-deploy/0.1/tests/resources.yaml
- task/orka-deploy/0.1/tests/run.yaml
- task/orka-deploy/OWNERS
- task/orka-init/0.1/README.md
- task/orka-init/0.1/orka-init.yaml
- task/orka-init/0.1/tests/fixtures/orka.yaml
- task/orka-init/0.1/tests/resources.yaml
- task/orka-init/0.1/tests/run.yaml
- task/orka-init/OWNERS
- task/orka-teardown/0.1/README.md
- task/orka-teardown/0.1/orka-teardown.yaml
- task/orka-teardown/0.1/tests/mocks/orka.yaml
- task/orka-teardown/0.1/tests/mods/mod_task.py
- task/orka-teardown/0.1/tests/pre-apply-task-hook.sh
- task/orka-teardown/0.1/tests/resources.yaml
- task/orka-teardown/0.1/tests/run.yaml
- task/orka-teardown/OWNERS
This change adds a set of modular Tasks to integrate Tekton with Orka
by MacStadium. Orka allows users to run macOS builds and workloads on
real Apple hardware. An Orka / Tekton integration will allow the
utilization of macOS build agents for CI jobs that run on Tekton
pipelines.
The tasks orka-init, orka-deploy and orka-teardown are designed to work
together in order to allow the utilization of multiple macOS
build agents in a CI/CD pipeline. The orka-deploy Task allows the user
to provide a build script as a parameter, and will allow the user to
store build artifacts in a Tekton workspace. The orka-init and
orka-teardown tasks create and delete virtual machine configurations.
This is accomplished by making calls to the Orka API running in a
separate Kubernetes cluster over a VPN …
> Add set of modular Orka tasks

- task/openshift-client/0.1/README.md
- task/openshift-client/0.1/openshift-client.yaml
- task/openshift-client/0.1/tests/run.yaml
Add a params to allow the user to specify an OpenShift Version for the
openshift-client task to use.
Add a test along the way.
review them:
```
spec:
```
---
> Add a VERSION params to openshift client task

- task/tkn/0.1/tkn.yaml
- task/tkn/0.2/tkn.yaml
multi-arch tkn image allows to use the same catalog task in the setup
for many hardware acrhitectures (latest tkn image is available for
linux/amd64, linux/s390x and linux/ppc64le)
review them:
```
spec:
```
---
> Use multi-arch tkn container image for tkn task

- task/git-cli/0.1/git-cli.yaml
- task/git-rebase/0.1/git-rebase.yaml
Image sha specified in git-cli and git-rebase tasks is for `amd64` version of `alpine/git:v2.26.2` image. The image is actually multi-arch one.
Replacement of image sha to point to multi-arch version will allow to use the same catalog task for many hardware acrhitectures.
review them:
```
spec:
```
---
[validation]: …
> Use multi-arch alpine/git image for git-cli and git-rebase

- task/kubernetes-actions/0.2/README.md
- task/kubernetes-actions/0.2/kubernetes-actions.yaml
- task/kubernetes-actions/0.2/samples/kubectl-actions-run.yaml
- task/kubernetes-actions/0.2/samples/update-deployment-image-taskrun.yaml
- task/kubernetes-actions/0.2/tests/resources.yaml
- task/kubernetes-actions/0.2/tests/run.yaml
This PR adds optional workspaces support in kubernetes-actions
task and also adds tests for the task.
review them:
```
spec:
```
---
> Add optional workspaces in kubernetes-actions task

- task/github-create-deployment/0.1/README.md
- task/github-create-deployment/0.1/github-create-deployment.yaml
This introduces a Task for creating GitHub deployments for a given
repository. This allows people who rely on GitHub deployment events
for their CD systems to be able create them from within a Tekton
pipeline.
This task is pretty much just a wrapper around the GitHub API for
creating deployments. The main params required are the ref
and environment for the deployment, and we fall back to the API's
defaults for the other params.
review them:
> Task for creating GitHub deployments

- task/aws-cli/0.2/README.md
- task/aws-cli/0.2/aws-cli.yaml
- task/aws-cli/0.2/samples/run.yaml
- task/aws-cli/0.2/samples/secret.yaml
Credentials can be passed to the aws-cli via instance roles (with e.g. `kiam`).
So an installation of this task could look like this:
```
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/master/task/aws-cli/0.2/aws-cli.yaml
patchesStrategicMerge:
- |-
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: aws-cli
annotations:
iam.amazonaws.com/role: tekton-upload
```
> aws-cli: Make `secrets` workspace optional

- task/golangci-lint/0.1/README.md
- task/golangci-lint/0.1/golangci-lint.yaml
This adds context param to provide path to the directory to use
as context.
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
review them:
```
spec:
```
---
> Adds context param in golangci-lint

- task/golang-test/0.1/README.md
- task/golang-test/0.1/golang-test.yaml
This adds context param to provide path to the directory to use
as context.
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
review them:
```
spec:
```
---
> Adds context param in golang-test task

- task/helm-upgrade-from-repo/0.2/README.md
- task/helm-upgrade-from-repo/0.2/helm-upgrade-from-repo.yaml
- task/helm-upgrade-from-repo/0.2/samples/helm-upgrade-from-repo-task-run.yaml.tmpl
- task/helm-upgrade-from-repo/0.2/tests/pre-apply-task-hook.sh
- task/helm-upgrade-from-repo/0.2/tests/resources.yaml
- task/helm-upgrade-from-repo/0.2/tests/run.yaml
Add helm image parameter instead of helm image version
review them:
```
spec:
```
---
> Bump helm-upgrade-from-repo task version to 0.2

- task/jenkins/0.1/tests/pre-apply-task-hook.sh
- task/trigger-jenkins-job/0.1/tests/pre-apply-task-hook.sh
Currently in pre-apply-task-hook.sh we are using `jenkins:lts` image
which gets updated on a regular basis which might break the CI while
testing the following tasks:- jenkins, trigger-jenkins-job.
Adding a tag+digest to the image used in test so that the tests don't
break in future.
review them:
```
spec:
```
---
[example]: …
> Fix jenkins and trigger-jenkins-job task tests

- task/git-clone/0.3/README.md
- task/git-clone/0.3/git-clone.yaml
- task/git-clone/0.3/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.3/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.3/samples/git-clone-sparse-checkout.yaml
- task/git-clone/0.3/samples/using-git-clone-result.yaml
- task/git-clone/0.3/tests/run.yaml
I have added sparse-checkout capabilities to the git-clone task. I have also created a sample based on the others.
I tested this using the nightly image: 
https://console.cloud.google.com/gcr/images/tekton-nightly/GLOBAL/github.com/tektoncd/pipeline/cmd/git-init@sha256:54f18d7519e4249da6fc6c17af8e7cd9d72d0ba54d47e0bd584f58cfc9617142/details?tab=info
review them:
```
spec:
```
---
[example]: …
> add sparse clone

- task/docker-build/0.1/README.md
- task/docker-build/0.1/docker-build.yaml
At the time of writing, the stable `docker:dind` is broken, the solution is to roll back to the previous version (https://github.com/containerd/containerd/issues/4837).
In other words, `docker:dind` should be temporarily replaced with `docker:19-dind`.
I think allowing users to specify the docker-in-docker image via params is the best way to get around this issue.
Add param that determines the image used for docker-in-docker.
review them:
```
spec:
```
---
[TEP]: …
> Choose dind image via params

- task/orka-init/0.1/orka-init.yaml
- task/orka-teardown/0.1/orka-teardown.yaml
The tasks orka-init and orka-teardown fails to create resources on the
cluster where rbac rules are enforced so running that as privileged
works fine.
review them:
```
spec:
```
---
> Run orka-init and orka-teardown as privileged

- task/github-add-gist/0.1/README.md
- task/github-add-gist/0.1/github-add-gist.yaml
- task/github-add-gist/0.1/samples/pipeline.yaml
- task/github-add-gist/0.1/tests/fixtures/github-post-gist.yaml
- task/github-add-gist/0.1/tests/pre-apply-task-hook.sh
- task/github-add-gist/0.1/tests/resources.yaml
- task/github-add-gist/0.1/tests/run.yaml
This adds a task to upload a file on gist github.
review them:
```
spec:
```
---
> Add Task to post a file on Gist Github

- task/github-add-comment/0.3/README.md
- task/github-add-comment/0.3/github-add-comment.yaml
- task/github-add-comment/0.3/tests/fixtures/github-post-comment.yaml
- task/github-add-comment/0.3/tests/pre-apply-task-hook.sh
- task/github-add-comment/0.3/tests/run.yaml
As of now github-add-comment task supports input of comments only via
params.
This PR adds support of workspaces if in case somebody wants to provide
the comments via some file. One such use case can be:-
In Catlin CI, logs are produced after executing catlin command on
changed files which can contain multiple warnings and these warnings can
be ingored by the user if not posted on the github PR as the CI is
green. So all the logs would be stored in a file with proper formatting
and then the shared workspace can be passed to the github-add-comment
task along with the filename containing the formatted logs.
review them:
```
spec:
one line summary of …
```
> Add github-add-comment version 0.3

- task/buildpacks-phases/0.2/README.md
- task/buildpacks-phases/0.2/buildpacks-phases.yaml
- task/buildpacks-phases/0.2/samples/env-vars.yaml
- task/buildpacks-phases/0.2/samples/lifecycle-image.yaml
- task/buildpacks-phases/0.2/samples/results.yaml
- task/buildpacks-phases/0.2/tests/pre-apply-task-hook.sh
- task/buildpacks-phases/0.2/tests/resources.yaml
- task/buildpacks-phases/0.2/tests/run.yaml
- Add `APP_IMAGE_DIGEST` result
- Upgrade to Platform API 0.4
- Add parameter to configure the `LIFECYCLE_IMAGE`
- Add support for build-time environment variables
- Replace use of PipelineResources with Params
review them:
```
spec:
```
---
> Add task/buildpacks-phases/0.2

- task/github-request-reviewers/0.1/README.md
- task/github-request-reviewers/0.1/github-request-reviewers.yaml
- task/github-request-reviewers/0.1/tests/fixtures/github-post-comment.yaml
- task/github-request-reviewers/0.1/tests/pre-apply-task-hook.sh
- task/github-request-reviewers/0.1/tests/run.yaml
Add a new task that allows to request reviewers on a GitHub PR.
review them:
```
spec:
This Task will request reviewers for a GitHub PR
It can take either a list of users or teams or both.
Note that, when teams are used, GitHub does not verify
if the team (or any of its members) are collaborators
the repo, so a 201 reply may still result in no reviewer
added to the PR.
```
---
[example]: …
> Task to request reviewers on a GitHub PR

- task/github-create-deployment/0.2/README.md
- task/github-create-deployment/0.2/github-create-deployment.yaml
- task/github-create-deployment/0.2/tests/fixtures/github-create-deployment.yaml
- task/github-create-deployment/0.2/tests/pre-apply-task-hook.sh
- task/github-create-deployment/0.2/tests/run.yaml
Bump github-create-deployment version to 0.2
- Add API_PATH_PREFIX to github-create-deployment task parameter
GitHub enterprise exposes API using path (e.g. `/api/v3`) instead of host.
Current github-create-deployment implementation will fail on this case, since `HTTPSConnection` does not allow path included host.
Signed-off-by: Sunghoon Kang <hoon@linecorp.com>
review them:
```
spec:
```
> Bump github-create-deployment version to 0.2

- test/e2e-common.sh
Resolves #678
- Go back to using python to append yaml
- I dislike python but after discussion in #678 it's clear the sensible choice is to go back to using it
- Check for libraries in a pip agnostic way
- I install my python dependencies through [nix](https://search.nixos.org/packages?channel=unstable&show=python39Packages.pyyaml&from=0&size=50&sort=relevance&query=pyyaml) when I have to so the pip method doesn't work. This is likely the same if pyyaml is installed through apt/yum/etc
- allow for adding multiple sidecars with a reusable `add_sidecars` function
- fix overwriting sidecars issue for previous python
- the previous python implementation would replace sidecars resulting in a _similar_ issue to the bash solution if `add_sidecar_registry` wasnt ran first
- make it more readable …
> Go back to appending sidecars with python

- task/github-create-deployment-status/0.1/README.md
- task/github-create-deployment-status/0.1/github-create-deployment-status.yaml
- task/github-create-deployment-status/0.1/samples/run.yaml
- task/github-create-deployment-status/0.1/samples/secret.yaml
- task/github-create-deployment-status/0.1/tests/fixtures/github-create-deployment-status.yaml
- task/github-create-deployment-status/0.1/tests/pre-apply-task-hook.sh
- task/github-create-deployment-status/0.1/tests/run.yaml
This task allows to update a status of GitHub deployment from a Tekton pipeline. This task can be used while deploying or
after deployed (with `finally`) to show status at GitHub deployment status tab.
Signed-off-by: Sunghoon Kang <hoon@linecorp.com>
review them:
```
spec:
```
> Add github-create-deployment-status task

- test/e2e-common.sh
- test/e2e-tests.sh
In e2e tests script podTemplate was getting added even if the yaml
manifest contains only ConfigMap which was failing the CI.
Add a envFrom to mount fixtures ConfigMap instead of using podTemplate
as appending the podTemplate was conditional and there can be scenarios
where podTemplate might get appended at wrong location.
Also removing `ask/github-add-comment/0.4/tests/fixtures/list-comment-response.json`
and moving this to fixtures file.
*Run CI on whole catalog if e2e test modified*
As of now if there is some modification in any e2e test then CI doesn't
run on whole catalog and this might result in failure of some task which
we get to know next day whene nightly periodic job runs.
This change detects the changes in the tests dir and if there is any
change then run the CI on whole …
> Append volume in sidecar instead of podTemplate for fixture sidecar and Run CI on whole catalog if e2e test modified

- CONTRIBUTING.md
- task/buildah/0.2/tests/pre-apply-task-hook.sh
- task/jib-maven/0.3/README.md
- task/jib-maven/0.3/jib-maven.yaml
- task/jib-maven/0.3/tests/internal-registry/internal-registry.yaml
- task/jib-maven/0.3/tests/pre-apply-task-hook.sh
- task/jib-maven/0.3/tests/resources.yaml
- task/jib-maven/0.3/tests/run.yaml
- task/s2i/0.2/tests/pre-apply-task-hook.sh
- test/e2e-common.sh
This will add jib-maven 0.3 version with support for providing cert file
to talk to insecure registry
Fix #686
review them:
```
spec:
```
---
> Add jib-maven 0.3 with certficate support for registry

- task/kaniko/0.3/README.md
- task/kaniko/0.3/kaniko.yaml
- task/kaniko/0.3/tests/pre-apply-task-hook.sh
- task/kaniko/0.3/tests/resources.yaml
- task/kaniko/0.3/tests/run.yaml
Add an optional workspace to the kaniko task that can be used to
pass container registry credentials to the kaniko task.
This mechanism replaces the service account based one. The change
is not backward compatible, however it is not easily possible to
support both auth mechanism, since the service account one
requires setting DOCKER_CONFIG, which breaks the workspace based
one. Workspace are preferrable since they are available in all
deployments, while Tekton's built-in auth is only available when
it's enabled. While enabled is the default setting for now, it may
change in future, and it may already be disabled in various
deployments, where the kaniko task is today effecively unusable.
These are the criteria that every PR should …
> Support Kaniko authentication via workspace

- task/jenkins/0.1/tests/pre-apply-task-hook.sh
- test/e2e-tests.sh
Aims to make e2e tests consistent across projects.
review them:
- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [n/a] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [n/a] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [n/a] File path follows  `<kind>/<name>/<version>/name.yaml`
- [n/a] Has `README.md` at …
> Remove extra set -x commands in e2e tests.

- task/jenkins/0.1/tests/pre-apply-task-hook.sh
This is a follow up to https://github.com/tektoncd/catalog/pull/696.
review them:
- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [n/a] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [n/a] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
- [n/a] File path follows  `<kind>/<name>/<version>/name.yaml`
- [n/a] Has …
> jenkins: Add set +x to test script.

- test/e2e-tests.sh
As of now the function `detect_changed_e2e_test` was running even if the
variable `TEST_RUN_ALL_TESTS` value was set which resulted in breaking
the CI.
Add a condition to call the function iff `TEST_RUN_ALL_TESTS` value is
not set.
review them:
```
spec:
```
---
[validation]: …
> Fix e2e scripts

- go.mod
- go.sum
- vendor/github.com/tektoncd/plumbing/scripts/README.md
- vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
- vendor/github.com/tektoncd/plumbing/scripts/library.sh
- vendor/modules.txt
This commit pins catalog to gke 1.18 for the next six months
while plumbing works on removing basic auth.
Major hat-tip to @jmcshane for doing the work to resolve this
problem!
review them:
/kind misc
> Update plumbing dep to pin gke version

- task/jib-maven/0.3/jib-maven.yaml
This will fix the issue of task failing with some MAVEN_IMAGE
like 3.6.3-adoptopenjdk-11 etc because of [[ not found
review them:
```
spec:
```
---
> Use bash instead on sh in jib-maven

- task/kind/0.1/README.md
- task/kind/0.1/kind.yaml
- task/kind/0.1/tests/pre-apply-task-hook.sh
- task/kind/0.1/tests/run.yaml
This adds support for running kind within Tekton. This includes 2
main components:
1. Catalog Task for configuring Docker-in-Docker environment.
2. Dockerfile Runner image as a base environment for common runtime tools.
review them:
```
spec:
```
---
> Add kind catalog task.

- task/github-app-token/0.2/Dockerfile
- task/github-app-token/0.2/README.md
- task/github-app-token/0.2/github-app-token.yaml
- task/github-app-token/0.2/samples/run.yaml
- task/github-app-token/0.2/samples/secret.yaml
Added a new parameter to allow getting the application_id stored in a file
inside the secrets workspace. 
Still allowing as params directly if user would like to use
this instead.
review them:
```
spec:
```
---
> Add github app token 0.2

- .github/pull_request_template.md
- CONTRIBUTING.md
- recommendations.md
Writing my first contribution to the catalog, I failed to find the authoring recommendations, resulting in unnecessary Slack noise. This adds references to parts of the documentation that I did read in the hope that others will see them in time.
I removed the recommendations list that was inlined in CONTRIBUTING.md as it is covered by the linked recommendations.md. The "portability" item was only partially covered by the recommendations, so I took the liberty of adding a section about backwards version compatibility, as that is the most important portability concern I can think of in this context.
These are the criteria that every PR should meet, please check them off as you review them:
> Raise the visibility of authoring recommendations

- task/sendmail/0.1/README.md
A small typo to make sure no surprise happens when copy/pasting the kubectl command
review them:
```
spec:
```
---
> Fix typo in sendmail readme

- task/git-clone/0.1/git-clone.yaml
- task/git-clone/0.2/git-clone.yaml
- task/git-clone/0.3/git-clone.yaml
Previously we passed params directly into the `script` block of
the clone step. Because Pipelines doesn't escape variable values
when interpolating them the behaviour of the task could be changed
by the contents of a param.
This commit changes the way params are provided to the script;
instead of being interpolated directly they are converted first
into environment variables and accessed through shell's `${}`
construct.
There are no behaviour changes to the git-clone tasks themselves.
> Pass git-clone Params as EnvVars Instead

- task/write-file/0.1/README.md
- task/write-file/0.1/tests/run.yaml
- task/write-file/0.1/write-file.yaml
This PR adds a catalog task to write a parameter out as a file, creating intermediate directories and setting permissions as necessary. While it is possible today to have a workspace that is a mounted config map variable, that provides limited support for expanding parameters into the file (i.e. the [replace-tokens](https://hub.tekton.dev/tekton/task/replace-tokens) task). Ultimately, my argument for adopting this task into the catalog is that I believe others will also look for a file-writing task and their experience of Tekton will be better if they find one.
review them:
> Add Task to write a file onto a workspace

- task/tekton-catalog-publish/0.1/README.md
- task/tekton-catalog-publish/0.1/samples/run-with-workspace-secret.yaml
- task/tekton-catalog-publish/0.1/samples/run-without-workspace-secret.yaml
- task/tekton-catalog-publish/0.1/samples/secrets.yaml
- task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
- task/tekton-catalog-publish/0.1/tests/pre-apply-task-hook.sh
- task/tekton-catalog-publish/0.1/tests/resources.yaml
- task/tekton-catalog-publish/0.1/tests/run.yaml
Add a new task that uses tkn bundle to publish a Tekton catalog as
bundles to a container registry. Each task corresponds to a dedicated
bundle, which task versions available as tags.
Optionally, bundles are tagged with an extra tag provided as an input
parameter.
review them:
```
spec:
```
---
[example]: …
> Add a task to publish a catalog as bundles

- task/tekton-catalog-publish/0.1/tekton-catalog-publish.yaml
The syntax of the find command was not correct, and the error was not
caught by CI because of the missing "set -o pipefail".
review them:
```
spec:
```
---
> [tekton-publish-catalog] Fix syntax of find command

- task/golang-build/0.2/README.md
- task/golang-build/0.2/golang-build.yaml
- task/golang-build/0.2/tests/pre-apply-task-hook.sh
- task/golang-build/0.2/tests/resources.yaml
- task/golang-build/0.2/tests/run.yaml
- task/golang-test/0.2/README.md
- task/golang-test/0.2/golang-test.yaml
- task/golang-test/0.2/tests/pre-apply-task-hook.sh
- task/golang-test/0.2/tests/resources.yaml
- task/golang-test/0.2/tests/run.yaml
- task/golangci-lint/0.2/README.md
- task/golangci-lint/0.2/golangci-lint.yaml
- task/golangci-lint/0.2/tests/pre-apply-task-hook.sh
- task/golangci-lint/0.2/tests/resources.yaml
- task/golangci-lint/0.2/tests/run.yaml
- test/e2e-tests.sh
Allow overriding the GO cache, GO mod caching and golangci-lint caching.
Optimize golang-build and golang-test to not do a fulll copy of the source
inside the GOPATH if we have a go.mod in source root directory.
Changed the test for smaller repo since the pipeline/cli one were really slow (~12mn per test)
Background: https://blog.chmouel.com/2021/05/25/speed-up-your-tekton-pipeline-caching-the-hacky-way/
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalo …
> Allow overriding GO caching environment variable

- task/send-to-webhook-slack/0.1/README.md
- task/send-to-webhook-slack/0.1/send-to-webhook-slack.yaml
Add a few more parameters to Slack webhook to make it more Tekton like in a Slack channel.
review them:
---
> Add extra possibility for username and emoij to make it more Tekton Like

- task/github-add-comment/0.3/github-add-comment.yaml
This use python multi string when getting the comment
params so we don't bug out on multi lines comments in 0.3 version of github-add-comment
/cc @chmouel @afrittoli 
review them:
```
spec:
```
---
> Fix getting comment with multi Lines in 0.3 version of github-add-comment

- task/git-clone/0.4/README.md
- task/git-clone/0.4/git-clone.yaml
- task/git-clone/0.4/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.4/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.4/samples/git-clone-sparse-checkout.yaml
- task/git-clone/0.4/samples/using-git-clone-result.yaml
- task/git-clone/0.4/tests/run.yaml
This commit introduces a 0.4 version of git-clone, fixing several
problems with the 0.3 git-clone Task:
1. Credentials in 0.3 could not be passed directly to the Task via
a Workspace. User had to rely on creds-init.
2. There was no support for running as a non-root user.
This commit introduces a new version of git-clone that fixes both
of these issues. Credentials can now be supplied directly using a
Secret workspace. A nonroot user is provided with UID 65532 that
can clone repos without requiring root permissions.
/hold
Requires https://github.com/tektoncd/pipeline/pull/3700 and https://github.com/tektoncd/pipeline/pull/3727 to be merged in Pipelines before this Task will work.
review them:
```
spec: …
```
> Add non-root user support and workspace credentials to git-clone

- task/jib-maven/0.4/README.md
- task/jib-maven/0.4/jib-maven.yaml
- task/jib-maven/0.4/tests/internal-registry/internal-registry.yaml
- task/jib-maven/0.4/tests/pre-apply-task-hook.sh
- task/jib-maven/0.4/tests/resources.yaml
- task/jib-maven/0.4/tests/run.yaml
This will add a new version 0.4 in jib-maven task which
have only one change of different mounth rather than /etc/ssl/certs
as mounting at that location is overidding the default certs of
the image. This will make the certs to mount at different path
/tekton-custom-certs
review them:
```
spec:
```
---
[validation]: …
> Bump jib-maven task to 0.4 to fix certs mount path

- task/gitleaks/0.1/README.md
- task/gitleaks/0.1/samples/run.yaml
- task/gitleaks/0.1/tests/run.yaml
Changed Config file url to the one present in [gitleaks/0.1/samples](https://github.com/tektoncd/catalog/tree/main/task/gitleaks/0.1/samples)
> change config file url for gitleaks

- task/github-set-status/0.2/README.md
- task/github-set-status/0.2/github-set-status.yaml
Add the option to influence the authorization type so a user could use Basic Auth with prefabricated b64 encoded token.
Not the most secure option, but it's another option for setting commit status.
> Add option to use Basic Auth

- task/argocd-task-sync-and-wait/0.1/argocd-task-sync-and-wait.yaml
Logging in from one container and having sync and wait run in the separate containers does not work. Authenticate once and reuse the connection across the containers in a pod is not supported. Sync and wait fails with the authentication error. Either we login at each step or collapse sync and wait along with the login step. Or we could authenticate once and
find a way to how to reuse the same connection across the containers.
For now, combining everything into a single step.
review them:
```
spec:
```
---
[TEP]: …
> fix argocd sync and wait task

- task/ansible-runner/0.1/README.md
- task/ansible-runner/0.1/ansible-runner.yaml
- task/buildpacks-phases/0.1/README.md
- task/buildpacks-phases/0.1/buildpacks-phases.yaml
- task/buildpacks-phases/0.2/README.md
- task/buildpacks-phases/0.2/buildpacks-phases.yaml
- task/git-clone/0.1/README.md
- task/git-clone/0.1/git-clone.yaml
- task/git-clone/0.4/git-clone.yaml
- task/orka-deploy/0.1/orka-deploy.yaml
- task/orka-full/0.1/orka-full.yaml
With pipelines version 0.24.x+ `HOME` and default workingDir would not be set by
default and because of this some tasks in the catalog are failing. The following PR fixes
those tasks. The following tasks are changed:
- ansible-runner
- buildpacks-phases
- git-clone
- orka-deploy
- orka-full
review them:
```
spec:
```
---
[example]: …
> Add fixes for tasks as per latest pipelines 0.24+

- README.md
- recommendations.md
Following TEP 70, `tekton.dev/platforms` annotation can be used to specify on which platforms the resource can be run.
- add best practices for platform information in the recommendations.md
- add example of usage for tekton.dev/platforms annotation
review them:
```
spec:
```
---
> Add documentation about platform information for resources

- task/git-cli/0.2/README.md
- task/git-cli/0.2/git-cli.yaml
- task/git-cli/0.2/tests/run.yaml
Create a git-cli 0.2 tasks based on the same changes as have been done in git-clone 0.4. Therefore you can work with the same secret setup as the git-clone tasks.
review them:
> Add 0.2 git-cli task after git-clone 0.4 example

- task/github-set-status/0.2/github-set-status.yaml
The `github-set-status` task now uses volumeMount to read github token.
The volume approach is prefered over environment variable.
github-set-status: use secret volume for github token
1. https://github.com/tektoncd/catalog/issues/717
2. https://github.com/tektoncd/plumbing/pull/859
review them:
---
> github-set-status: use secret volume for github token

- pipeline/buildpacks/0.1/README.md
- pipeline/buildpacks/0.1/buildpacks.yaml
- pipeline/buildpacks/0.1/samples/cache-image.yaml
- pipeline/buildpacks/0.1/samples/cache-volume.yaml
- pipeline/buildpacks/0.1/samples/env-vars.yaml
- pipeline/buildpacks/0.1/samples/run-image.yaml
- pipeline/buildpacks/0.1/tests/pre-apply-task-hook.sh
- pipeline/buildpacks/0.1/tests/run.yaml
These changes introduce the Buildpacks Pipeline. This pipeline
builds source into a container image using Cloud Native Buildpacks.
To do that, it uses builders to run buildpacks against your application source.
It relies on git-clone, buildpacks, and buildpacks-phases tasks to perform
its tasks.
- Depends on https://github.com/tektoncd/catalog/pull/654
- Depends on https://github.com/tektoncd/catalog/pull/655
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-c …
> Add pipeline/buildpacks/0.1

- task/openshift-client/0.1/README.md
- task/openshift-client/0.2/README.md
- task/openshift-client/0.2/openshift-client.yaml
- task/openshift-client/0.2/samples/run-with-workspace.yaml
- task/openshift-client/0.2/tests/run.yaml
For Task version 0.1
- The README was showing that the task uses the input resource of
cluster-type but the resource being used was of git-type so fixing that.
For Task version 0.2
- The task requires min pipelines version 0.17.0 as it uses two optional
workspaces. First workspace is for passing the manifests which we want
to apply on the cluster and second workspace can be used to mount the
kubeconfig file if in case we want to run the oc command on another
cluster.
review them:
```
spec:
```
_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTI …
> Openshift client task fix README of 0.1 and add 0.2

- recommendations.md
When discussing some potential ways a Task could be compromised,
@afrittoli mentioned that if a Task refers to some remote source for a
script, there is the potential for that source to be modified and run
something malicious inside a Task. As he described this, he mentioned
that our catalog recommends putting scripts into configmaps, which I was
surprised to see. A script inside a configmap does have this potential
attack vector (though you'd have to have write access to the configmap
to pull it off) but I'm actually a bit more concerned that this isn't
a great solution for maintaining scripts over time. Not to mention that
I'm not how we would support this in the catalog (we'd have to start
supporting applying and versioning ConfigMaps alongside the Tasks that
reference them).
So this …
> Recommend versioning script instead of using configmap 📝

- task/flake8/0.1/README.md
- task/flake8/0.1/flake8.yaml
- task/flake8/0.1/tests/run.yaml
- task/flake8/OWNERS
It's a word-for-word copy of the pylint-0.2 task.
Flake8 is another very popular python linting tool. There was no task for it yet so I figured I'd add it, based on the already existing pylint task. I made the OWNERS of this task the same as the OWNERS of the pylint task. Of course, I don't know if they're actually available for that, let me know if I need to change it. 
review them:
```
spec:
```
---
[example]: …
> Add flake8 task

- hack/diff-task-version
Using github.com/cli/cli it takes a PR URL as first argument and check
it out.
It will then detect automatically the old and new version and post a
comment to the PR with the diff and copy it in your clipboard (with
xclip on Linux and pbcopy on OSX)
> Add diff-task-version script

- task/mypy-lint/0.2/README.md
- task/mypy-lint/0.2/mypy-lint.yaml
- task/mypy-lint/0.2/tests/pre-apply-task-hook.sh
- task/mypy-lint/0.2/tests/resources.yaml
- task/mypy-lint/0.2/tests/run.yaml
This provides more flexibility to the user for which exact version of mypy should be used.
You can now specify which image to use, and which requirement_file to use. Aside from allowing you to specify the mypy version, this will also allow you to more closely mimic your eventual production environment.
review them:
```
spec:
```
--- …
> Add image and requirements_file params to mypy task

- task/black/0.2/README.md
- task/black/0.2/black.yaml
- task/black/0.2/tests/resources.yaml
- task/black/0.2/tests/run.yaml
This provides more flexibility to the user for which exact version of
black should be used. 
You can now specify which image to use, and which requirement_file to use. Aside from allowing you to specify the black version, this will also allow you to more closely mimic your eventual production environment.
See also #792 for a similar PR. 
review them:
```
spec:
```
---
[example]: …
> Add image and requirements_file params to black task

- task/generate-build-id/0.1/README.md
Fixes a simple typo in `generate-build-id` documentation.
review them:
```
spec:
```
---
> Fix typo in `generate-build-id` documentation

- task/github-add-comment/0.4/README.md
- task/github-add-comment/0.4/github-add-comment.yaml
- task/github-add-gist/0.1/README.md
- task/github-add-gist/0.1/github-add-gist.yaml
- task/github-add-labels/0.1/README.md
- task/github-add-labels/0.1/github-add-labels.yaml
- task/github-close-issue/0.2/README.md
- task/github-close-issue/0.2/github-close-issue.yaml
- task/github-create-deployment-status/0.1/README.md
- task/github-create-deployment-status/0.1/github-create-deployment-status.yaml
- task/github-create-deployment/0.2/README.md
- task/github-create-deployment/0.2/github-create-deployment.yaml
- task/github-open-pr/0.1/README.md
- task/github-open-pr/0.1/github-open-pr.yaml
- task/github-request-reviewers/0.1/README.md
- task/github-request-reviewers/0.1/github-request-reviewers.yaml
- task/github-set-status/0.2/README.md
- task/github-set-status/0.2/github-set-status.yaml
Annotation about linux/amd64, linux/s390x and linux/ppc64le platforms was added to the latest versions of the github-* tasks.
The tasks were tested for linux/amd64, linux/s390x, and linux/ppc64le.
review them:
```
spec:
```
---
> Add platforms annotation to github-* tasks

- task/kaniko/0.4/README.md
- task/kaniko/0.4/kaniko.yaml
Annotation about `linux/amd64`,`linux/s390x`, and `linux/ppc64le` platforms was added to the latest versions of the kaniko task, as well as information which custom images to use for `linux/s390x` and `linux/ppc64le` platforms.
`JQ_IMAGE` parameter is introduced with default value from the existing task to be able to use custom image for non-Intel architecture.
The changes were tested for `linux/amd64`,`linux/s390x`, and `linux/ppc64le` platforms.
review them:
```
spec:
```
---
[TEP]: …
> Add platforms annotation to kaniko task

- task/send-to-channel-slack/0.1/README.md
- task/send-to-channel-slack/0.1/send-to-channel-slack.yaml
- task/send-to-microsoft-teams/0.1/README.md
- task/send-to-microsoft-teams/0.1/send-to-microsoft-teams.yaml
- task/send-to-telegram/0.1/README.md
- task/send-to-telegram/0.1/send-to-telegram.yaml
- task/send-to-webex-room/0.1/README.md
- task/send-to-webex-room/0.1/send-to-webex-room.yaml
- task/send-to-webhook-slack/0.1/README.md
- task/send-to-webhook-slack/0.1/send-to-webhook-slack.yaml
Annotation about linux/amd64, linux/s390x, and linux/ppc64le platforms is added to the latest versions of the send-to-* tasks.
Curl image used in the tasks is upgraded from 7.68.0 to 7.70.0 to use multi-arch version.
review them:
```
spec:
```
---
> Add platforms annotation to send-to-* tasks

- task/gitlab-set-status/0.1/README.md
- task/gitlab-set-status/0.1/gitlab-set-status.yaml
- task/gitlab-set-status/0.1/tests/fixtures/gitlab-set-status.yaml
- task/gitlab-set-status/0.1/tests/pre-apply-task-hook.sh
- task/gitlab-set-status/0.1/tests/run.yaml
It's basically the gitlab variant of the github-set-status task
review them:
```
spec:
```
---
> Add gitlab-set-status task

- task/upload-pypi/0.2/README.md
- task/upload-pypi/0.2/samples/run.yaml
- task/upload-pypi/0.2/tests/pre-apply-task-hook.sh
- task/upload-pypi/0.2/tests/resources.yaml
- task/upload-pypi/0.2/tests/run.yaml
- task/upload-pypi/0.2/upload-pypi.yaml
(Created new PR with hopefully fixed easycla)
Added 0.2 version of the upload-pypi task with the following changes/improvements:
- Added optional parameters for secret name and keys
- Added optional prebuild script parameter
- Added builder image parameter and changed to python image instead of Twine
review them:
> Add upload pypi 0.2 task

- task/buildah/0.2/README.md
- task/buildah/0.2/buildah.yaml
- task/skopeo-copy/0.1/README.md
- task/skopeo-copy/0.1/skopeo-copy.yaml
`quay.io/buildah/stable:v1.18.0` and `quay.io/skopeo/stable:v1.3.0` are multi-arch images, bumping images to these versions for buildah and skopeo-copy will allow to run the tasks on different architectures.
The update is tested for `linux/amd64`, `linux/s390x` and `linux/ppc64le` platforms. Both image versions have also `linux/arm64` support, so this platform is also mentioned.
review them:
```
spec:
```
--- …
> Bump skopeo image to v1.3.0 and buildah image to v1.18.0

- task/kaniko/0.5/README.md
- task/kaniko/0.5/kaniko.yaml
- task/kaniko/0.5/tests/pre-apply-task-hook.sh
- task/kaniko/0.5/tests/resources.yaml
- task/kaniko/0.5/tests/run.yaml
Task now uses --digest-file flag to create a results file with the
digest of a built image.
Task now uses `--digest-file` flag to create a results file with the digest of a built image as was discussed in #324 
review them:
```
spec:
```
---
> Add kaniko task 0.5

- task/kn/0.1/README.md
Helping a user in Knative slack, I noticed that the documented default on TektonHub (and the catalog) was different from what was actually in the task.  This corrects the README.
/kind bug
review them:
- [N/A] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [N/A] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [N/A] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-mes …
> Fix the README to reflect actual defaults.

- task/trivy-scanner/0.1/README.md
- task/trivy-scanner/0.1/tests/pvc.yaml
- task/trivy-scanner/0.1/tests/run.yaml
- task/trivy-scanner/0.1/trivy-scanner.yaml
- task/trivy-scanner/OWNERS
- Task provides a scanner that can be used in CI/CD pIpelines.
review them:
```
spec:
```
---
> Add new task trivy-scanner - replaces PR https://github.com/tektoncd/catalog/pull/819

- task/github-open-pr/0.1/github-open-pr.yaml
Fix indenting and add readonly
Fixes for github open PR after https://github.com/tektoncd/catalog/pull/778 got merged
review them:
> Use secrets through volume mounts

- task/orka-full/0.1/tests/mods/mod_task.py
- test/e2e-common.sh
The `go-rest-api-test` image is used in many catalog tests. To run the tests on many platforms, the image should be the multi-arch one, which is introduced in this PR. At this moment platforms of `gcr.io/tekton-releases/dogfooding/go-rest-api-test:latest` image are `linux/amd64`, `linux/ppc64le`, `linux/s390x`, `linux/arm64`.
review them:
```
spec:
```
---
[example]: …
> Use multi-arch go-rest-api-test image

- task/golang-build/0.2/README.md
- task/golang-build/0.2/golang-build.yaml
- task/golang-fuzz/0.1/README.md
- task/golang-fuzz/0.1/golang-fuzz.yaml
- task/golang-test/0.2/README.md
- task/golang-test/0.2/golang-test.yaml
Annotation about linux/amd64, linux/s390x, and linux/ppc64le platforms was added to the latest versions of the golang-* tasks.
The tasks were tested for linux/amd64, linux/s390x, and linux/ppc64le.
review them:
```
spec:
```
---
> Add platforms annotation to golang-* tasks

- task/kube-linter/0.1/README.md
- task/kube-linter/0.1/kube-linter.yaml
The `plain` option allows for a human-readable output from the kube-linter task. `json` and `sarif` is more meant to be programmatically consumed. This is a standard option for kube-linter, so no change in the task was required, just a documentation update.
review them:
```
spec:
```
---
[validation]: …
> Add 'plain' option to kube-linter output formatting

- hack/diff-task-version
Github markdown allows using 4 (or more) backticks to differentiate
between triple backticks inside the code blocks. Seeing as how most
task-diffs will probably have some form of markdown with codeblocks
inside them, this will escape that.
Of course, if there are code blocks inside the diff with 4 backticks, we're back to square one. We could combat that by using 5 backticks and so on. But I guess let's just start with 4 for now 😃 
DISCLAIMER: I have not run it to verify that it works correctly, as I don't have everything set up for this. If someone is able to do so that would be great!
review them:
```
spec:
```
_See [the …
> Make diff-task handle code blocks

- test/e2e-common.sh
- test/linux-s390x.sh
PLATFORM env variable is introduced. This variable allows to run tests for specific platform (for instance, "linux/s390x" or "linux/ppc64le").
If the environment variable is specified:
- some tests are updated with different image values, required for specific platform.
Image names should be specified in script file, separate for each platform. In the current code script file for linux/s390x is proposed.
- only tasks, which have mention about corresponding platform support in the annotation, will be tested.
If PLATFORM env variable is not specified, the behaviour of test scripts will be similar to the one before the PR.
review them:
```
spec:
Paragraph(s) to …
```
> Extend catalog test script to run tests for different platforms

- task/buildah/0.3/README.md
- task/buildah/0.3/buildah.yaml
- task/buildah/0.3/samples/openshift-internal-registry.yaml
- task/buildah/0.3/tests/internal-registry/internal-registry.yaml
- task/buildah/0.3/tests/pre-apply-task-hook.sh
- task/buildah/0.3/tests/run.yaml
Adds a new parameter `SKIP_PUSH` to the buildah step to disable pushing the built container to a registry. We are using this as part of our Pull Request build pipeline: We just want to make sure the Docker build works and no breaking changes were made to the Dockerfile, but we do not actually want to push the resulting container to a registry (happens only on release builds).
As explained in the public tekton slack channel, `when` expressions can currently not be used in `Tasks` - therefore the parameter is read and dealt with in the script of the push step.
review them:
---
[example]: …
> buildah: allow skipping push of built container

- task/git-clone/0.5/README.md
- task/git-clone/0.5/git-clone.yaml
- task/git-clone/0.5/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.5/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.5/samples/git-clone-sparse-checkout.yaml
- task/git-clone/0.5/samples/using-git-clone-result.yaml
- task/git-clone/0.5/tests/run.yaml
Add a optional workspace for custom CAs. This will use pass down the optional
workspace path to git's GIT_SSL_CAPATH env variable (and subsequently to
libcurl).
Fixes #660 
review them:
```
spec:
```
---
> git-clone: support mounting custom CAs for https

- task/pytest/0.1/pytest.yaml
When no args are passed, we run pytest "" <path> which does not
work as expected. Only pass the args to pytest when there are
some defined.
Fixes #864
review them:
```
spec:
```
---
> [pytest] Fix issue when no args are passed

- task/aws-ecr-login/0.1/aws-ecr-login.yaml
Added optional: true flag for the secret workspace in aws-ecr-login task. In some cases the credentials are already provided without using a secret (same as aws-cli task).
review them:
> add optional flag to ecr-login workspace

- task/jib-maven/0.1/tests/run.yaml
- task/jib-maven/0.2/tests/run.yaml
- task/jib-maven/0.3/tests/run.yaml
- task/jib-maven/0.4/jib-maven.yaml
- task/jib-maven/0.4/tests/run.yaml
This will fix the issue of jib-maven task not passing digest to results
if the clone has happened in sub-directory and directory passed to
jib-maven task
It is because the directory param is not handled in path creation for digest
It will not break the existing the behaviour but fixing the issue for directory scenario
so doing the change in latest version
review them:
```
spec:
```
---
[example]: …
> Directory not handled in digest-to-results step

- task/jib-gradle/0.3/README.md
- task/jib-gradle/0.3/jib-gradle.yaml
- task/jib-gradle/0.3/tests/pre-apply-task-hook.sh
- task/jib-gradle/0.3/tests/resources.yaml
- task/jib-gradle/0.3/tests/run.yaml
Adds a parameter to the jib-gradle task in order to provide extra arguments to the gradle jib build. For instance to provide credentials for a private image repository.
review them:
> Add new jib-gradle version with optional arguments

- task/goreleaser/0.2/goreleaser.yaml
Use latest goreleaser version, willl be able to release to homebrew without producing this warning : 
```
Updated 2 casks.
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tektoncd/tools tap (not Homebrew/brew or Homebrew/core):
/usr/local/Homebrew/Library/Taps/tektoncd/homebrew-tools/Formula/tektoncd-cli.rb:6
```
> bump goreleaser to latest

- task/sendmail/0.1/sendmail.yaml
The recipients of the email are extracted from a variable using the
split() function on a blank space (' '). If there are additional blanks,
either before, after or in the middle of the receivers_email variable the
sendmail function will cause an exception. This patch makes sure that blanks
won't cause the exception.
review them:
```
spec:
```
---
[example]: …
> remove blanks from receivers_email

- task/jib-gradle/0.1/jib-gradle.yaml
- task/jib-gradle/0.2/jib-gradle.yaml
- task/jib-gradle/0.3/jib-gradle.yaml
Specification of Docker config location allows to point jib tool to the Docker config file with registry auth information, provided by Tekton via [service accounts](https://github.com/tektoncd/pipeline/blob/main/docs/auth.md#configuring-docker-authentication-for-docker).
Without this fix jib is not able to find credentials for private registries or registries will limited pulls and build fails.
Fix is provided for all 3 existing versions of the task.
review them:
```
spec:
```
---
[TEP]: …
> Add DOCKER_CONFIG env variable to jib-gradle

- task/golang-build/0.3/README.md
- task/golang-build/0.3/golang-build.yaml
- task/golang-build/0.3/tests/pre-apply-task-hook.sh
- task/golang-build/0.3/tests/resources.yaml
- task/golang-build/0.3/tests/run.yaml
Adding CGO_ENABLED and GOSUMDB as task parameters to be used as environment variables during the go `build` command. This allows for static builds that can run in a different base-image than the image used for the golang build.
review them:
- [V] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [V] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [V] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [V] Commit messages follow [commit message best …
> Task golang-build add extra build params allowing for static golang builds.

- task/golang-test/0.2/golang-test.yaml
Looks like the `context` param is never used in 0.2 which fails builds that don't have the golang sources at the workspace root. Seems like a regression from 0.1.
Append $(params.context) during source dir construction.
review them:
```
spec:
```
---
> Don't omit params.context in source path construction

- task/git-clone/0.5/README.md
Added documentation to recommend the usage of id_rsa rather than a custom private key name. Using a custom private key name will result in an SSH error:
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
"stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:149\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"
review them:
```
spec:
Paragraph(s) to describe the …
```
> Added comments regarding id_rsa as default filename for private key

- task/github-set-status/0.4/README.md
- task/github-set-status/0.4/github-set-status.yaml
The default image for the github-set-status is more than 800MB. The python code actually run in this task
is small and used only the stdlib. A smaller image would works just as well.
The new default is python-alpine (45MB), which is the smallest python image possible. It is now configurable as well.
review them:
---
> Smaller default image for github-set-status

- task/hadolint/0.1/README.md
Fix Readme hadolint task 0.1, tekton web catalog no compatible with some markdown syntax.
review them:
```
spec:
```
---
> Fix Readme hadolint task 0.1

- task/pytest/0.1/pytest.yaml
The quotation marks are breaking the proper execution of args in the pytest task.
Given these args:
```
- name: ARGS
value: -rfs --junitxml build/results.xml --cov-config .coveragerc --cov app --cov-report xml:coverage-reports/coverage-results.xml
```
This results in the following yaml for the taskrun pod:
```
pytest "-rfs --junitxml build/results.xml --cov-config .coveragerc --cov app --cov-report xml:coverage-reports/coverage-results.xml" "."
```
Removed the quotation marks around the args parameter in the script
review them:
> Fix pytest args

- test/linux-ppc64le.sh
This PR adds support to perform catalog testing on `ppc64le` platform. The `linux-ppc64le.sh` script is similar to one added in #797 for `s390x`. 
Script contains
- image values required for ppc64le platform
- tasks to skip on ppc64le platform
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
review them:
```
spec:
```
--- …
> Add test script to extend support for testing on ppc64le platform

- task/argocd-task-sync-and-wait/0.1/argocd-task-sync-and-wait.yaml
- task/argocd-task-sync-and-wait/0.2/README.md
- task/argocd-task-sync-and-wait/0.2/argocd-task-sync-and-wait.yaml
Signed-off-by: Jann Fischer <jfischer@redhat.com>
This changes the container registry where Argo CD image is pulled from docker.io to quay.io (the project deprecated publishing on Docker Hub since a few releases, and will stop publishing new images to there soon). Also bumps the default version used by the task to the latest stable release.
review them:
```
spec:
```
---
[example]: …
> Small changes to task argocd-task-sync-and-wait

- task/upload-pypi/0.2/upload-pypi.yaml
`upload-pypi` Task version 0.2 is failing during nightly tests and
reason for the failure was that the image digest was inaccessible.
Updated the image with the tag `v0.0.2`
Closes #921 
review them:
```
spec:
```
---
> Fix upload-pypi task version 0.2

- task/gitea-set-status/0.1/README.md
- task/gitea-set-status/0.1/gitea-set-status.yaml
- task/gitea-set-status/0.1/tests/fixtures/gitea-post.yaml
- task/gitea-set-status/0.1/tests/pre-apply-task-hook.sh
- task/gitea-set-status/0.1/tests/run.yaml
Add a set commit status task for Gitea.
review them:
> Add V1 of gitea set status task

- task/golang-test/0.1/tests/run.yaml
Currently golang-test Task is using tektoncd/cli repo to test the task
golang-test but that's too flaky so changing that to use another repo.
review them:
```
spec:
```
---
> Update tests to use another repo in golang-test

- task/hadolint/0.1/hadolint.yaml
Improve ignore rules. 
Multiple rules do not need to indicate the "--ignore" parameter for each one.
Example:
```
- name: ignore-rules
value: 'DL3013,DL3018,DL3042,DL4006,SC2086'
```
review them:
```
spec:
```
---
> Hadolint improve ignore rules

- task/sonarqube-scanner/0.2/README.md
- task/sonarqube-scanner/0.2/samples/sonar-project.properties
- task/sonarqube-scanner/0.2/sonarqube-scanner.yaml
- task/sonarqube-scanner/0.2/tests/pre-apply-task-hook.sh
- task/sonarqube-scanner/0.2/tests/resources.yaml
- task/sonarqube-scanner/0.2/tests/run.yaml
Changes the source workspace name to `source` instead of `source-dir`. When running code-coverage analysis in pytest (possibly other tasks) the workspace dir is hardcoded into the coverage file. This change makes sure the source workspace path sonarqube-scanner is the same path as in the coverage file.
I also added a test (as there was none). This uses a public sonarcloud project as it's very resource intensive to run an entire sonarqube as a sidecar.
review them:
> Change sonarqube scanner workspace name + tests

- task/gcs-upload/0.2/README.md
- task/gcs-upload/0.2/gcs-upload.yaml
- task/gcs-upload/0.2/samples/gcs-sample.yaml
The gcs-upload task v0.1, when dealing with folders, uses the "-d"
option by default, which deletes remote files by default. This is
a relatively dangerous choice of default, and it's safer to make
that as an opt-in, as it may result in deletion of a lot of remote
files by accident.
V0.2 has a new parameter "deleteExtraFiles" which corresponds to
gsutil "-d" flag. deleteExtraFiles defaults to false, making the
default behaviour of the task different from v0.1.
V0.2 replaces parameters in the script with environment variables
for security as recommended in the catalog best practices.
The cloud-sdk image version has been updated to 390.0.0-slim which
is newer, ~60% smaller than the current image and includes gsutil.
These are the …
> gcs-upload v0.2 do not delete missing files by default

- task/kaniko/0.6/kaniko.yaml
Added -n to the echo command used to export the IMAGE_URL result in order to avoid to add a new line after the image url that caused gke-deploy in a pipeline to fail with a "could not parse reference" when IMAGE_URL result is used as an argument to the --image parameter in gke-deploy
> added -n to IMAGE_URL result to avoid adding a line feed

- task/gradle/0.1/README.md
- task/gradle/0.1/gradle.yaml
- task/gradle/0.1/tests/pre-apply-task-hook.sh
- task/gradle/0.1/tests/resources.yaml
- task/gradle/0.1/tests/run.yaml
- task/gradle/OWNERS
- Create Gradle Task
- Add tests for gradle task
- Move first version into 0.1 directory
Add a new task which runs a Gradle build which can then feed into other tasks.
review them:
```
spec:
```
---
> Add Task for Gradle builds

- task/gcs-upload/0.3/gcs-upload.yaml
The new param introduced in the latest version of the task was meant
to have a default value (as documented). Actually set the default.
review them:
```
spec:
```
---
> Add missing default value in gcs-upload param

- task/argocd-task-sync-and-wait/0.2/argocd-task-sync-and-wait.yaml
Added a type to the params to prevent the Task breaking in OpenShift Pipelines (this requires an explicit type)
review them:
```
spec:
```
---
> add type to params (needed for openshift)

- task/upload-pypi/0.2/tests/pre-apply-task-hook.sh
Currently in the tests of upload-pypi task, pypiserver was pointing to
latest and there are some recent changes made there which is breaking
the test here. Pinning the version to v1.4.2
review them:
```
spec:
```
---
> Fix pypiserver in tests of upload-pypi task

- task/ansible-runner/0.1/tests/resources.yaml
- task/blue-green-deploy/0.1/tests/resources.yaml
- task/kubernetes-actions/0.2/tests/resources.yaml
- task/tkn/0.2/tests/resources.yaml
- task/tkn/0.3/tests/resources.yaml
RBAC v1beta1 was deprecated in kubernetes and was removed in recent
versions.
review them:
```
spec:
```
---
> Use RBAC v1 instead of v1beta1 in tasks' tests

- test/linux-ppc64le.sh
- test/linux-s390x.sh
This PR contains Multi-arch gradle image values for ppc64le, s390x platforms. 
This PR fixes https://github.com/tektoncd/catalog/issues/987
Script contains
- Gradle image values required for ppc64le,s390x platform
review them:
```
spec:
```
---
> Use Multi-arch gradle image for ppc64le, s390x gradle tasks

- task/buildah/0.4/README.md
- task/buildah/0.4/buildah.yaml
- task/buildah/0.4/samples/openshift-internal-registry.yaml
- task/buildah/0.4/tests/internal-registry/internal-registry.yaml
- task/buildah/0.4/tests/pre-apply-task-hook.sh
- task/buildah/0.4/tests/run.yaml
buildah v1.18.0 is pretty old - update to the latest v1.23.3. This fixes a few security advisories in buildah and also from its dependencies (I'm not sure if they affect buildah when used in Tekton).
Replaces #969 
review them:
```
spec:
```
---
> Update buildah to v1.23.3 (creating buildah task v0.4)

- task/git-clone/0.7/README.md
- task/git-clone/0.7/git-clone.yaml
- task/git-clone/0.7/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.7/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.7/samples/git-clone-sparse-checkout.yaml
- task/git-clone/0.7/samples/using-git-clone-result.yaml
- task/git-clone/0.7/tests/run.yaml
**Issue:** tried cloning secured repository by creating secret for `crt` and mounted using `ssl-ca-directory` but still faced below issue
```
[clone] {"level":"error","ts":1655989849.1085541,"caller":"git/git.go:55","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nfatal: unable to access 'https://gitlab.cee.redhat.com/tekton/plumbing.git/': SSL certificate problem: unable to get local issuer certificate\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:55\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:150\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:225"}
```
* …
> Update git-clone task to fix custom CAs for https and bump to 0.7 version

- task/git-clone/0.5/README.md
- task/git-clone/0.6/README.md
* Updated readme with instruction on how to use `ssl-ca-directory` workspace
review them:
```
spec:
```
---
> Update readme on how to use ssl-ca-directory workspace for 0.5 and 0.6 git-clone

- task/orka-init/0.1/tests/resources.yaml
- task/orka-init/0.2/tests/resources.yaml
Suffix version in orka-init tests
Orka-init's both versions tests were using the same name of ClusterRole
and ClusterRoleBinding. Because of this, while running tests if any of
the version's tests gets completed, the resources are pruned which can
cause trouble for other Task.
Suffixing the version in the name of ClusterRole and ClusterRoleBinding
review them:
```
spec:
```
---
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organiz …
> Fix orka-init tests

- task/gcloud/OWNERS
This PR makes the Google Tekton team owners of the `gcloud` task; these are the most logical owners. 😺
review them:
---
> Add Googlers as OWNERS of gcloud task.

- task/git-clone/0.8/git-clone.yaml
- task/kn-apply/0.2/kn-apply.yaml
- task/kn/0.2/kn.yaml
- task/skopeo-copy/0.2/skopeo-copy.yaml
- task/tkn/0.4/tkn.yaml
In an effort to reduce permissions for certain tasks in #1034, the HOME
directory was either set to `/home/nonroot` or was unchanged. This
caused the tasks to fail when being run under limited permissions as
they could not create `/home/nonroot` or write to `/` in some cases.
This commit follows suit with #860 where HOME is set to `/tekton/home`
so that the task can perform actions in it.
review them:
> Set HOME to /tekton/home for nonroot tasks

- .github/pull_request_template.md
This PR inserts colons that I missed in #1040 (oops 🤷🏾) so that the `pull_request_template`
formats correctly in markdown.
Also: fixes whitespace in note to _See the contribution guide_.
/kind misc
review them:
[authoring]: …
> Fix markdown link resolution in PR template.

- task/sonarqube-scanner/0.1/sonarqube-scanner.yaml
- task/sonarqube-scanner/0.2/sonarqube-scanner.yaml
- task/sonarqube-scanner/0.3/README.md
- task/sonarqube-scanner/0.3/samples/sonar-project.properties
- task/sonarqube-scanner/0.3/sonarqube-scanner.yaml
- task/sonarqube-scanner/0.3/tests/pre-apply-task-hook.sh
- task/sonarqube-scanner/0.3/tests/resources.yaml
- task/sonarqube-scanner/0.3/tests/run.yaml
Deprecate existing versions of sonarqube-scanner
As of now, sonarqube-scanner task version 0.1 and 0.2 are using an older
version of sonarqube-scanner-cli image ie 4.5 which is around 2 years
old which makes it incompatible with existing versions of compatible
node. So deprecating. Will be adding the stable 0.3 version for the
same.
Add SonarQube version 0.3
The following new version of SonarQube consists of various enhancements
such as:
- Basic sonar properties can now be passed via parameters
- `sonar-settings` workspace is now optional
- Image is now paramterized so that if anyone wants to use their own
sonar-scanner-cli image then they can easily use it
- Script improvements
/kind feature
These are the criteria that every PR should …
> Bump sonarqube-scanner task to 0.3 and deprecate the existing ones

- task/buildah/0.5/buildah.yaml
Move the application of dockerconfig to before the `buildah bud` command to allow for pulling images from private registries.
Resolves #1085
review them:
```
spec:
```
[example]: …
> Use dockerconfig for buildah bud

- task/yq/0.4/README.md
- task/yq/0.4/tests/pre-apply-task-hook.sh
- task/yq/0.4/tests/resources.yaml
- task/yq/0.4/tests/run.yaml
- task/yq/0.4/yq.yaml
The yq task was missing a -P (pretty print) option, as well as a --no-color option. Instead of making new task versions (and params) for each of the myriad of options yq offers, I figured that what I want in a `yq` task is to be able to use yq, however I want it. A script is more suitable for that.
The only problem I have with this change is that it's quite different from the previous versions. I was thinking about splitting it up into a new task, but then the new task's name would not have been `yq`, or the old task would have to be renamed to `yq-replace`, and then we would still be stuck with a big change for every user.
In theory, if you update your task you would take into account you might have to update your pipelines to make them work with the new task version.
Let me know if you …
> Add fully flexible script to yq task

- task/sonarqube-scanner/0.3/sonarqube-scanner.yaml
fix shellcheck error SC2086
Fixes error from catalog build job by double quoting variable used in shell script.
> double quote to prevent globbing and word splitting

- task/orka-deploy/0.2/README.md
- task/orka-deploy/0.2/orka-deploy.yaml
- task/orka-deploy/0.2/samples/parallel-deploy.yaml
- task/orka-deploy/0.2/samples/use-ssh-key.yaml
- task/orka-deploy/0.2/tests/mocks/orka.yaml
- task/orka-deploy/0.2/tests/mods/mod_task.py
- task/orka-deploy/0.2/tests/mods/sidecars.yaml
- task/orka-deploy/0.2/tests/mods/volumes.yaml
- task/orka-deploy/0.2/tests/pre-apply-task-hook.sh
- task/orka-deploy/0.2/tests/resources.yaml
- task/orka-deploy/0.2/tests/run.yaml
Added version `0.2` for `orka-deploy` task
* Compatibility changes to make the pipelines also work properly when using Tekton v0.34.1
* Added additional task parameters for feature parity with Orka v2.1.0:
* `system-serial`: Assign an owned macOS system serial number to the VM (on Intel nodes only).
* `vm-metadata`: Inject custom metadata to the VM (on Intel nodes only)
* `gpu-passthrough`: Enables or disables GPU passthrough for the VM (on Intel nodes only).
* Changes in scripts to dynamically add additional parameters to VM config/deploy request when they are passed in pipelines.
* Requires `task/orka-init/0.2/orka-init.yaml` in `pre-apply-task-hook.sh` in order for tests to work.
review them:
```
spec: …
```
> v0.2 for orka-deploy task

- task/git-clone/0.9/README.md
- task/git-clone/0.9/git-clone.yaml
- task/git-clone/0.9/samples/git-clone-checking-out-a-branch.yaml
- task/git-clone/0.9/samples/git-clone-checking-out-a-commit.yaml
- task/git-clone/0.9/samples/git-clone-for-ssl-ca.yaml
- task/git-clone/0.9/samples/git-clone-sparse-checkout.yaml
- task/git-clone/0.9/samples/using-git-clone-result.yaml
- task/git-clone/0.9/tests/run.yaml
Note: this is supposed to be similar to the PR https://github.com/tektoncd/catalog/pull/1076. I just didn't want to change its commit structure as the CONTRIBUTING.md suggests us to push one commit with the version copy first.
- Bump up version of `git-init` image to `0.40.2`
- Fix tests by adding the `safe.directory` config to git
- Change the HOME directory so the ssh authentication works fine
review them:
```
spec:
```
_See [the …
> git-clone: 0.8 -> 0.9, bump git-init image + fix tests

- task/git-clone/0.9/git-clone.yaml
We were doing the git safe add-directory first but when having a
WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND we would erase the .gitconfig and
that safe variable would not be there anymore.
Do this only right before calling the git-init so we know the setting
would be applied.
cc @jhonis
> Make directory safe only right before the git-init

- task/git-clone/0.9/README.md
The "using basic-auth section" of the readme for the `git-clone` task  had a few typos
Fixed a typo in the basic authentication section of the readme
review them:
```
spec:
```
[example]: …
> Fixed typo In Readme

- task/git-clone/0.9/git-clone.yaml
when trying to cleandir, there could be some non owner files in there (ie: lost+found)
let's not fail when failed to clean.
review them:
```
spec:
```
[example]: …
> git-clone don't fail when cleandir has failed

- task/buildah/0.5/buildah.yaml
- task/buildah/0.5/tests/run.yaml
While consuming the result `IMAGE_URL` produced by buildah task, a new line character '\n' was getting appended and the same was causing issues which using the task.
- Added `-n` flag with echo in order to remove the newline character
- Modified the tests for the same
/kind bug
fixes #1133
review them:
```
spec:
``` …
> Remove newline character from buildah results

- task/pylint/0.2/pylint.yaml
- task/upload-pypi/0.2/tests/run.yaml
- test/e2e-tests.sh
- Force the version of pylint to 0.12.0 in order to fix the CI
- Bump the pipelines version from v0.40.0 to v0.44.0
/kind misc
review them:
```
spec:
```
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/ …
> Fix nightly ci and bump pipelines version to v0.44.0

- task/gradle/0.3/README.md
- task/gradle/0.3/gradle.yaml
- task/gradle/0.3/tests/pre-apply-task-hook.sh
- task/gradle/0.3/tests/resources.yaml
- task/gradle/0.3/tests/run.yaml
Added optional workspace gradle-config, the gradle.properties in this workspace wil be copied to the home directory of the gradle user. 
review them:
```
spec:
This Task can be used to run a Gradle build.
``` …
> Added optional workspace gradle-config

- pipeline/build-push-gke-deploy/0.1/samples/build-push-gke-deploy-example.md
The path in the `build-push-gke-deploy-example` walkthrough appears to be out of date. I've updated it with what I believe is the correct path.
> Fix typo in build-push-gke-deploy-example walkthrough

- task/boskos-acquire/0.1/boskos-acquire.yaml
- task/buildah/0.1/buildah.yaml
- task/buildah/0.2/buildah.yaml
- task/buildah/0.3/buildah.yaml
- task/gke-cluster-create/0.1/gke-cluster-create.yaml
- task/jib-gradle/0.2/jib-gradle.yaml
- task/jib-gradle/0.3/jib-gradle.yaml
- task/jib-maven/0.2/jib-maven.yaml
- task/jib-maven/0.3/jib-maven.yaml
- task/jib-maven/0.4/jib-maven.yaml
- task/kaniko/0.1/kaniko.yaml
- task/kaniko/0.2/kaniko.yaml
- task/kaniko/0.3/kaniko.yaml
- task/kaniko/0.4/kaniko.yaml
- task/kaniko/0.5/kaniko.yaml
- task/pull-request/0.1/samples/static.yaml
- task/s2i/0.2/s2i.yaml
- task/s2i/0.3/s2i.yaml
Some tasks were referencing absolute paths for `results`. It is recommended to use variable replacement syntax in the API spec. This PR migrates the absolute paths for results to variable syntax notation. This PR addresses Issue https://github.com/tektoncd/catalog/issues/1163.
review them:
```
spec:
```
[TEP]: …
> Fix hardcoded result path usage in Tasks

- task/gitlab-set-status/0.2/README.md
- task/gitlab-set-status/0.2/gitlab-set-status.yaml
- task/gitlab-set-status/0.2/tests/fixtures/gitlab-set-status.yaml
- task/gitlab-set-status/0.2/tests/pre-apply-task-hook.sh
- task/gitlab-set-status/0.2/tests/run.yaml
/kind feature
Add version 0.2 to the `gitlab-set-status` task.
This update introduced a `coverage` parameter for the `gitlab-set-status` task for displaying the coverage information in GitLab pipelines.
Reference: https://docs.gitlab.com/ee/api/commits.html#set-the-pipeline-status-of-a-commit
review them:
```
spec:
``` …
> Add version 0.2 to `gitlab-set-status` task

- task/kamel-run/0.1/README.md
- task/kamel-run/0.1/kamel-run.yaml
- task/kamel-run/0.1/samples/run-external-build.yaml
- task/kamel-run/0.1/samples/run-operator-build.yaml
- task/kamel-run/0.1/support/camel-k-tekton.yaml
- task/kamel-run/0.1/tests/pre-apply-task-hook.sh
- task/kamel-run/0.1/tests/resources.yaml
- task/kamel-run/0.1/tests/run.yaml
- task/kamel-run/OWNERS
Closes https://github.com/apache/camel-k/issues/3795
Closes https://github.com/apache/camel-k/issues/682
With this PR we are introducing the first version of `kamel-run` task which will allow [Camel K](https://github.com/apache/camel-k) users to integration Tekton pipelines when building and deploying Camel application in their CICD pipelines. The task is based on the same container image used by the Camel K operator, which contains the `kamel` CLI. The task is opinionated to let the user use the CLI as a deployment task only in a generic pipeline used to build Camel applications on K8S.
review them:
contains `/kind <type>`. Valid …
> feat: add Camel K run task

- task/skopeo-copy/0.1/skopeo-copy.yaml
- task/skopeo-copy/0.2/skopeo-copy.yaml
- task/skopeo-copy/0.3/skopeo-copy.yaml
The previous tag, quay.io/skopeo/stable:v1.9.0, no longer exists. This commit updates the image reference to use the `v1` floating tag.
review them:
```
spec:
```
[example]: …
> Fix skopeo image reference

- task/redhat-dependency-analytics/0.1/README.md
- task/redhat-dependency-analytics/0.1/redhat-dependency-analytics.yaml
- task/redhat-dependency-analytics/0.1/samples/pipeline-run.yaml
- task/redhat-dependency-analytics/0.1/samples/pipeline.yaml
- task/redhat-dependency-analytics/0.1/samples/secret.yaml
- task/redhat-dependency-analytics/0.1/samples/task-run.yaml
- task/redhat-dependency-analytics/0.1/samples/workspace.yaml
- task/redhat-dependency-analytics/0.1/tests/pre-apply-task-hook.sh
- task/redhat-dependency-analytics/0.1/tests/resources.yaml
- task/redhat-dependency-analytics/0.1/tests/run.yaml
This pull request marks a significant milestone in the Tekton Tasks evolution. We have undergone a comprehensive refactoring process and re-branded the project from "Red Hat Codeready Dependency Analysis" to "Red Hat Dependency Analytics". 
Within this update, we've introduced a fresh Tekton Task named "redhat-dependency-analytics", aligning with the Red Hat Dependency Analytics (RHDA) platform version `0.7.0-alpha`. One of the key highlights of this update is the integration of an image utilizing the Exhort JavaScript API.
In the current version of the Red Hat Dependency Analytics Tekton Task, language support is specifically tailored to Maven and NPM. Support for GoLang and Python will be resumed in future releases.
"Red Hat Codeready Dependency Analysis" tekton task is now considered …
> feat: introduce new task redhat-dependency-analytics for RHDA v0.7.0-alpha

- task/github-open-pr/0.2/github-open-pr.yaml
The `github-open-pr` task was missing a `"Content-Type"` header so I added it. Believe it or not, this single missing header makes the task not work for my use case so I need this to be merged 😭.
review them:
```
spec:
``` …
> fix: Add "Content-Type" header

- task/buildah/0.6/buildah.yaml
Currently buildah fails with the message below if CERT_DIR_FLAG empty but TaskRun reports successful
```
Error: accepts at most 1 arg(s), received 10
```
Adds shellcheck exception for `$(params.BUILD_EXTRA_ARGS)` and `$(params.PUSH_EXTRA_ARGS)` as these need to be able to support multiple parameters
review them:
```
spec:
```
_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more …
> Fix buildah task

- task/ansible-runner/0.2/ansible-runner.yaml
Ansible-Runner 0.2 uses the image with ansible-runner version 2.12 which is [EOL](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix).
This PR deprecates it since Tests are failing as a result.
review them:
```
spec:
```
[TEP]: …
> Deprecate ansible-runner 0.2

- task/ansible-builder/0.1/ansible-builder.yaml
Ansible Builder uses Ansible Runner as the base image and since the image points to v2.12 which is [EOL](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix), the tests are failing.
This PR marks `ansible-builder/0.1` as deprecated.
review them:
```
spec:
``` …
> Deprecate ansible-builder 0.1

- CONTRIBUTING.md
- stepaction/git-clone/0.1/README.md
- stepaction/git-clone/0.1/git-clone.yaml
- stepaction/git-clone/0.1/samples/git-clone-checking-out-a-branch.yaml
- stepaction/git-clone/0.1/samples/git-clone-checking-out-a-commit.yaml
- stepaction/git-clone/0.1/samples/git-clone-for-ssl-ca.yaml
- stepaction/git-clone/0.1/samples/git-clone-sparse-checkout.yaml
- stepaction/git-clone/0.1/samples/using-git-clone-result.yaml
- stepaction/git-clone/0.1/tests/run.yaml
- test/e2e-common.sh
- test/e2e-tests.sh
- test/run-test.sh
This PR sets up the tests for StepActions and adds a first StepAction `git-clone` to the catalog. 
It is based off the Task but with samples and tests updated.
This PR addresses the update to [TEP](https://github.com/tektoncd/community/pull/1137) and Issue https://github.com/tektoncd/catalog/issues/1218.
review them:
```
spec:
```
_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more …
> Add First StepAction `git-clone` to the catalog

- task/helm-upgrade-from-repo/0.3/README.md
- task/helm-upgrade-from-repo/0.3/helm-upgrade-from-repo.yaml
- task/helm-upgrade-from-repo/0.3/samples/helm-upgrade-from-repo-task-run.yaml.tmpl
- task/helm-upgrade-from-repo/0.3/tests/pre-apply-task-hook.sh
- task/helm-upgrade-from-repo/0.3/tests/run.yaml
- task/helm-upgrade-from-source/0.4/README.md
- task/helm-upgrade-from-source/0.4/helm-upgrade-from-source.yaml
- task/helm-upgrade-from-source/0.4/samples/helm-upgrade-from-source-task-run.yaml.tmpl
- task/helm-upgrade-from-source/0.4/tests/pre-apply-task-hook.sh
- task/helm-upgrade-from-source/0.4/tests/resources.yaml
- task/helm-upgrade-from-source/0.4/tests/run.yaml
This PR updates the default image used in the `helm-upgrade-from-repo` and `helm-upgrade-from-source` tasks from [v3.6.0](https://hub.docker.com/layers/lachlanevenson/k8s-helm/v3.6.0/images/sha256-b3510a2fb35cad3631e245e416b5e8b1d03b0184e0d125a4797e055201852ba3?context=explore) to [v3.10.2](https://hub.docker.com/layers/lachlanevenson/k8s-helm/v3.10.2/images/sha256-4ea644ab5330f22864ca12bde02414360d371de9db25f0c177638fa81bc69908?context=explore).
The main motivation for this change is that the existing version does not include [the `--dependency-upgrade` option](https://github.com/helm/helm/pull/9659). This change therefore provides the ability for charts to _not_ package their dependencies.
review them:
- See …
> Update default helm image for helm-upgrade-from- tasks

- task/remote-scp/0.1/README.md
- task/remote-scp/0.1/remote-scp.yaml
- task/remote-scp/0.1/samples/run.yaml
- task/remote-scp/0.1/samples/secrets.yaml
- task/remote-scp/0.1/samples/storage.yaml
Add remote-scp new task 
review them:
```
spec:
```
[authoring]: …
> Add remote-scp new task

- task/gradle/0.4/tests/run.yaml
- test/linux-ppc64le.sh
Replaces the GRADLE_IMAGE parameter for gradle/0.4 to the multi-arch alternative. Currently the image is x86 only.
Added an Extra MAVEN_IMAGE parameter which is missing for the maven-0-3 test via linux-ppc64le.sh script.
Added a patch command to enable Step Actions on the cluster. This is needed for stepaction test.
Added a patch command to disable Affinity Assistant  on the cluster. This allow binding of two PVCs at the same time and is needed by the maven-0-3 test.
review them:
```
spec:
one line summary …
```
> Fix catalog test for ppc64le

- task/rhacs-image-scan/4.0/README.md
- task/rhacs-image-scan/4.0/rhacs-image-scan.yaml
- task/rhacs-image-scan/4.0/samples/with-api-token/pipeline.yaml
- task/rhacs-image-scan/4.0/samples/with-api-token/pipelinerun.yaml
- task/rhacs-image-scan/4.0/samples/with-api-token/secrets.yaml
- task/rhacs-image-scan/4.0/samples/with-m2m-token/pipeline.yaml
- task/rhacs-image-scan/4.0/samples/with-m2m-token/pipelinerun.yaml
Add a new version of the `rhacs-image-scan` task that can be configured either with authorization using API tokens (similar configuration to 3.71 version of the task), or with authorization using short-lived tokens received from the new rhacs-m2m-authenticate task.
Both configuration variants have a sample with the expected Secret, Pipeline and PipelineRun objects.
review them:
```
spec:
``` …
> task: Add M2M support for rhacs-image-scan

- task/rhacs-deployment-check/4.0/README.md
- task/rhacs-deployment-check/4.0/rhacs-deployment-check.yaml
- task/rhacs-deployment-check/4.0/samples/with-api-token/pipeline.yaml
- task/rhacs-deployment-check/4.0/samples/with-api-token/pipelinerun.yaml
- task/rhacs-deployment-check/4.0/samples/with-api-token/secrets.yaml
- task/rhacs-deployment-check/4.0/samples/with-m2m-token/pipeline.yaml
- task/rhacs-deployment-check/4.0/samples/with-m2m-token/pipelinerun.yaml
Add support for short-lived tokens in `rhacs-deployment-check`, `rhacs-image-check` and `rhacs-image-scan` tasks.
The above three tasks have a new version that can be configured either with authorization using API tokens (similar configuration to `3.71` version of the tasks), or with authorization using short-lived tokens received from the new `rhacs-m2m-authenticate` task.
Both configuration variants have a sample with the expected `Secret`, `Pipeline` and `PipelineRun` objects.
review them:
- **No**. _Requires external service integration._
feature, …
> task: add short-lived token support in `rhacs-*` tasks

- task/rhacs-image-check/4.0/README.md
- task/rhacs-image-check/4.0/rhacs-image-check.yaml
- task/rhacs-image-check/4.0/samples/with-api-token/pipeline.yaml
- task/rhacs-image-check/4.0/samples/with-api-token/pipelinerun.yaml
- task/rhacs-image-check/4.0/samples/with-api-token/secrets.yaml
- task/rhacs-image-check/4.0/samples/with-m2m-token/pipeline.yaml
- task/rhacs-image-check/4.0/samples/with-m2m-token/pipelinerun.yaml
Add a new version of the `rhacs-image-check` task that can be configured either with authorization using API tokens (similar configuration to 3.71 version of the task), or with authorization using short-lived tokens received from the new rhacs-m2m-authenticate task.
Both configuration variants have a sample with the expected Secret, Pipeline and PipelineRun objects.
review them:
```
spec:
``` …
> task: Add M2M support for rhacs-image-check

- task/rhacs-m2m-authenticate/0.1/README.md
- task/rhacs-m2m-authenticate/0.1/rhacs-m2m-authenticate.yaml
- task/rhacs-m2m-authenticate/0.1/samples/configure-m2m.md
- task/rhacs-m2m-authenticate/0.1/samples/pipeline.yaml
- task/rhacs-m2m-authenticate/0.1/samples/pipelinerun.yaml
- task/rhacs-m2m-authenticate/OWNERS
Add a new task which handles authentication for RHACS tasks (i.e. `rhacs-image-scan, rhacs-image-check, rhacs-deployment-check`).
The task will allow folks to make use of projected volumes for obtaining a valid RHACS token instead of relying on long-living API tokens as before.
review them:
```
spec:
```
[TEP]: …
> task: add rhacs M2M authenticate task

- task/rhacs-generic/0.1/README.md
- task/rhacs-generic/0.1/rhacs-generic.yaml
- task/rhacs-generic/0.1/samples/pipeline.yaml
- task/rhacs-generic/0.1/samples/pipelinerun.yaml
- task/rhacs-generic/OWNERS
Add a generic task for custom interactions with Red Hat Advanced Cluster Security.
This allows users to perform any action with the `roxctl` cli.
review them:
```
spec:
```
[example]: …
> task: Add generic RHACS task

- test/linux-s390x.sh
Replaces the GRADLE_IMAGE parameter for gradle/0.4 to the multi-arch alternative. Currently the image is x86 only.
Added an Extra MAVEN_IMAGE parameter which is missing for the maven-0-3 test via linux-s390x.sh script.
Added a patch command to enable Step Actions on the cluster. This is needed for stepaction test.
Added a patch command to disable Affinity Assistant on the cluster. This allow binding of two PVCs at the same time and is needed by the maven-0-3 test.
review them:
```
spec:
one line summary of …
```
> fix catalog test failures on s390x

- task/python-boto3-aws/0.1/README.md
- task/python-boto3-aws/0.1/python-boto3-aws.yaml
- task/python-boto3-aws/0.1/samples/config-map.yaml
- task/python-boto3-aws/0.1/samples/run.yaml
- task/python-boto3-aws/0.1/samples/secret.yaml
review them:
```
spec:
```
[authoring]: …
> adding python boto3 task

- task/jira-get-ticket-status/0.1/README.md
- task/jira-get-ticket-status/0.1/jira-get-ticket-status.yaml
Added a new task `jira-get-ticket-status` to get the current status of a Jira ticket.
> Added jira-get-ticket-status new task

- task/aws-cli/0.2/aws-cli.yaml
Fixes the incorrect mountpath referenced in issue #1210 
review them:
```
spec:
``` …
> Corrected mountpath in aws-cli task

- task/buildah/0.8/README.md
- task/buildah/0.8/buildah.yaml
- task/buildah/0.8/samples/dockerconfig.yaml
- task/buildah/0.8/samples/openshift-internal-registry.yaml
- task/buildah/0.8/tests/internal-registry/internal-registry.yaml
- task/buildah/0.8/tests/pre-apply-task-hook.sh
- task/buildah/0.8/tests/run.yaml
- Don't use interpolation (move to env)
- Easier way of specifying build args - previously would have to use `BUILD_EXTRA_ARGS` and quote them very carefully
- Add warning for `BUILD_EXTRA_ARGS` and `PUSH_EXTRA_ARGS` that inputs need to be sanitized 
e.g. now the following are correctly passed as Dockerfile build arguments:
```
- name: BUILD_ARGS
value:
- |
foo=b\"a'z"u uu
- baz=8888$(echo foo)ssss`ssss` -v a:b
```
review them:
- [] Commit messages follow [commit message best practices][commit]
```
spec: …
```
> buildah 0.8

- task/skopeo-copy/0.4/README.md
- task/skopeo-copy/0.4/samples/docker-secret.yaml
- task/skopeo-copy/0.4/samples/quay-secret.yaml
- task/skopeo-copy/0.4/samples/run.yaml
- task/skopeo-copy/0.4/samples/serviceaccount.yaml
- task/skopeo-copy/0.4/skopeo-copy.yaml
- task/skopeo-copy/0.4/tests/pre-apply-task-hook.sh
- task/skopeo-copy/0.4/tests/run.yaml
Add a multiArch param to the skopeo copy task. From issue https://github.com/tektoncd/catalog/issues/1280 and PR #1281 tho I messed up squashing :(
/kind feature
review them:
- [ x] Follows the [authoring recommendations][authoring]
- [ x] Includes [docs][docs] (if user facing)
- [ x] Includes [tests][tests] (for new tasks or changed functionality)
- [ x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [ x] Commit messages follow [commit message best practices][commit]
- [ x] Has a kind label. You can add one by adding a comment on this PR that
contains `/kind <type>`. Valid types are …
> Add multi-arch parm

- task/conftest/0.2/README.md
- task/conftest/0.2/conftest.yaml
added 0.2 of contest as 0.1 was using a very old image / old api
review them:
```
spec:
```
[validation]: …
> added 0.2 of conftest

- task/sendmail/0.2/README.md
- task/sendmail/0.2/sendmail.yaml
review them:
```
spec:
```
[authoring]: …
> Fix for Issue 1285-: SendMail task was failing to execute successfully

- stepaction/tekton-catalog-publish/0.2/README.md
- stepaction/tekton-catalog-publish/0.2/samples/run-with-workspace-secret.yaml
- stepaction/tekton-catalog-publish/0.2/samples/run-without-workspace-secret.yaml
- stepaction/tekton-catalog-publish/0.2/samples/secrets.yaml
- stepaction/tekton-catalog-publish/0.2/tekton-catalog-publish.yaml
- stepaction/tekton-catalog-publish/0.2/tests/pre-apply-task-hook.sh
- stepaction/tekton-catalog-publish/0.2/tests/run.yaml
Add a new version of the catalog publish step action. This new version API is backwards compatible, as it adds one new optional parameter only, `TKN_ARGS`.
The new version includes the following changes:
- latest version of tkn image set by default
- sets two OCI labels org.opencontainers.image.description and org.opencontainers.image.version for each resource
- accepts TKN_ARGS which is passed to all resources and can be used to set additional OCI labels as well as other settings
review them:
```
spec: …
```
> New version of tekton catalog publish with labels

- task/maven/0.4/maven.yaml
Fix groupId typo in results for `mvn-goals` step in maven (0.4) task 
```
[maven-build : mvn-goals] ${project.gruopId}library-shop1.0.0
[maven-build : mvn-goals] org.acmelibrary-shop1.0.0
```
review them:
- ~[n/a] Includes [docs][docs] (if user facing)~
- ~[n/a] Includes [tests][tests] (for new tasks or changed functionality)~
- ~See the [end-to-end testing documentation][e2e] for guidance and CI details.~
- ~[n/a] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]~
- [n/a] File path follows …
> fix: groupId typo in maven (0.4) task results

- task/buildah/0.9/README.md
- task/buildah/0.9/buildah.yaml
- task/buildah/0.9/samples/dockerconfig.yaml
- task/buildah/0.9/samples/openshift-internal-registry.yaml
- task/buildah/0.9/tests/internal-registry/internal-registry.yaml
- task/buildah/0.9/tests/pre-apply-task-hook.sh
- task/buildah/0.9/tests/run.yaml
This PR makes it able to overwrite `--tls-verify` on push. It moves to the end of the command the variable `PARAM_PUSH_EXTRA_ARGS`. Otherwise you will have to disable `TLSVERIFY` for pull actions too and that is not desirable. This way one can run the action with the parameter `PUSH_EXTRA_ARGS=--tls-verify=false` and being able to push to an insecure registry. But still maintaining the TLS checks on build.
review them:
```
spec:
``` …
> fix(buildah): makes it able to overwrite --tls-verify on push

- task/gitleaks/0.1/gitleaks.yaml
- task/grype/0.1/grype.yaml
- task/jib-gradle/0.2/jib-gradle.yaml
- task/jib-gradle/0.3/jib-gradle.yaml
- task/jib-gradle/0.4/jib-gradle.yaml
- task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml
Following are the tasks which were failing in e2e tests:
1. gitleaks - v0.1
2. grype - v0.1
3. jib-gradle - v0.2, v0.3, v0.4
4. redhat-dependency-analytics v0.2
Marking them as deprecated until they are fixed or there is a new version available for that task. Also there are couple of PRs which are waiting for the CI to be green, this PR will unblock them.
/kind bug
review them:
```
spec:
``` …
> Fix e2e tests by deprecating the failing tasks

- task/kaniko/0.7/README.md
- task/kaniko/0.7/kaniko.yaml
- task/kaniko/0.7/tests/pre-apply-task-hook.sh
- task/kaniko/0.7/tests/resources.yaml
- task/kaniko/0.7/tests/run.yaml
This change adds the ability for a user of the kaniko task to override the image used for the write-url step. This will be useful in scenarios where pulling directly from docker.io is not desireable (or possible)
closes #1325 
review them:
```
spec:
```
[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekto …
> add image override parameter for write-url step in kaniko task

- README.md
Add ghcr.io migration banner to `README.md`. Add types to code blocks in and update links and references in manifests to use `ghcr.`
Issue tektoncd/website#645.
review them:
```
spec:
```
[example]: …
> Add ghcr.io migration banner to README.md

- stepaction/git-clone/0.1/git-clone.yaml
As gcr.io is deprecated, git-clone step action is still using referencing git-init image from gcr.io that's failing PipelineRuns.
review them:
```
spec:
```
[example]: …
> migrate git-init from gcr.io to ghcr.io
